# 1 "data/maps/LittlerootTown/scripts.pory"

# 2 "data/maps/LittlerootTown/scripts.pory"
# 1 "data/maps/LittlerootTown/scripts.pory"
# 3 "data/maps/LittlerootTown/scripts.pory"

# 4 "data/maps/LittlerootTown/scripts.pory"
# 2 "data/maps/LittlerootTown/scripts.pory"
# 5 "data/maps/LittlerootTown/scripts.pory"
.set LOCALID_TWIN, 1
# 6 "data/maps/LittlerootTown/scripts.pory"
# 3 "data/maps/LittlerootTown/scripts.pory"
# 7 "data/maps/LittlerootTown/scripts.pory"
.set LOCALID_MOM, 4
# 8 "data/maps/LittlerootTown/scripts.pory"
# 4 "data/maps/LittlerootTown/scripts.pory"
# 9 "data/maps/LittlerootTown/scripts.pory"
# 5 "data/maps/LittlerootTown/scripts.pory"
# 10 "data/maps/LittlerootTown/scripts.pory"
.set LOCALID_BIRCH, 7
# 11 "data/maps/LittlerootTown/scripts.pory"
# 6 "data/maps/LittlerootTown/scripts.pory"
# 12 "data/maps/LittlerootTown/scripts.pory"

# 13 "data/maps/LittlerootTown/scripts.pory"
# 7 "data/maps/LittlerootTown/scripts.pory"
# 14 "data/maps/LittlerootTown/scripts.pory"
LittlerootTown_MapScripts::
# 15 "data/maps/LittlerootTown/scripts.pory"
# 8 "data/maps/LittlerootTown/scripts.pory"
# 16 "data/maps/LittlerootTown/scripts.pory"
	map_script MAP_SCRIPT_ON_TRANSITION, LittlerootTown_OnTransition
# 17 "data/maps/LittlerootTown/scripts.pory"
# 9 "data/maps/LittlerootTown/scripts.pory"
# 18 "data/maps/LittlerootTown/scripts.pory"
	map_script MAP_SCRIPT_ON_FRAME_TABLE, LittlerootTown_OnFrame
# 19 "data/maps/LittlerootTown/scripts.pory"
# 10 "data/maps/LittlerootTown/scripts.pory"
# 20 "data/maps/LittlerootTown/scripts.pory"
	map_script MAP_SCRIPT_ON_WARP_INTO_MAP_TABLE, LittlerootTown_OnWarp
# 21 "data/maps/LittlerootTown/scripts.pory"
# 11 "data/maps/LittlerootTown/scripts.pory"
# 22 "data/maps/LittlerootTown/scripts.pory"
	.byte 0
# 23 "data/maps/LittlerootTown/scripts.pory"
# 12 "data/maps/LittlerootTown/scripts.pory"
# 24 "data/maps/LittlerootTown/scripts.pory"

# 25 "data/maps/LittlerootTown/scripts.pory"
# 13 "data/maps/LittlerootTown/scripts.pory"
# 26 "data/maps/LittlerootTown/scripts.pory"
	@ State descriptions for VAR_LITTLEROOT_TOWN_STATE
# 27 "data/maps/LittlerootTown/scripts.pory"
# 14 "data/maps/LittlerootTown/scripts.pory"
# 28 "data/maps/LittlerootTown/scripts.pory"
	@ 1: Met Rival
# 29 "data/maps/LittlerootTown/scripts.pory"
# 15 "data/maps/LittlerootTown/scripts.pory"
# 30 "data/maps/LittlerootTown/scripts.pory"
	@ 2: Saving Birch
# 31 "data/maps/LittlerootTown/scripts.pory"
# 16 "data/maps/LittlerootTown/scripts.pory"
# 32 "data/maps/LittlerootTown/scripts.pory"
	@ 3: Received Pokedex
# 33 "data/maps/LittlerootTown/scripts.pory"
# 17 "data/maps/LittlerootTown/scripts.pory"
# 34 "data/maps/LittlerootTown/scripts.pory"
	@ 4: Received Running Shoes
# 35 "data/maps/LittlerootTown/scripts.pory"
# 18 "data/maps/LittlerootTown/scripts.pory"
# 36 "data/maps/LittlerootTown/scripts.pory"

# 37 "data/maps/LittlerootTown/scripts.pory"
# 19 "data/maps/LittlerootTown/scripts.pory"
# 38 "data/maps/LittlerootTown/scripts.pory"
	@ State descriptions for VAR_LITTLEROOT_INTRO_STATE
# 39 "data/maps/LittlerootTown/scripts.pory"
# 20 "data/maps/LittlerootTown/scripts.pory"
# 40 "data/maps/LittlerootTown/scripts.pory"
	@ 1: In truck male
# 41 "data/maps/LittlerootTown/scripts.pory"
# 21 "data/maps/LittlerootTown/scripts.pory"
# 42 "data/maps/LittlerootTown/scripts.pory"
	@ 2: In truck female
# 43 "data/maps/LittlerootTown/scripts.pory"
# 22 "data/maps/LittlerootTown/scripts.pory"
# 44 "data/maps/LittlerootTown/scripts.pory"
	@ 3: Entered house
# 45 "data/maps/LittlerootTown/scripts.pory"
# 23 "data/maps/LittlerootTown/scripts.pory"
# 46 "data/maps/LittlerootTown/scripts.pory"
	@ 4: Told to go set clock
# 47 "data/maps/LittlerootTown/scripts.pory"
# 24 "data/maps/LittlerootTown/scripts.pory"
# 48 "data/maps/LittlerootTown/scripts.pory"
	@ 5: Entered 2F to set clock
# 49 "data/maps/LittlerootTown/scripts.pory"
# 25 "data/maps/LittlerootTown/scripts.pory"
# 50 "data/maps/LittlerootTown/scripts.pory"
	@ 6: Set clock
# 51 "data/maps/LittlerootTown/scripts.pory"
# 26 "data/maps/LittlerootTown/scripts.pory"
# 52 "data/maps/LittlerootTown/scripts.pory"
	@ 7: Told to go meet rival
# 53 "data/maps/LittlerootTown/scripts.pory"
# 27 "data/maps/LittlerootTown/scripts.pory"
# 54 "data/maps/LittlerootTown/scripts.pory"

# 55 "data/maps/LittlerootTown/scripts.pory"
# 28 "data/maps/LittlerootTown/scripts.pory"
# 56 "data/maps/LittlerootTown/scripts.pory"
	@ State descriptions for VAR_LITTLEROOT_HOUSES_STATE_MAY
# 57 "data/maps/LittlerootTown/scripts.pory"
# 29 "data/maps/LittlerootTown/scripts.pory"
# 58 "data/maps/LittlerootTown/scripts.pory"
	@                    and VAR_LITTLEROOT_HOUSES_STATE_BRENDAN
# 59 "data/maps/LittlerootTown/scripts.pory"
# 30 "data/maps/LittlerootTown/scripts.pory"
# 60 "data/maps/LittlerootTown/scripts.pory"
	@ 1: On Truck (and is corresponding gender)
# 61 "data/maps/LittlerootTown/scripts.pory"
# 31 "data/maps/LittlerootTown/scripts.pory"
# 62 "data/maps/LittlerootTown/scripts.pory"
	@ 2: Met Rival's Mom (and is corresponding gender)
# 63 "data/maps/LittlerootTown/scripts.pory"
# 32 "data/maps/LittlerootTown/scripts.pory"
# 64 "data/maps/LittlerootTown/scripts.pory"
	@ 3: Entered Hall of Fame
# 65 "data/maps/LittlerootTown/scripts.pory"
# 33 "data/maps/LittlerootTown/scripts.pory"
# 66 "data/maps/LittlerootTown/scripts.pory"
	@ 4: Completed Lati TV / SS Ticket event
# 67 "data/maps/LittlerootTown/scripts.pory"
# 34 "data/maps/LittlerootTown/scripts.pory"
# 68 "data/maps/LittlerootTown/scripts.pory"
	@ 5: Exited house after above event
# 69 "data/maps/LittlerootTown/scripts.pory"
# 35 "data/maps/LittlerootTown/scripts.pory"
# 70 "data/maps/LittlerootTown/scripts.pory"

# 71 "data/maps/LittlerootTown/scripts.pory"
# 36 "data/maps/LittlerootTown/scripts.pory"
# 72 "data/maps/LittlerootTown/scripts.pory"
	@ State descriptions for VAR_LITTLEROOT_RIVAL_STATE
# 73 "data/maps/LittlerootTown/scripts.pory"
# 37 "data/maps/LittlerootTown/scripts.pory"
# 74 "data/maps/LittlerootTown/scripts.pory"
	@ 1: Never occurs
# 75 "data/maps/LittlerootTown/scripts.pory"
# 38 "data/maps/LittlerootTown/scripts.pory"
# 76 "data/maps/LittlerootTown/scripts.pory"
	@ 2: Entered Rival's bedroom
# 77 "data/maps/LittlerootTown/scripts.pory"
# 39 "data/maps/LittlerootTown/scripts.pory"
# 78 "data/maps/LittlerootTown/scripts.pory"
	@ 3: Met Rival
# 79 "data/maps/LittlerootTown/scripts.pory"
# 40 "data/maps/LittlerootTown/scripts.pory"
# 80 "data/maps/LittlerootTown/scripts.pory"
	@ 4: Received Pokedex
# 81 "data/maps/LittlerootTown/scripts.pory"
# 41 "data/maps/LittlerootTown/scripts.pory"
# 82 "data/maps/LittlerootTown/scripts.pory"

# 83 "data/maps/LittlerootTown/scripts.pory"
# 42 "data/maps/LittlerootTown/scripts.pory"
# 84 "data/maps/LittlerootTown/scripts.pory"

# 85 "data/maps/LittlerootTown/scripts.pory"
# 43 "data/maps/LittlerootTown/scripts.pory"
# 86 "data/maps/LittlerootTown/scripts.pory"
LittlerootTown_OnTransition:
# 87 "data/maps/LittlerootTown/scripts.pory"
# 44 "data/maps/LittlerootTown/scripts.pory"
# 88 "data/maps/LittlerootTown/scripts.pory"
	setflag FLAG_VISITED_LITTLEROOT_TOWN
# 89 "data/maps/LittlerootTown/scripts.pory"
# 45 "data/maps/LittlerootTown/scripts.pory"
# 90 "data/maps/LittlerootTown/scripts.pory"
	call Common_EventScript_SetupRivalGfxId
# 91 "data/maps/LittlerootTown/scripts.pory"
# 46 "data/maps/LittlerootTown/scripts.pory"
# 92 "data/maps/LittlerootTown/scripts.pory"
	call_if_eq VAR_LITTLEROOT_INTRO_STATE, 2, LittlerootTown_EventScript_MoveMomToMaysDoor
# 93 "data/maps/LittlerootTown/scripts.pory"
# 47 "data/maps/LittlerootTown/scripts.pory"
# 94 "data/maps/LittlerootTown/scripts.pory"
	call_if_unset FLAG_RESCUED_BIRCH, LittlerootTown_EventScript_SetTwinPos
# 95 "data/maps/LittlerootTown/scripts.pory"
# 48 "data/maps/LittlerootTown/scripts.pory"
# 96 "data/maps/LittlerootTown/scripts.pory"
	call_if_eq VAR_LITTLEROOT_TOWN_STATE, 3, LittlerootTown_EventScript_SetMomStandingInFrontOfDoorPos
# 97 "data/maps/LittlerootTown/scripts.pory"
# 49 "data/maps/LittlerootTown/scripts.pory"
# 98 "data/maps/LittlerootTown/scripts.pory"
	call_if_eq VAR_LITTLEROOT_HOUSES_STATE_MAY, 4, LittlerootTown_EventScript_SetExitedHouseAfterLatiSSTicketEvent
# 99 "data/maps/LittlerootTown/scripts.pory"
# 50 "data/maps/LittlerootTown/scripts.pory"
# 100 "data/maps/LittlerootTown/scripts.pory"
	call_if_eq VAR_LITTLEROOT_HOUSES_STATE_BRENDAN, 4, LittlerootTown_EventScript_SetExitedHouseAfterLatiSSTicketEvent
# 101 "data/maps/LittlerootTown/scripts.pory"
# 51 "data/maps/LittlerootTown/scripts.pory"
# 102 "data/maps/LittlerootTown/scripts.pory"
	call_if_eq VAR_OLDALE_RIVAL_STATE, 1, LittlerootTown_EventScript_MoveRivalFromOldale
# 103 "data/maps/LittlerootTown/scripts.pory"
# 52 "data/maps/LittlerootTown/scripts.pory"
# 104 "data/maps/LittlerootTown/scripts.pory"
	call_if_eq VAR_LITTLEROOT_RIVAL_STATE, 3, LittlerootTown_EventScript_SetRivalLeftForRoute103
# 105 "data/maps/LittlerootTown/scripts.pory"
# 53 "data/maps/LittlerootTown/scripts.pory"
# 106 "data/maps/LittlerootTown/scripts.pory"
	call_if_eq VAR_GIVE_NAVEL_ISLAND_TICKET, 1, LittlerootTown_EventScript_HideMapNamePopup
# 107 "data/maps/LittlerootTown/scripts.pory"
# 54 "data/maps/LittlerootTown/scripts.pory"
# 108 "data/maps/LittlerootTown/scripts.pory"
	call_if_eq VAR_DEX_UPGRADE_JOHTO_STARTER_STATE, 2, LittlerootTown_EventScript_LeftLabAfterDexUpgrade
# 109 "data/maps/LittlerootTown/scripts.pory"
# 55 "data/maps/LittlerootTown/scripts.pory"
# 110 "data/maps/LittlerootTown/scripts.pory"
	end
# 111 "data/maps/LittlerootTown/scripts.pory"
# 56 "data/maps/LittlerootTown/scripts.pory"
# 112 "data/maps/LittlerootTown/scripts.pory"

# 113 "data/maps/LittlerootTown/scripts.pory"
# 57 "data/maps/LittlerootTown/scripts.pory"
# 114 "data/maps/LittlerootTown/scripts.pory"
LittlerootTown_EventScript_LeftLabAfterDexUpgrade::
# 115 "data/maps/LittlerootTown/scripts.pory"
# 58 "data/maps/LittlerootTown/scripts.pory"
# 116 "data/maps/LittlerootTown/scripts.pory"
	setvar VAR_DEX_UPGRADE_JOHTO_STARTER_STATE, 3
# 117 "data/maps/LittlerootTown/scripts.pory"
# 59 "data/maps/LittlerootTown/scripts.pory"
# 118 "data/maps/LittlerootTown/scripts.pory"
	return
# 119 "data/maps/LittlerootTown/scripts.pory"
# 60 "data/maps/LittlerootTown/scripts.pory"
# 120 "data/maps/LittlerootTown/scripts.pory"

# 121 "data/maps/LittlerootTown/scripts.pory"
# 61 "data/maps/LittlerootTown/scripts.pory"
# 122 "data/maps/LittlerootTown/scripts.pory"
LittlerootTown_EventScript_HideMapNamePopup::
# 123 "data/maps/LittlerootTown/scripts.pory"
# 62 "data/maps/LittlerootTown/scripts.pory"
# 124 "data/maps/LittlerootTown/scripts.pory"
	setflag FLAG_HIDE_MAP_NAME_POPUP
# 125 "data/maps/LittlerootTown/scripts.pory"
# 63 "data/maps/LittlerootTown/scripts.pory"
# 126 "data/maps/LittlerootTown/scripts.pory"
	return
# 127 "data/maps/LittlerootTown/scripts.pory"
# 64 "data/maps/LittlerootTown/scripts.pory"
# 128 "data/maps/LittlerootTown/scripts.pory"

# 129 "data/maps/LittlerootTown/scripts.pory"
# 65 "data/maps/LittlerootTown/scripts.pory"
# 130 "data/maps/LittlerootTown/scripts.pory"
LittlerootTown_EventScript_SetRivalLeftForRoute103::
# 131 "data/maps/LittlerootTown/scripts.pory"
# 66 "data/maps/LittlerootTown/scripts.pory"
# 132 "data/maps/LittlerootTown/scripts.pory"
	setflag FLAG_RIVAL_LEFT_FOR_ROUTE103
# 133 "data/maps/LittlerootTown/scripts.pory"
# 67 "data/maps/LittlerootTown/scripts.pory"
# 134 "data/maps/LittlerootTown/scripts.pory"
	return
# 135 "data/maps/LittlerootTown/scripts.pory"
# 68 "data/maps/LittlerootTown/scripts.pory"
# 136 "data/maps/LittlerootTown/scripts.pory"

# 137 "data/maps/LittlerootTown/scripts.pory"
# 69 "data/maps/LittlerootTown/scripts.pory"
# 138 "data/maps/LittlerootTown/scripts.pory"
LittlerootTown_EventScript_MoveRivalFromOldale::
# 139 "data/maps/LittlerootTown/scripts.pory"
# 70 "data/maps/LittlerootTown/scripts.pory"
# 140 "data/maps/LittlerootTown/scripts.pory"
	setvar VAR_OLDALE_RIVAL_STATE, 2
# 141 "data/maps/LittlerootTown/scripts.pory"
# 71 "data/maps/LittlerootTown/scripts.pory"
# 142 "data/maps/LittlerootTown/scripts.pory"
	setflag FLAG_HIDE_OLDALE_TOWN_RIVAL
# 143 "data/maps/LittlerootTown/scripts.pory"
# 72 "data/maps/LittlerootTown/scripts.pory"
# 144 "data/maps/LittlerootTown/scripts.pory"
	return
# 145 "data/maps/LittlerootTown/scripts.pory"
# 73 "data/maps/LittlerootTown/scripts.pory"
# 146 "data/maps/LittlerootTown/scripts.pory"

# 147 "data/maps/LittlerootTown/scripts.pory"
# 74 "data/maps/LittlerootTown/scripts.pory"
# 148 "data/maps/LittlerootTown/scripts.pory"
LittlerootTown_EventScript_SetExitedHouseAfterLatiSSTicketEvent::
# 149 "data/maps/LittlerootTown/scripts.pory"
# 75 "data/maps/LittlerootTown/scripts.pory"
# 150 "data/maps/LittlerootTown/scripts.pory"
	setvar VAR_LITTLEROOT_HOUSES_STATE_MAY, 5
# 151 "data/maps/LittlerootTown/scripts.pory"
# 76 "data/maps/LittlerootTown/scripts.pory"
# 152 "data/maps/LittlerootTown/scripts.pory"
	setvar VAR_LITTLEROOT_HOUSES_STATE_BRENDAN, 5
# 153 "data/maps/LittlerootTown/scripts.pory"
# 77 "data/maps/LittlerootTown/scripts.pory"
# 154 "data/maps/LittlerootTown/scripts.pory"
	return
# 155 "data/maps/LittlerootTown/scripts.pory"
# 78 "data/maps/LittlerootTown/scripts.pory"
# 156 "data/maps/LittlerootTown/scripts.pory"

# 157 "data/maps/LittlerootTown/scripts.pory"
# 79 "data/maps/LittlerootTown/scripts.pory"
# 158 "data/maps/LittlerootTown/scripts.pory"
LittlerootTown_EventScript_MoveMomToMaysDoor::
# 159 "data/maps/LittlerootTown/scripts.pory"
# 80 "data/maps/LittlerootTown/scripts.pory"
# 160 "data/maps/LittlerootTown/scripts.pory"
	setobjectxyperm LOCALID_MOM, 14, 8
# 161 "data/maps/LittlerootTown/scripts.pory"
# 81 "data/maps/LittlerootTown/scripts.pory"
# 162 "data/maps/LittlerootTown/scripts.pory"
	return
# 163 "data/maps/LittlerootTown/scripts.pory"
# 82 "data/maps/LittlerootTown/scripts.pory"
# 164 "data/maps/LittlerootTown/scripts.pory"

# 165 "data/maps/LittlerootTown/scripts.pory"
# 83 "data/maps/LittlerootTown/scripts.pory"
# 166 "data/maps/LittlerootTown/scripts.pory"
LittlerootTown_EventScript_SetTwinPos::
# 167 "data/maps/LittlerootTown/scripts.pory"
# 84 "data/maps/LittlerootTown/scripts.pory"
# 168 "data/maps/LittlerootTown/scripts.pory"
	goto_if_eq VAR_LITTLEROOT_TOWN_STATE, 0, LittlerootTown_EventScript_SetTwinGuardingRoutePos
# 169 "data/maps/LittlerootTown/scripts.pory"
# 85 "data/maps/LittlerootTown/scripts.pory"
# 170 "data/maps/LittlerootTown/scripts.pory"
	setobjectxyperm LOCALID_TWIN, 10, 1
# 171 "data/maps/LittlerootTown/scripts.pory"
# 86 "data/maps/LittlerootTown/scripts.pory"
# 172 "data/maps/LittlerootTown/scripts.pory"
	setobjectmovementtype LOCALID_TWIN, MOVEMENT_TYPE_FACE_UP
# 173 "data/maps/LittlerootTown/scripts.pory"
# 87 "data/maps/LittlerootTown/scripts.pory"
# 174 "data/maps/LittlerootTown/scripts.pory"
	return
# 175 "data/maps/LittlerootTown/scripts.pory"
# 88 "data/maps/LittlerootTown/scripts.pory"
# 176 "data/maps/LittlerootTown/scripts.pory"

# 177 "data/maps/LittlerootTown/scripts.pory"
# 89 "data/maps/LittlerootTown/scripts.pory"
# 178 "data/maps/LittlerootTown/scripts.pory"
LittlerootTown_EventScript_SetTwinGuardingRoutePos::
# 179 "data/maps/LittlerootTown/scripts.pory"
# 90 "data/maps/LittlerootTown/scripts.pory"
# 180 "data/maps/LittlerootTown/scripts.pory"
	setobjectxyperm LOCALID_TWIN, 7, 2
# 181 "data/maps/LittlerootTown/scripts.pory"
# 91 "data/maps/LittlerootTown/scripts.pory"
# 182 "data/maps/LittlerootTown/scripts.pory"
	setobjectmovementtype LOCALID_TWIN, MOVEMENT_TYPE_FACE_DOWN
# 183 "data/maps/LittlerootTown/scripts.pory"
# 92 "data/maps/LittlerootTown/scripts.pory"
# 184 "data/maps/LittlerootTown/scripts.pory"
	return
# 185 "data/maps/LittlerootTown/scripts.pory"
# 93 "data/maps/LittlerootTown/scripts.pory"
# 186 "data/maps/LittlerootTown/scripts.pory"

# 187 "data/maps/LittlerootTown/scripts.pory"
# 94 "data/maps/LittlerootTown/scripts.pory"
# 188 "data/maps/LittlerootTown/scripts.pory"
LittlerootTown_EventScript_SetMomStandingInFrontOfDoorPos::
# 189 "data/maps/LittlerootTown/scripts.pory"
# 95 "data/maps/LittlerootTown/scripts.pory"
# 190 "data/maps/LittlerootTown/scripts.pory"
	clearflag FLAG_HIDE_LITTLEROOT_TOWN_MOM_OUTSIDE
# 191 "data/maps/LittlerootTown/scripts.pory"
# 96 "data/maps/LittlerootTown/scripts.pory"
# 192 "data/maps/LittlerootTown/scripts.pory"
	setobjectmovementtype LOCALID_MOM, MOVEMENT_TYPE_FACE_DOWN
# 193 "data/maps/LittlerootTown/scripts.pory"
# 97 "data/maps/LittlerootTown/scripts.pory"
# 194 "data/maps/LittlerootTown/scripts.pory"
	checkplayergender
# 195 "data/maps/LittlerootTown/scripts.pory"
# 98 "data/maps/LittlerootTown/scripts.pory"
# 196 "data/maps/LittlerootTown/scripts.pory"
	call_if_eq VAR_RESULT, MALE, LittlerootTown_EventScript_SetMomInFrontOfDoorMale
# 197 "data/maps/LittlerootTown/scripts.pory"
# 99 "data/maps/LittlerootTown/scripts.pory"
# 198 "data/maps/LittlerootTown/scripts.pory"
	call_if_eq VAR_RESULT, FEMALE, LittlerootTown_EventScript_SetMomInFrontOfDoorFemale
# 199 "data/maps/LittlerootTown/scripts.pory"
# 100 "data/maps/LittlerootTown/scripts.pory"
# 200 "data/maps/LittlerootTown/scripts.pory"
	return
# 201 "data/maps/LittlerootTown/scripts.pory"
# 101 "data/maps/LittlerootTown/scripts.pory"
# 202 "data/maps/LittlerootTown/scripts.pory"

# 203 "data/maps/LittlerootTown/scripts.pory"
# 102 "data/maps/LittlerootTown/scripts.pory"
# 204 "data/maps/LittlerootTown/scripts.pory"
LittlerootTown_EventScript_SetMomInFrontOfDoorMale::
# 205 "data/maps/LittlerootTown/scripts.pory"
# 103 "data/maps/LittlerootTown/scripts.pory"
# 206 "data/maps/LittlerootTown/scripts.pory"
	setobjectxyperm LOCALID_MOM, 5, 9
# 207 "data/maps/LittlerootTown/scripts.pory"
# 104 "data/maps/LittlerootTown/scripts.pory"
# 208 "data/maps/LittlerootTown/scripts.pory"
	return
# 209 "data/maps/LittlerootTown/scripts.pory"
# 105 "data/maps/LittlerootTown/scripts.pory"
# 210 "data/maps/LittlerootTown/scripts.pory"

# 211 "data/maps/LittlerootTown/scripts.pory"
# 106 "data/maps/LittlerootTown/scripts.pory"
# 212 "data/maps/LittlerootTown/scripts.pory"
LittlerootTown_EventScript_SetMomInFrontOfDoorFemale::
# 213 "data/maps/LittlerootTown/scripts.pory"
# 107 "data/maps/LittlerootTown/scripts.pory"
# 214 "data/maps/LittlerootTown/scripts.pory"
	setobjectxyperm LOCALID_MOM, 14, 9
# 215 "data/maps/LittlerootTown/scripts.pory"
# 108 "data/maps/LittlerootTown/scripts.pory"
# 216 "data/maps/LittlerootTown/scripts.pory"
	return
# 217 "data/maps/LittlerootTown/scripts.pory"
# 109 "data/maps/LittlerootTown/scripts.pory"
# 218 "data/maps/LittlerootTown/scripts.pory"

# 219 "data/maps/LittlerootTown/scripts.pory"
# 110 "data/maps/LittlerootTown/scripts.pory"
# 220 "data/maps/LittlerootTown/scripts.pory"
LittlerootTown_OnFrame:
# 221 "data/maps/LittlerootTown/scripts.pory"
# 111 "data/maps/LittlerootTown/scripts.pory"
# 222 "data/maps/LittlerootTown/scripts.pory"
	map_script_2 VAR_LITTLEROOT_INTRO_STATE, 1, LittlerootTown_EventScript_StepOffTruckMale
# 223 "data/maps/LittlerootTown/scripts.pory"
# 112 "data/maps/LittlerootTown/scripts.pory"
# 224 "data/maps/LittlerootTown/scripts.pory"
	map_script_2 VAR_LITTLEROOT_INTRO_STATE, 2, LittlerootTown_EventScript_StepOffTruckFemale
# 225 "data/maps/LittlerootTown/scripts.pory"
# 113 "data/maps/LittlerootTown/scripts.pory"
# 226 "data/maps/LittlerootTown/scripts.pory"
	map_script_2 VAR_GIVE_NAVEL_ISLAND_TICKET, 1, LittlerootTown_EventScript_BeginDexUpgradeScene
# 227 "data/maps/LittlerootTown/scripts.pory"
# 114 "data/maps/LittlerootTown/scripts.pory"
# 228 "data/maps/LittlerootTown/scripts.pory"
	.2byte 0
# 229 "data/maps/LittlerootTown/scripts.pory"
# 115 "data/maps/LittlerootTown/scripts.pory"
# 230 "data/maps/LittlerootTown/scripts.pory"

# 231 "data/maps/LittlerootTown/scripts.pory"
# 116 "data/maps/LittlerootTown/scripts.pory"
# 232 "data/maps/LittlerootTown/scripts.pory"
LittlerootTown_EventScript_StepOffTruckMale::
# 233 "data/maps/LittlerootTown/scripts.pory"
# 117 "data/maps/LittlerootTown/scripts.pory"
# 234 "data/maps/LittlerootTown/scripts.pory"
	lockall
# 235 "data/maps/LittlerootTown/scripts.pory"
# 118 "data/maps/LittlerootTown/scripts.pory"
# 236 "data/maps/LittlerootTown/scripts.pory"
	setvar VAR_0x8004, 5
# 237 "data/maps/LittlerootTown/scripts.pory"
# 119 "data/maps/LittlerootTown/scripts.pory"
# 238 "data/maps/LittlerootTown/scripts.pory"
	setvar VAR_0x8005, 8
# 239 "data/maps/LittlerootTown/scripts.pory"
# 120 "data/maps/LittlerootTown/scripts.pory"
# 240 "data/maps/LittlerootTown/scripts.pory"
	call LittlerootTown_EventScript_GoInsideWithMom
# 241 "data/maps/LittlerootTown/scripts.pory"
# 121 "data/maps/LittlerootTown/scripts.pory"
# 242 "data/maps/LittlerootTown/scripts.pory"
	setflag FLAG_HIDE_LITTLEROOT_TOWN_BRENDANS_HOUSE_TRUCK
# 243 "data/maps/LittlerootTown/scripts.pory"
# 122 "data/maps/LittlerootTown/scripts.pory"
# 244 "data/maps/LittlerootTown/scripts.pory"
	warpsilent MAP_LITTLEROOT_TOWN_BRENDANS_HOUSE_1F, 8, 8
# 245 "data/maps/LittlerootTown/scripts.pory"
# 123 "data/maps/LittlerootTown/scripts.pory"
# 246 "data/maps/LittlerootTown/scripts.pory"
	waitstate
# 247 "data/maps/LittlerootTown/scripts.pory"
# 124 "data/maps/LittlerootTown/scripts.pory"
# 248 "data/maps/LittlerootTown/scripts.pory"
	releaseall
# 249 "data/maps/LittlerootTown/scripts.pory"
# 125 "data/maps/LittlerootTown/scripts.pory"
# 250 "data/maps/LittlerootTown/scripts.pory"
	end
# 251 "data/maps/LittlerootTown/scripts.pory"
# 126 "data/maps/LittlerootTown/scripts.pory"
# 252 "data/maps/LittlerootTown/scripts.pory"

# 253 "data/maps/LittlerootTown/scripts.pory"
# 127 "data/maps/LittlerootTown/scripts.pory"
# 254 "data/maps/LittlerootTown/scripts.pory"
LittlerootTown_EventScript_StepOffTruckFemale::
# 255 "data/maps/LittlerootTown/scripts.pory"
# 128 "data/maps/LittlerootTown/scripts.pory"
# 256 "data/maps/LittlerootTown/scripts.pory"
	lockall
# 257 "data/maps/LittlerootTown/scripts.pory"
# 129 "data/maps/LittlerootTown/scripts.pory"
# 258 "data/maps/LittlerootTown/scripts.pory"
	setvar VAR_0x8004, 14
# 259 "data/maps/LittlerootTown/scripts.pory"
# 130 "data/maps/LittlerootTown/scripts.pory"
# 260 "data/maps/LittlerootTown/scripts.pory"
	setvar VAR_0x8005, 8
# 261 "data/maps/LittlerootTown/scripts.pory"
# 131 "data/maps/LittlerootTown/scripts.pory"
# 262 "data/maps/LittlerootTown/scripts.pory"
	call LittlerootTown_EventScript_GoInsideWithMom
# 263 "data/maps/LittlerootTown/scripts.pory"
# 132 "data/maps/LittlerootTown/scripts.pory"
# 264 "data/maps/LittlerootTown/scripts.pory"
	setflag FLAG_HIDE_LITTLEROOT_TOWN_MAYS_HOUSE_TRUCK
# 265 "data/maps/LittlerootTown/scripts.pory"
# 133 "data/maps/LittlerootTown/scripts.pory"
# 266 "data/maps/LittlerootTown/scripts.pory"
	warpsilent MAP_LITTLEROOT_TOWN_MAYS_HOUSE_1F, 2, 8
# 267 "data/maps/LittlerootTown/scripts.pory"
# 134 "data/maps/LittlerootTown/scripts.pory"
# 268 "data/maps/LittlerootTown/scripts.pory"
	waitstate
# 269 "data/maps/LittlerootTown/scripts.pory"
# 135 "data/maps/LittlerootTown/scripts.pory"
# 270 "data/maps/LittlerootTown/scripts.pory"
	releaseall
# 271 "data/maps/LittlerootTown/scripts.pory"
# 136 "data/maps/LittlerootTown/scripts.pory"
# 272 "data/maps/LittlerootTown/scripts.pory"
	end
# 273 "data/maps/LittlerootTown/scripts.pory"
# 137 "data/maps/LittlerootTown/scripts.pory"
# 274 "data/maps/LittlerootTown/scripts.pory"

# 275 "data/maps/LittlerootTown/scripts.pory"
# 138 "data/maps/LittlerootTown/scripts.pory"
# 276 "data/maps/LittlerootTown/scripts.pory"
LittlerootTown_EventScript_GoInsideWithMom::
# 277 "data/maps/LittlerootTown/scripts.pory"
# 139 "data/maps/LittlerootTown/scripts.pory"
# 278 "data/maps/LittlerootTown/scripts.pory"
	delay 15
# 279 "data/maps/LittlerootTown/scripts.pory"
# 140 "data/maps/LittlerootTown/scripts.pory"
# 280 "data/maps/LittlerootTown/scripts.pory"
	playse SE_LEDGE
# 281 "data/maps/LittlerootTown/scripts.pory"
# 141 "data/maps/LittlerootTown/scripts.pory"
# 282 "data/maps/LittlerootTown/scripts.pory"
	applymovement OBJ_EVENT_ID_PLAYER, LittlerootTown_Movement_PlayerStepOffTruck
# 283 "data/maps/LittlerootTown/scripts.pory"
# 142 "data/maps/LittlerootTown/scripts.pory"
# 284 "data/maps/LittlerootTown/scripts.pory"
	waitmovement 0
# 285 "data/maps/LittlerootTown/scripts.pory"
# 143 "data/maps/LittlerootTown/scripts.pory"
# 286 "data/maps/LittlerootTown/scripts.pory"
	opendoor VAR_0x8004, VAR_0x8005
# 287 "data/maps/LittlerootTown/scripts.pory"
# 144 "data/maps/LittlerootTown/scripts.pory"
# 288 "data/maps/LittlerootTown/scripts.pory"
	waitdooranim
# 289 "data/maps/LittlerootTown/scripts.pory"
# 145 "data/maps/LittlerootTown/scripts.pory"
# 290 "data/maps/LittlerootTown/scripts.pory"
	addobject LOCALID_MOM
# 291 "data/maps/LittlerootTown/scripts.pory"
# 146 "data/maps/LittlerootTown/scripts.pory"
# 292 "data/maps/LittlerootTown/scripts.pory"
	applymovement LOCALID_MOM, LittlerootTown_Movement_MomExitHouse
# 293 "data/maps/LittlerootTown/scripts.pory"
# 147 "data/maps/LittlerootTown/scripts.pory"
# 294 "data/maps/LittlerootTown/scripts.pory"
	waitmovement 0
# 295 "data/maps/LittlerootTown/scripts.pory"
# 148 "data/maps/LittlerootTown/scripts.pory"
# 296 "data/maps/LittlerootTown/scripts.pory"
	closedoor VAR_0x8004, VAR_0x8005
# 297 "data/maps/LittlerootTown/scripts.pory"
# 149 "data/maps/LittlerootTown/scripts.pory"
# 298 "data/maps/LittlerootTown/scripts.pory"
	waitdooranim
# 299 "data/maps/LittlerootTown/scripts.pory"
# 150 "data/maps/LittlerootTown/scripts.pory"
# 300 "data/maps/LittlerootTown/scripts.pory"
	delay 10
# 301 "data/maps/LittlerootTown/scripts.pory"
# 151 "data/maps/LittlerootTown/scripts.pory"
# 302 "data/maps/LittlerootTown/scripts.pory"
	applymovement LOCALID_MOM, LittlerootTown_Movement_MomApproachPlayerAtTruck
# 303 "data/maps/LittlerootTown/scripts.pory"
# 152 "data/maps/LittlerootTown/scripts.pory"
# 304 "data/maps/LittlerootTown/scripts.pory"
	waitmovement 0
# 305 "data/maps/LittlerootTown/scripts.pory"
# 153 "data/maps/LittlerootTown/scripts.pory"
# 306 "data/maps/LittlerootTown/scripts.pory"
	msgbox LittlerootTown_Text_OurNewHomeLetsGoInside, MSGBOX_DEFAULT
# 307 "data/maps/LittlerootTown/scripts.pory"
# 154 "data/maps/LittlerootTown/scripts.pory"
# 308 "data/maps/LittlerootTown/scripts.pory"
	closemessage
# 309 "data/maps/LittlerootTown/scripts.pory"
# 155 "data/maps/LittlerootTown/scripts.pory"
# 310 "data/maps/LittlerootTown/scripts.pory"
	applymovement LOCALID_MOM, LittlerootTown_Movement_MomApproachDoor
# 311 "data/maps/LittlerootTown/scripts.pory"
# 156 "data/maps/LittlerootTown/scripts.pory"
# 312 "data/maps/LittlerootTown/scripts.pory"
	applymovement OBJ_EVENT_ID_PLAYER, LittlerootTown_Movement_PlayerApproachDoor
# 313 "data/maps/LittlerootTown/scripts.pory"
# 157 "data/maps/LittlerootTown/scripts.pory"
# 314 "data/maps/LittlerootTown/scripts.pory"
	waitmovement 0
# 315 "data/maps/LittlerootTown/scripts.pory"
# 158 "data/maps/LittlerootTown/scripts.pory"
# 316 "data/maps/LittlerootTown/scripts.pory"
	opendoor VAR_0x8004, VAR_0x8005
# 317 "data/maps/LittlerootTown/scripts.pory"
# 159 "data/maps/LittlerootTown/scripts.pory"
# 318 "data/maps/LittlerootTown/scripts.pory"
	waitdooranim
# 319 "data/maps/LittlerootTown/scripts.pory"
# 160 "data/maps/LittlerootTown/scripts.pory"
# 320 "data/maps/LittlerootTown/scripts.pory"
	applymovement LOCALID_MOM, LittlerootTown_Movement_MomEnterHouse
# 321 "data/maps/LittlerootTown/scripts.pory"
# 161 "data/maps/LittlerootTown/scripts.pory"
# 322 "data/maps/LittlerootTown/scripts.pory"
	applymovement OBJ_EVENT_ID_PLAYER, LittlerootTown_Movement_PlayerEnterHouse
# 323 "data/maps/LittlerootTown/scripts.pory"
# 162 "data/maps/LittlerootTown/scripts.pory"
# 324 "data/maps/LittlerootTown/scripts.pory"
	waitmovement 0
# 325 "data/maps/LittlerootTown/scripts.pory"
# 163 "data/maps/LittlerootTown/scripts.pory"
# 326 "data/maps/LittlerootTown/scripts.pory"
	setflag FLAG_HIDE_LITTLEROOT_TOWN_MOM_OUTSIDE
# 327 "data/maps/LittlerootTown/scripts.pory"
# 164 "data/maps/LittlerootTown/scripts.pory"
# 328 "data/maps/LittlerootTown/scripts.pory"
	setvar VAR_LITTLEROOT_INTRO_STATE, 3
# 329 "data/maps/LittlerootTown/scripts.pory"
# 165 "data/maps/LittlerootTown/scripts.pory"
# 330 "data/maps/LittlerootTown/scripts.pory"
	hideobjectat OBJ_EVENT_ID_PLAYER, 0
# 331 "data/maps/LittlerootTown/scripts.pory"
# 166 "data/maps/LittlerootTown/scripts.pory"
# 332 "data/maps/LittlerootTown/scripts.pory"
	closedoor VAR_0x8004, VAR_0x8005
# 333 "data/maps/LittlerootTown/scripts.pory"
# 167 "data/maps/LittlerootTown/scripts.pory"
# 334 "data/maps/LittlerootTown/scripts.pory"
	waitdooranim
# 335 "data/maps/LittlerootTown/scripts.pory"
# 168 "data/maps/LittlerootTown/scripts.pory"
# 336 "data/maps/LittlerootTown/scripts.pory"
	clearflag FLAG_HIDE_LITTLEROOT_TOWN_FAT_MAN
# 337 "data/maps/LittlerootTown/scripts.pory"
# 169 "data/maps/LittlerootTown/scripts.pory"
# 338 "data/maps/LittlerootTown/scripts.pory"
	clearflag FLAG_HIDE_MAP_NAME_POPUP
# 339 "data/maps/LittlerootTown/scripts.pory"
# 170 "data/maps/LittlerootTown/scripts.pory"
# 340 "data/maps/LittlerootTown/scripts.pory"
	return
# 341 "data/maps/LittlerootTown/scripts.pory"
# 171 "data/maps/LittlerootTown/scripts.pory"
# 342 "data/maps/LittlerootTown/scripts.pory"

# 343 "data/maps/LittlerootTown/scripts.pory"
# 172 "data/maps/LittlerootTown/scripts.pory"
# 344 "data/maps/LittlerootTown/scripts.pory"
LittlerootTown_Movement_MomExitHouse:
# 345 "data/maps/LittlerootTown/scripts.pory"
# 173 "data/maps/LittlerootTown/scripts.pory"
# 346 "data/maps/LittlerootTown/scripts.pory"
	walk_down
# 347 "data/maps/LittlerootTown/scripts.pory"
# 174 "data/maps/LittlerootTown/scripts.pory"
# 348 "data/maps/LittlerootTown/scripts.pory"
	step_end
# 349 "data/maps/LittlerootTown/scripts.pory"
# 175 "data/maps/LittlerootTown/scripts.pory"
# 350 "data/maps/LittlerootTown/scripts.pory"

# 351 "data/maps/LittlerootTown/scripts.pory"
# 176 "data/maps/LittlerootTown/scripts.pory"
# 352 "data/maps/LittlerootTown/scripts.pory"
LittlerootTown_Movement_MomApproachPlayerAtTruck:
# 353 "data/maps/LittlerootTown/scripts.pory"
# 177 "data/maps/LittlerootTown/scripts.pory"
# 354 "data/maps/LittlerootTown/scripts.pory"
	walk_down
# 355 "data/maps/LittlerootTown/scripts.pory"
# 178 "data/maps/LittlerootTown/scripts.pory"
# 356 "data/maps/LittlerootTown/scripts.pory"
	walk_in_place_faster_left
# 357 "data/maps/LittlerootTown/scripts.pory"
# 179 "data/maps/LittlerootTown/scripts.pory"
# 358 "data/maps/LittlerootTown/scripts.pory"
	step_end
# 359 "data/maps/LittlerootTown/scripts.pory"
# 180 "data/maps/LittlerootTown/scripts.pory"
# 360 "data/maps/LittlerootTown/scripts.pory"

# 361 "data/maps/LittlerootTown/scripts.pory"
# 181 "data/maps/LittlerootTown/scripts.pory"
# 362 "data/maps/LittlerootTown/scripts.pory"
LittlerootTown_Movement_MomApproachDoor:
# 363 "data/maps/LittlerootTown/scripts.pory"
# 182 "data/maps/LittlerootTown/scripts.pory"
# 364 "data/maps/LittlerootTown/scripts.pory"
	delay_16
# 365 "data/maps/LittlerootTown/scripts.pory"
# 183 "data/maps/LittlerootTown/scripts.pory"
# 366 "data/maps/LittlerootTown/scripts.pory"
	delay_8
# 367 "data/maps/LittlerootTown/scripts.pory"
# 184 "data/maps/LittlerootTown/scripts.pory"
# 368 "data/maps/LittlerootTown/scripts.pory"
	walk_up
# 369 "data/maps/LittlerootTown/scripts.pory"
# 185 "data/maps/LittlerootTown/scripts.pory"
# 370 "data/maps/LittlerootTown/scripts.pory"
	step_end
# 371 "data/maps/LittlerootTown/scripts.pory"
# 186 "data/maps/LittlerootTown/scripts.pory"
# 372 "data/maps/LittlerootTown/scripts.pory"

# 373 "data/maps/LittlerootTown/scripts.pory"
# 187 "data/maps/LittlerootTown/scripts.pory"
# 374 "data/maps/LittlerootTown/scripts.pory"
LittlerootTown_Movement_MomEnterHouse:
# 375 "data/maps/LittlerootTown/scripts.pory"
# 188 "data/maps/LittlerootTown/scripts.pory"
# 376 "data/maps/LittlerootTown/scripts.pory"
	walk_up
# 377 "data/maps/LittlerootTown/scripts.pory"
# 189 "data/maps/LittlerootTown/scripts.pory"
# 378 "data/maps/LittlerootTown/scripts.pory"
	set_invisible
# 379 "data/maps/LittlerootTown/scripts.pory"
# 190 "data/maps/LittlerootTown/scripts.pory"
# 380 "data/maps/LittlerootTown/scripts.pory"
	step_end
# 381 "data/maps/LittlerootTown/scripts.pory"
# 191 "data/maps/LittlerootTown/scripts.pory"
# 382 "data/maps/LittlerootTown/scripts.pory"

# 383 "data/maps/LittlerootTown/scripts.pory"
# 192 "data/maps/LittlerootTown/scripts.pory"
# 384 "data/maps/LittlerootTown/scripts.pory"
LittlerootTown_Movement_PlayerApproachDoor:
# 385 "data/maps/LittlerootTown/scripts.pory"
# 193 "data/maps/LittlerootTown/scripts.pory"
# 386 "data/maps/LittlerootTown/scripts.pory"
	delay_16
# 387 "data/maps/LittlerootTown/scripts.pory"
# 194 "data/maps/LittlerootTown/scripts.pory"
# 388 "data/maps/LittlerootTown/scripts.pory"
	delay_8
# 389 "data/maps/LittlerootTown/scripts.pory"
# 195 "data/maps/LittlerootTown/scripts.pory"
# 390 "data/maps/LittlerootTown/scripts.pory"
	walk_right
# 391 "data/maps/LittlerootTown/scripts.pory"
# 196 "data/maps/LittlerootTown/scripts.pory"
# 392 "data/maps/LittlerootTown/scripts.pory"
	walk_in_place_faster_up
# 393 "data/maps/LittlerootTown/scripts.pory"
# 197 "data/maps/LittlerootTown/scripts.pory"
# 394 "data/maps/LittlerootTown/scripts.pory"
	step_end
# 395 "data/maps/LittlerootTown/scripts.pory"
# 198 "data/maps/LittlerootTown/scripts.pory"
# 396 "data/maps/LittlerootTown/scripts.pory"

# 397 "data/maps/LittlerootTown/scripts.pory"
# 199 "data/maps/LittlerootTown/scripts.pory"
# 398 "data/maps/LittlerootTown/scripts.pory"
LittlerootTown_Movement_PlayerEnterHouse:
# 399 "data/maps/LittlerootTown/scripts.pory"
# 200 "data/maps/LittlerootTown/scripts.pory"
# 400 "data/maps/LittlerootTown/scripts.pory"
	walk_up
# 401 "data/maps/LittlerootTown/scripts.pory"
# 201 "data/maps/LittlerootTown/scripts.pory"
# 402 "data/maps/LittlerootTown/scripts.pory"
	walk_up
# 403 "data/maps/LittlerootTown/scripts.pory"
# 202 "data/maps/LittlerootTown/scripts.pory"
# 404 "data/maps/LittlerootTown/scripts.pory"
	step_end
# 405 "data/maps/LittlerootTown/scripts.pory"
# 203 "data/maps/LittlerootTown/scripts.pory"
# 406 "data/maps/LittlerootTown/scripts.pory"

# 407 "data/maps/LittlerootTown/scripts.pory"
# 204 "data/maps/LittlerootTown/scripts.pory"
# 408 "data/maps/LittlerootTown/scripts.pory"
LittlerootTown_Movement_PlayerStepOffTruck:
# 409 "data/maps/LittlerootTown/scripts.pory"
# 205 "data/maps/LittlerootTown/scripts.pory"
# 410 "data/maps/LittlerootTown/scripts.pory"
	jump_right
# 411 "data/maps/LittlerootTown/scripts.pory"
# 206 "data/maps/LittlerootTown/scripts.pory"
# 412 "data/maps/LittlerootTown/scripts.pory"
	delay_16
# 413 "data/maps/LittlerootTown/scripts.pory"
# 207 "data/maps/LittlerootTown/scripts.pory"
# 414 "data/maps/LittlerootTown/scripts.pory"
	delay_16
# 415 "data/maps/LittlerootTown/scripts.pory"
# 208 "data/maps/LittlerootTown/scripts.pory"
# 416 "data/maps/LittlerootTown/scripts.pory"
	delay_16
# 417 "data/maps/LittlerootTown/scripts.pory"
# 209 "data/maps/LittlerootTown/scripts.pory"
# 418 "data/maps/LittlerootTown/scripts.pory"
	step_end
# 419 "data/maps/LittlerootTown/scripts.pory"
# 210 "data/maps/LittlerootTown/scripts.pory"
# 420 "data/maps/LittlerootTown/scripts.pory"

# 421 "data/maps/LittlerootTown/scripts.pory"
# 211 "data/maps/LittlerootTown/scripts.pory"
# 422 "data/maps/LittlerootTown/scripts.pory"
LittlerootTown_EventScript_BeginDexUpgradeScene::
# 423 "data/maps/LittlerootTown/scripts.pory"
# 212 "data/maps/LittlerootTown/scripts.pory"
# 424 "data/maps/LittlerootTown/scripts.pory"
	lockall
# 425 "data/maps/LittlerootTown/scripts.pory"
# 213 "data/maps/LittlerootTown/scripts.pory"
# 426 "data/maps/LittlerootTown/scripts.pory"
	playse SE_PIN
# 427 "data/maps/LittlerootTown/scripts.pory"
# 214 "data/maps/LittlerootTown/scripts.pory"
# 428 "data/maps/LittlerootTown/scripts.pory"
	applymovement LOCALID_BIRCH, Common_Movement_ExclamationMark
# 429 "data/maps/LittlerootTown/scripts.pory"
# 215 "data/maps/LittlerootTown/scripts.pory"
# 430 "data/maps/LittlerootTown/scripts.pory"
	waitmovement 0
# 431 "data/maps/LittlerootTown/scripts.pory"
# 216 "data/maps/LittlerootTown/scripts.pory"
# 432 "data/maps/LittlerootTown/scripts.pory"
	delay 80
# 433 "data/maps/LittlerootTown/scripts.pory"
# 217 "data/maps/LittlerootTown/scripts.pory"
# 434 "data/maps/LittlerootTown/scripts.pory"
	msgbox LittlerootTown_Text_BirchSomethingToShowYouAtLab, MSGBOX_DEFAULT
# 435 "data/maps/LittlerootTown/scripts.pory"
# 218 "data/maps/LittlerootTown/scripts.pory"
# 436 "data/maps/LittlerootTown/scripts.pory"
	closemessage
# 437 "data/maps/LittlerootTown/scripts.pory"
# 219 "data/maps/LittlerootTown/scripts.pory"
# 438 "data/maps/LittlerootTown/scripts.pory"
# 220 "data/maps/LittlerootTown/scripts.pory"
# 439 "data/maps/LittlerootTown/scripts.pory"
	clearflag FLAG_HIDE_LITTLEROOT_TOWN_BIRCH
# 440 "data/maps/LittlerootTown/scripts.pory"
	clearflag FLAG_HIDE_LITTLEROOT_TOWN_BIRCHS_LAB_BIRCH
# 441 "data/maps/LittlerootTown/scripts.pory"
# 221 "data/maps/LittlerootTown/scripts.pory"
# 442 "data/maps/LittlerootTown/scripts.pory"
	delay 20
# 443 "data/maps/LittlerootTown/scripts.pory"
# 222 "data/maps/LittlerootTown/scripts.pory"
# 444 "data/maps/LittlerootTown/scripts.pory"
	clearflag FLAG_HIDE_MAP_NAME_POPUP
# 445 "data/maps/LittlerootTown/scripts.pory"
# 223 "data/maps/LittlerootTown/scripts.pory"
# 446 "data/maps/LittlerootTown/scripts.pory"
	warp MAP_NEW_BIRCHS_LAB, 6, 6
# 447 "data/maps/LittlerootTown/scripts.pory"
# 224 "data/maps/LittlerootTown/scripts.pory"
# 448 "data/maps/LittlerootTown/scripts.pory"
	waitstate
# 449 "data/maps/LittlerootTown/scripts.pory"
# 225 "data/maps/LittlerootTown/scripts.pory"
# 450 "data/maps/LittlerootTown/scripts.pory"
	releaseall
# 451 "data/maps/LittlerootTown/scripts.pory"
# 226 "data/maps/LittlerootTown/scripts.pory"
# 452 "data/maps/LittlerootTown/scripts.pory"
	end
# 453 "data/maps/LittlerootTown/scripts.pory"
# 227 "data/maps/LittlerootTown/scripts.pory"
# 454 "data/maps/LittlerootTown/scripts.pory"

# 455 "data/maps/LittlerootTown/scripts.pory"
# 228 "data/maps/LittlerootTown/scripts.pory"
# 456 "data/maps/LittlerootTown/scripts.pory"
LittlerootTown_OnWarp:
# 457 "data/maps/LittlerootTown/scripts.pory"
# 229 "data/maps/LittlerootTown/scripts.pory"
# 458 "data/maps/LittlerootTown/scripts.pory"
	map_script_2 VAR_GIVE_NAVEL_ISLAND_TICKET, 1, LittlerootTown_EventScript_SetRivalBirchPosForDexUpgrade
# 459 "data/maps/LittlerootTown/scripts.pory"
# 230 "data/maps/LittlerootTown/scripts.pory"
# 460 "data/maps/LittlerootTown/scripts.pory"
	.2byte 0
# 461 "data/maps/LittlerootTown/scripts.pory"
# 231 "data/maps/LittlerootTown/scripts.pory"
# 462 "data/maps/LittlerootTown/scripts.pory"

# 463 "data/maps/LittlerootTown/scripts.pory"
# 232 "data/maps/LittlerootTown/scripts.pory"
# 464 "data/maps/LittlerootTown/scripts.pory"
LittlerootTown_EventScript_SetRivalBirchPosForDexUpgrade::
# 465 "data/maps/LittlerootTown/scripts.pory"
# 233 "data/maps/LittlerootTown/scripts.pory"
# 466 "data/maps/LittlerootTown/scripts.pory"
	addobject LOCALID_BIRCH
# 467 "data/maps/LittlerootTown/scripts.pory"
# 234 "data/maps/LittlerootTown/scripts.pory"
# 468 "data/maps/LittlerootTown/scripts.pory"
# 235 "data/maps/LittlerootTown/scripts.pory"
# 469 "data/maps/LittlerootTown/scripts.pory"
	checkplayergender
# 470 "data/maps/LittlerootTown/scripts.pory"
# 236 "data/maps/LittlerootTown/scripts.pory"
# 471 "data/maps/LittlerootTown/scripts.pory"
	goto_if_eq VAR_RESULT, MALE, LittlerootTown_EventScript_SetRivalBirchPosForDexUpgradeMale
# 472 "data/maps/LittlerootTown/scripts.pory"
# 237 "data/maps/LittlerootTown/scripts.pory"
# 473 "data/maps/LittlerootTown/scripts.pory"
	goto LittlerootTown_EventScript_SetRivalBirchPosForDexUpgradeFemale
# 474 "data/maps/LittlerootTown/scripts.pory"
# 238 "data/maps/LittlerootTown/scripts.pory"
# 475 "data/maps/LittlerootTown/scripts.pory"
	end
# 476 "data/maps/LittlerootTown/scripts.pory"
# 239 "data/maps/LittlerootTown/scripts.pory"
# 477 "data/maps/LittlerootTown/scripts.pory"

# 478 "data/maps/LittlerootTown/scripts.pory"
# 240 "data/maps/LittlerootTown/scripts.pory"
# 479 "data/maps/LittlerootTown/scripts.pory"
LittlerootTown_EventScript_SetRivalBirchPosForDexUpgradeMale::
# 480 "data/maps/LittlerootTown/scripts.pory"
# 241 "data/maps/LittlerootTown/scripts.pory"
# 481 "data/maps/LittlerootTown/scripts.pory"
# 242 "data/maps/LittlerootTown/scripts.pory"
# 482 "data/maps/LittlerootTown/scripts.pory"
	setobjectxy LOCALID_BIRCH, 5, 10
# 483 "data/maps/LittlerootTown/scripts.pory"
# 243 "data/maps/LittlerootTown/scripts.pory"
# 484 "data/maps/LittlerootTown/scripts.pory"
	end
# 485 "data/maps/LittlerootTown/scripts.pory"
# 244 "data/maps/LittlerootTown/scripts.pory"
# 486 "data/maps/LittlerootTown/scripts.pory"

# 487 "data/maps/LittlerootTown/scripts.pory"
# 245 "data/maps/LittlerootTown/scripts.pory"
# 488 "data/maps/LittlerootTown/scripts.pory"
LittlerootTown_EventScript_SetRivalBirchPosForDexUpgradeFemale::
# 489 "data/maps/LittlerootTown/scripts.pory"
# 246 "data/maps/LittlerootTown/scripts.pory"
# 490 "data/maps/LittlerootTown/scripts.pory"
# 247 "data/maps/LittlerootTown/scripts.pory"
# 491 "data/maps/LittlerootTown/scripts.pory"
	setobjectxy LOCALID_BIRCH, 14, 10
# 492 "data/maps/LittlerootTown/scripts.pory"
# 248 "data/maps/LittlerootTown/scripts.pory"
# 493 "data/maps/LittlerootTown/scripts.pory"
	end
# 494 "data/maps/LittlerootTown/scripts.pory"
# 249 "data/maps/LittlerootTown/scripts.pory"
# 495 "data/maps/LittlerootTown/scripts.pory"

# 496 "data/maps/LittlerootTown/scripts.pory"
# 250 "data/maps/LittlerootTown/scripts.pory"
# 497 "data/maps/LittlerootTown/scripts.pory"
LittlerootTown_EventScript_FatMan::
# 498 "data/maps/LittlerootTown/scripts.pory"
# 251 "data/maps/LittlerootTown/scripts.pory"
# 499 "data/maps/LittlerootTown/scripts.pory"
	msgbox LittlerootTown_Text_CanUsePCToStoreItems, MSGBOX_NPC
# 500 "data/maps/LittlerootTown/scripts.pory"
# 252 "data/maps/LittlerootTown/scripts.pory"
# 501 "data/maps/LittlerootTown/scripts.pory"
	end
# 502 "data/maps/LittlerootTown/scripts.pory"
# 253 "data/maps/LittlerootTown/scripts.pory"
# 503 "data/maps/LittlerootTown/scripts.pory"

# 504 "data/maps/LittlerootTown/scripts.pory"
# 254 "data/maps/LittlerootTown/scripts.pory"
# 505 "data/maps/LittlerootTown/scripts.pory"
LittlerootTown_EventScript_Boy::
# 506 "data/maps/LittlerootTown/scripts.pory"
# 255 "data/maps/LittlerootTown/scripts.pory"
# 507 "data/maps/LittlerootTown/scripts.pory"
	msgbox LittlerootTown_Text_BirchSpendsDaysInLab, MSGBOX_NPC
# 508 "data/maps/LittlerootTown/scripts.pory"
# 256 "data/maps/LittlerootTown/scripts.pory"
# 509 "data/maps/LittlerootTown/scripts.pory"
	end
# 510 "data/maps/LittlerootTown/scripts.pory"
# 257 "data/maps/LittlerootTown/scripts.pory"
# 511 "data/maps/LittlerootTown/scripts.pory"

# 512 "data/maps/LittlerootTown/scripts.pory"
# 258 "data/maps/LittlerootTown/scripts.pory"
# 513 "data/maps/LittlerootTown/scripts.pory"
LittlerootTown_EventScript_Twin::
# 514 "data/maps/LittlerootTown/scripts.pory"
# 259 "data/maps/LittlerootTown/scripts.pory"
# 515 "data/maps/LittlerootTown/scripts.pory"
	lock
# 516 "data/maps/LittlerootTown/scripts.pory"
# 260 "data/maps/LittlerootTown/scripts.pory"
# 517 "data/maps/LittlerootTown/scripts.pory"
	faceplayer
# 518 "data/maps/LittlerootTown/scripts.pory"
# 261 "data/maps/LittlerootTown/scripts.pory"
# 519 "data/maps/LittlerootTown/scripts.pory"
	goto_if_set FLAG_ADVENTURE_STARTED, LittlerootTown_EventScript_GoodLuck
# 520 "data/maps/LittlerootTown/scripts.pory"
# 262 "data/maps/LittlerootTown/scripts.pory"
# 521 "data/maps/LittlerootTown/scripts.pory"
	goto_if_set FLAG_RESCUED_BIRCH, LittlerootTown_EventScript_YouSavedBirch
# 522 "data/maps/LittlerootTown/scripts.pory"
# 263 "data/maps/LittlerootTown/scripts.pory"
# 523 "data/maps/LittlerootTown/scripts.pory"
	goto_if_ne VAR_LITTLEROOT_TOWN_STATE, 0, LittlerootTown_EventScript_GoSaveBirch
# 524 "data/maps/LittlerootTown/scripts.pory"
# 264 "data/maps/LittlerootTown/scripts.pory"
# 525 "data/maps/LittlerootTown/scripts.pory"
	msgbox LittlerootTown_Text_IfYouGoInGrassPokemonWillJumpOut, MSGBOX_DEFAULT
# 526 "data/maps/LittlerootTown/scripts.pory"
# 265 "data/maps/LittlerootTown/scripts.pory"
# 527 "data/maps/LittlerootTown/scripts.pory"
	release
# 528 "data/maps/LittlerootTown/scripts.pory"
# 266 "data/maps/LittlerootTown/scripts.pory"
# 529 "data/maps/LittlerootTown/scripts.pory"
	end
# 530 "data/maps/LittlerootTown/scripts.pory"
# 267 "data/maps/LittlerootTown/scripts.pory"
# 531 "data/maps/LittlerootTown/scripts.pory"

# 532 "data/maps/LittlerootTown/scripts.pory"
# 268 "data/maps/LittlerootTown/scripts.pory"
# 533 "data/maps/LittlerootTown/scripts.pory"
LittlerootTown_EventScript_GoSaveBirch::
# 534 "data/maps/LittlerootTown/scripts.pory"
# 269 "data/maps/LittlerootTown/scripts.pory"
# 535 "data/maps/LittlerootTown/scripts.pory"
	special GetPlayerBigGuyGirlString
# 536 "data/maps/LittlerootTown/scripts.pory"
# 270 "data/maps/LittlerootTown/scripts.pory"
# 537 "data/maps/LittlerootTown/scripts.pory"
	msgbox LittlerootTown_Text_CanYouGoSeeWhatsHappening, MSGBOX_DEFAULT
# 538 "data/maps/LittlerootTown/scripts.pory"
# 271 "data/maps/LittlerootTown/scripts.pory"
# 539 "data/maps/LittlerootTown/scripts.pory"
	closemessage
# 540 "data/maps/LittlerootTown/scripts.pory"
# 272 "data/maps/LittlerootTown/scripts.pory"
# 541 "data/maps/LittlerootTown/scripts.pory"
	applymovement LOCALID_TWIN, Common_Movement_FaceOriginalDirection
# 542 "data/maps/LittlerootTown/scripts.pory"
# 273 "data/maps/LittlerootTown/scripts.pory"
# 543 "data/maps/LittlerootTown/scripts.pory"
	waitmovement 0
# 544 "data/maps/LittlerootTown/scripts.pory"
# 274 "data/maps/LittlerootTown/scripts.pory"
# 545 "data/maps/LittlerootTown/scripts.pory"
	setvar VAR_LITTLEROOT_TOWN_STATE, 2
# 546 "data/maps/LittlerootTown/scripts.pory"
# 275 "data/maps/LittlerootTown/scripts.pory"
# 547 "data/maps/LittlerootTown/scripts.pory"
	release
# 548 "data/maps/LittlerootTown/scripts.pory"
# 276 "data/maps/LittlerootTown/scripts.pory"
# 549 "data/maps/LittlerootTown/scripts.pory"
	end
# 550 "data/maps/LittlerootTown/scripts.pory"
# 277 "data/maps/LittlerootTown/scripts.pory"
# 551 "data/maps/LittlerootTown/scripts.pory"

# 552 "data/maps/LittlerootTown/scripts.pory"
# 278 "data/maps/LittlerootTown/scripts.pory"
# 553 "data/maps/LittlerootTown/scripts.pory"
LittlerootTown_EventScript_YouSavedBirch::
# 554 "data/maps/LittlerootTown/scripts.pory"
# 279 "data/maps/LittlerootTown/scripts.pory"
# 555 "data/maps/LittlerootTown/scripts.pory"
	special GetPlayerBigGuyGirlString
# 556 "data/maps/LittlerootTown/scripts.pory"
# 280 "data/maps/LittlerootTown/scripts.pory"
# 557 "data/maps/LittlerootTown/scripts.pory"
	msgbox LittlerootTown_Text_YouSavedBirch, MSGBOX_DEFAULT
# 558 "data/maps/LittlerootTown/scripts.pory"
# 281 "data/maps/LittlerootTown/scripts.pory"
# 559 "data/maps/LittlerootTown/scripts.pory"
	release
# 560 "data/maps/LittlerootTown/scripts.pory"
# 282 "data/maps/LittlerootTown/scripts.pory"
# 561 "data/maps/LittlerootTown/scripts.pory"
	end
# 562 "data/maps/LittlerootTown/scripts.pory"
# 283 "data/maps/LittlerootTown/scripts.pory"
# 563 "data/maps/LittlerootTown/scripts.pory"

# 564 "data/maps/LittlerootTown/scripts.pory"
# 284 "data/maps/LittlerootTown/scripts.pory"
# 565 "data/maps/LittlerootTown/scripts.pory"
LittlerootTown_EventScript_GoodLuck::
# 566 "data/maps/LittlerootTown/scripts.pory"
# 285 "data/maps/LittlerootTown/scripts.pory"
# 567 "data/maps/LittlerootTown/scripts.pory"
	msgbox LittlerootTown_Text_GoodLuckCatchingPokemon, MSGBOX_DEFAULT
# 568 "data/maps/LittlerootTown/scripts.pory"
# 286 "data/maps/LittlerootTown/scripts.pory"
# 569 "data/maps/LittlerootTown/scripts.pory"
	release
# 570 "data/maps/LittlerootTown/scripts.pory"
# 287 "data/maps/LittlerootTown/scripts.pory"
# 571 "data/maps/LittlerootTown/scripts.pory"
	end
# 572 "data/maps/LittlerootTown/scripts.pory"
# 288 "data/maps/LittlerootTown/scripts.pory"
# 573 "data/maps/LittlerootTown/scripts.pory"

# 574 "data/maps/LittlerootTown/scripts.pory"
# 289 "data/maps/LittlerootTown/scripts.pory"
# 575 "data/maps/LittlerootTown/scripts.pory"
LittlerootTown_EventScript_NeedPokemonTriggerLeft::
# 576 "data/maps/LittlerootTown/scripts.pory"
# 290 "data/maps/LittlerootTown/scripts.pory"
# 577 "data/maps/LittlerootTown/scripts.pory"
	lockall
# 578 "data/maps/LittlerootTown/scripts.pory"
# 291 "data/maps/LittlerootTown/scripts.pory"
# 579 "data/maps/LittlerootTown/scripts.pory"
	applymovement LOCALID_TWIN, LittlerootTown_Movement_TwinApproachPlayerLeft
# 580 "data/maps/LittlerootTown/scripts.pory"
# 292 "data/maps/LittlerootTown/scripts.pory"
# 581 "data/maps/LittlerootTown/scripts.pory"
	waitmovement 0
# 582 "data/maps/LittlerootTown/scripts.pory"
# 293 "data/maps/LittlerootTown/scripts.pory"
# 583 "data/maps/LittlerootTown/scripts.pory"
	call LittlerootTown_EventScript_DangerousWithoutPokemon
# 584 "data/maps/LittlerootTown/scripts.pory"
# 294 "data/maps/LittlerootTown/scripts.pory"
# 585 "data/maps/LittlerootTown/scripts.pory"
	applymovement LOCALID_TWIN, LittlerootTown_Movement_TwinReturnLeft
# 586 "data/maps/LittlerootTown/scripts.pory"
# 295 "data/maps/LittlerootTown/scripts.pory"
# 587 "data/maps/LittlerootTown/scripts.pory"
	waitmovement 0
# 588 "data/maps/LittlerootTown/scripts.pory"
# 296 "data/maps/LittlerootTown/scripts.pory"
# 589 "data/maps/LittlerootTown/scripts.pory"
	releaseall
# 590 "data/maps/LittlerootTown/scripts.pory"
# 297 "data/maps/LittlerootTown/scripts.pory"
# 591 "data/maps/LittlerootTown/scripts.pory"
	end
# 592 "data/maps/LittlerootTown/scripts.pory"
# 298 "data/maps/LittlerootTown/scripts.pory"
# 593 "data/maps/LittlerootTown/scripts.pory"

# 594 "data/maps/LittlerootTown/scripts.pory"
# 299 "data/maps/LittlerootTown/scripts.pory"
# 595 "data/maps/LittlerootTown/scripts.pory"
LittlerootTown_EventScript_DangerousWithoutPokemon::
# 596 "data/maps/LittlerootTown/scripts.pory"
# 300 "data/maps/LittlerootTown/scripts.pory"
# 597 "data/maps/LittlerootTown/scripts.pory"
	msgbox LittlerootTown_Text_IfYouGoInGrassPokemonWillJumpOut, MSGBOX_DEFAULT
# 598 "data/maps/LittlerootTown/scripts.pory"
# 301 "data/maps/LittlerootTown/scripts.pory"
# 599 "data/maps/LittlerootTown/scripts.pory"
	closemessage
# 600 "data/maps/LittlerootTown/scripts.pory"
# 302 "data/maps/LittlerootTown/scripts.pory"
# 601 "data/maps/LittlerootTown/scripts.pory"
	applymovement LOCALID_TWIN, LittlerootTown_Movement_TwinPushPlayerFromRoute
# 602 "data/maps/LittlerootTown/scripts.pory"
# 303 "data/maps/LittlerootTown/scripts.pory"
# 603 "data/maps/LittlerootTown/scripts.pory"
	applymovement OBJ_EVENT_ID_PLAYER, LittlerootTown_Movement_PushPlayerBackFromRoute
# 604 "data/maps/LittlerootTown/scripts.pory"
# 304 "data/maps/LittlerootTown/scripts.pory"
# 605 "data/maps/LittlerootTown/scripts.pory"
	waitmovement 0
# 606 "data/maps/LittlerootTown/scripts.pory"
# 305 "data/maps/LittlerootTown/scripts.pory"
# 607 "data/maps/LittlerootTown/scripts.pory"
	msgbox LittlerootTown_Text_DangerousIfYouDontHavePokemon, MSGBOX_DEFAULT
# 608 "data/maps/LittlerootTown/scripts.pory"
# 306 "data/maps/LittlerootTown/scripts.pory"
# 609 "data/maps/LittlerootTown/scripts.pory"
	closemessage
# 610 "data/maps/LittlerootTown/scripts.pory"
# 307 "data/maps/LittlerootTown/scripts.pory"
# 611 "data/maps/LittlerootTown/scripts.pory"
	return
# 612 "data/maps/LittlerootTown/scripts.pory"
# 308 "data/maps/LittlerootTown/scripts.pory"
# 613 "data/maps/LittlerootTown/scripts.pory"

# 614 "data/maps/LittlerootTown/scripts.pory"
# 309 "data/maps/LittlerootTown/scripts.pory"
# 615 "data/maps/LittlerootTown/scripts.pory"
LittlerootTown_Movement_TwinApproachPlayerLeft:
# 616 "data/maps/LittlerootTown/scripts.pory"
# 310 "data/maps/LittlerootTown/scripts.pory"
# 617 "data/maps/LittlerootTown/scripts.pory"
	face_right
# 618 "data/maps/LittlerootTown/scripts.pory"
# 311 "data/maps/LittlerootTown/scripts.pory"
# 619 "data/maps/LittlerootTown/scripts.pory"
	delay_8
# 620 "data/maps/LittlerootTown/scripts.pory"
# 312 "data/maps/LittlerootTown/scripts.pory"
# 621 "data/maps/LittlerootTown/scripts.pory"
	disable_jump_landing_ground_effect
# 622 "data/maps/LittlerootTown/scripts.pory"
# 313 "data/maps/LittlerootTown/scripts.pory"
# 623 "data/maps/LittlerootTown/scripts.pory"
	jump_in_place_right
# 624 "data/maps/LittlerootTown/scripts.pory"
# 314 "data/maps/LittlerootTown/scripts.pory"
# 625 "data/maps/LittlerootTown/scripts.pory"
	delay_8
# 626 "data/maps/LittlerootTown/scripts.pory"
# 315 "data/maps/LittlerootTown/scripts.pory"
# 627 "data/maps/LittlerootTown/scripts.pory"
	walk_fast_right
# 628 "data/maps/LittlerootTown/scripts.pory"
# 316 "data/maps/LittlerootTown/scripts.pory"
# 629 "data/maps/LittlerootTown/scripts.pory"
	walk_fast_right
# 630 "data/maps/LittlerootTown/scripts.pory"
# 317 "data/maps/LittlerootTown/scripts.pory"
# 631 "data/maps/LittlerootTown/scripts.pory"
	walk_fast_right
# 632 "data/maps/LittlerootTown/scripts.pory"
# 318 "data/maps/LittlerootTown/scripts.pory"
# 633 "data/maps/LittlerootTown/scripts.pory"
	walk_fast_right
# 634 "data/maps/LittlerootTown/scripts.pory"
# 319 "data/maps/LittlerootTown/scripts.pory"
# 635 "data/maps/LittlerootTown/scripts.pory"
	walk_fast_up
# 636 "data/maps/LittlerootTown/scripts.pory"
# 320 "data/maps/LittlerootTown/scripts.pory"
# 637 "data/maps/LittlerootTown/scripts.pory"
	walk_fast_up
# 638 "data/maps/LittlerootTown/scripts.pory"
# 321 "data/maps/LittlerootTown/scripts.pory"
# 639 "data/maps/LittlerootTown/scripts.pory"
	walk_fast_left
# 640 "data/maps/LittlerootTown/scripts.pory"
# 322 "data/maps/LittlerootTown/scripts.pory"
# 641 "data/maps/LittlerootTown/scripts.pory"
	face_down
# 642 "data/maps/LittlerootTown/scripts.pory"
# 323 "data/maps/LittlerootTown/scripts.pory"
# 643 "data/maps/LittlerootTown/scripts.pory"
	step_end
# 644 "data/maps/LittlerootTown/scripts.pory"
# 324 "data/maps/LittlerootTown/scripts.pory"
# 645 "data/maps/LittlerootTown/scripts.pory"

# 646 "data/maps/LittlerootTown/scripts.pory"
# 325 "data/maps/LittlerootTown/scripts.pory"
# 647 "data/maps/LittlerootTown/scripts.pory"
LittlerootTown_Movement_TwinPushPlayerFromRoute:
# 648 "data/maps/LittlerootTown/scripts.pory"
# 326 "data/maps/LittlerootTown/scripts.pory"
# 649 "data/maps/LittlerootTown/scripts.pory"
	walk_down
# 650 "data/maps/LittlerootTown/scripts.pory"
# 327 "data/maps/LittlerootTown/scripts.pory"
# 651 "data/maps/LittlerootTown/scripts.pory"
	step_end
# 652 "data/maps/LittlerootTown/scripts.pory"
# 328 "data/maps/LittlerootTown/scripts.pory"
# 653 "data/maps/LittlerootTown/scripts.pory"

# 654 "data/maps/LittlerootTown/scripts.pory"
# 329 "data/maps/LittlerootTown/scripts.pory"
# 655 "data/maps/LittlerootTown/scripts.pory"
LittlerootTown_Movement_TwinReturnLeft:
# 656 "data/maps/LittlerootTown/scripts.pory"
# 330 "data/maps/LittlerootTown/scripts.pory"
# 657 "data/maps/LittlerootTown/scripts.pory"
	walk_right
# 658 "data/maps/LittlerootTown/scripts.pory"
# 331 "data/maps/LittlerootTown/scripts.pory"
# 659 "data/maps/LittlerootTown/scripts.pory"
	walk_down
# 660 "data/maps/LittlerootTown/scripts.pory"
# 332 "data/maps/LittlerootTown/scripts.pory"
# 661 "data/maps/LittlerootTown/scripts.pory"
	walk_down
# 662 "data/maps/LittlerootTown/scripts.pory"
# 333 "data/maps/LittlerootTown/scripts.pory"
# 663 "data/maps/LittlerootTown/scripts.pory"
	walk_left
# 664 "data/maps/LittlerootTown/scripts.pory"
# 334 "data/maps/LittlerootTown/scripts.pory"
# 665 "data/maps/LittlerootTown/scripts.pory"
	walk_left
# 666 "data/maps/LittlerootTown/scripts.pory"
# 335 "data/maps/LittlerootTown/scripts.pory"
# 667 "data/maps/LittlerootTown/scripts.pory"
	walk_left
# 668 "data/maps/LittlerootTown/scripts.pory"
# 336 "data/maps/LittlerootTown/scripts.pory"
# 669 "data/maps/LittlerootTown/scripts.pory"
	walk_left
# 670 "data/maps/LittlerootTown/scripts.pory"
# 337 "data/maps/LittlerootTown/scripts.pory"
# 671 "data/maps/LittlerootTown/scripts.pory"
	walk_up
# 672 "data/maps/LittlerootTown/scripts.pory"
# 338 "data/maps/LittlerootTown/scripts.pory"
# 673 "data/maps/LittlerootTown/scripts.pory"
	walk_in_place_faster_down
# 674 "data/maps/LittlerootTown/scripts.pory"
# 339 "data/maps/LittlerootTown/scripts.pory"
# 675 "data/maps/LittlerootTown/scripts.pory"
	step_end
# 676 "data/maps/LittlerootTown/scripts.pory"
# 340 "data/maps/LittlerootTown/scripts.pory"
# 677 "data/maps/LittlerootTown/scripts.pory"

# 678 "data/maps/LittlerootTown/scripts.pory"
# 341 "data/maps/LittlerootTown/scripts.pory"
# 679 "data/maps/LittlerootTown/scripts.pory"
LittlerootTown_Movement_PushPlayerBackFromRoute:
# 680 "data/maps/LittlerootTown/scripts.pory"
# 342 "data/maps/LittlerootTown/scripts.pory"
# 681 "data/maps/LittlerootTown/scripts.pory"
	lock_facing_direction
# 682 "data/maps/LittlerootTown/scripts.pory"
# 343 "data/maps/LittlerootTown/scripts.pory"
# 683 "data/maps/LittlerootTown/scripts.pory"
	walk_down
# 684 "data/maps/LittlerootTown/scripts.pory"
# 344 "data/maps/LittlerootTown/scripts.pory"
# 685 "data/maps/LittlerootTown/scripts.pory"
	unlock_facing_direction
# 686 "data/maps/LittlerootTown/scripts.pory"
# 345 "data/maps/LittlerootTown/scripts.pory"
# 687 "data/maps/LittlerootTown/scripts.pory"
	step_end
# 688 "data/maps/LittlerootTown/scripts.pory"
# 346 "data/maps/LittlerootTown/scripts.pory"
# 689 "data/maps/LittlerootTown/scripts.pory"

# 690 "data/maps/LittlerootTown/scripts.pory"
# 347 "data/maps/LittlerootTown/scripts.pory"
# 691 "data/maps/LittlerootTown/scripts.pory"
LittlerootTown_EventScript_NeedPokemonTriggerRight::
# 692 "data/maps/LittlerootTown/scripts.pory"
# 348 "data/maps/LittlerootTown/scripts.pory"
# 693 "data/maps/LittlerootTown/scripts.pory"
	lockall
# 694 "data/maps/LittlerootTown/scripts.pory"
# 349 "data/maps/LittlerootTown/scripts.pory"
# 695 "data/maps/LittlerootTown/scripts.pory"
	applymovement LOCALID_TWIN, LittlerootTown_Movement_TwinApproachPlayerRight
# 696 "data/maps/LittlerootTown/scripts.pory"
# 350 "data/maps/LittlerootTown/scripts.pory"
# 697 "data/maps/LittlerootTown/scripts.pory"
	waitmovement 0
# 698 "data/maps/LittlerootTown/scripts.pory"
# 351 "data/maps/LittlerootTown/scripts.pory"
# 699 "data/maps/LittlerootTown/scripts.pory"
	call LittlerootTown_EventScript_DangerousWithoutPokemon
# 700 "data/maps/LittlerootTown/scripts.pory"
# 352 "data/maps/LittlerootTown/scripts.pory"
# 701 "data/maps/LittlerootTown/scripts.pory"
	applymovement LOCALID_TWIN, LittlerootTown_Movement_TwinReturnRight
# 702 "data/maps/LittlerootTown/scripts.pory"
# 353 "data/maps/LittlerootTown/scripts.pory"
# 703 "data/maps/LittlerootTown/scripts.pory"
	waitmovement 0
# 704 "data/maps/LittlerootTown/scripts.pory"
# 354 "data/maps/LittlerootTown/scripts.pory"
# 705 "data/maps/LittlerootTown/scripts.pory"
	releaseall
# 706 "data/maps/LittlerootTown/scripts.pory"
# 355 "data/maps/LittlerootTown/scripts.pory"
# 707 "data/maps/LittlerootTown/scripts.pory"
	end
# 708 "data/maps/LittlerootTown/scripts.pory"
# 356 "data/maps/LittlerootTown/scripts.pory"
# 709 "data/maps/LittlerootTown/scripts.pory"

# 710 "data/maps/LittlerootTown/scripts.pory"
# 357 "data/maps/LittlerootTown/scripts.pory"
# 711 "data/maps/LittlerootTown/scripts.pory"
LittlerootTown_Movement_TwinApproachPlayerRight:
# 712 "data/maps/LittlerootTown/scripts.pory"
# 358 "data/maps/LittlerootTown/scripts.pory"
# 713 "data/maps/LittlerootTown/scripts.pory"
	face_right
# 714 "data/maps/LittlerootTown/scripts.pory"
# 359 "data/maps/LittlerootTown/scripts.pory"
# 715 "data/maps/LittlerootTown/scripts.pory"
	delay_8
# 716 "data/maps/LittlerootTown/scripts.pory"
# 360 "data/maps/LittlerootTown/scripts.pory"
# 717 "data/maps/LittlerootTown/scripts.pory"
	disable_jump_landing_ground_effect
# 718 "data/maps/LittlerootTown/scripts.pory"
# 361 "data/maps/LittlerootTown/scripts.pory"
# 719 "data/maps/LittlerootTown/scripts.pory"
	jump_in_place_right
# 720 "data/maps/LittlerootTown/scripts.pory"
# 362 "data/maps/LittlerootTown/scripts.pory"
# 721 "data/maps/LittlerootTown/scripts.pory"
	delay_8
# 722 "data/maps/LittlerootTown/scripts.pory"
# 363 "data/maps/LittlerootTown/scripts.pory"
# 723 "data/maps/LittlerootTown/scripts.pory"
	walk_fast_right
# 724 "data/maps/LittlerootTown/scripts.pory"
# 364 "data/maps/LittlerootTown/scripts.pory"
# 725 "data/maps/LittlerootTown/scripts.pory"
	walk_fast_right
# 726 "data/maps/LittlerootTown/scripts.pory"
# 365 "data/maps/LittlerootTown/scripts.pory"
# 727 "data/maps/LittlerootTown/scripts.pory"
	walk_fast_right
# 728 "data/maps/LittlerootTown/scripts.pory"
# 366 "data/maps/LittlerootTown/scripts.pory"
# 729 "data/maps/LittlerootTown/scripts.pory"
	walk_fast_up
# 730 "data/maps/LittlerootTown/scripts.pory"
# 367 "data/maps/LittlerootTown/scripts.pory"
# 731 "data/maps/LittlerootTown/scripts.pory"
	walk_fast_up
# 732 "data/maps/LittlerootTown/scripts.pory"
# 368 "data/maps/LittlerootTown/scripts.pory"
# 733 "data/maps/LittlerootTown/scripts.pory"
	walk_fast_right
# 734 "data/maps/LittlerootTown/scripts.pory"
# 369 "data/maps/LittlerootTown/scripts.pory"
# 735 "data/maps/LittlerootTown/scripts.pory"
	face_down
# 736 "data/maps/LittlerootTown/scripts.pory"
# 370 "data/maps/LittlerootTown/scripts.pory"
# 737 "data/maps/LittlerootTown/scripts.pory"
	step_end
# 738 "data/maps/LittlerootTown/scripts.pory"
# 371 "data/maps/LittlerootTown/scripts.pory"
# 739 "data/maps/LittlerootTown/scripts.pory"

# 740 "data/maps/LittlerootTown/scripts.pory"
# 372 "data/maps/LittlerootTown/scripts.pory"
# 741 "data/maps/LittlerootTown/scripts.pory"
LittlerootTown_Movement_TwinReturnRight:
# 742 "data/maps/LittlerootTown/scripts.pory"
# 373 "data/maps/LittlerootTown/scripts.pory"
# 743 "data/maps/LittlerootTown/scripts.pory"
	walk_left
# 744 "data/maps/LittlerootTown/scripts.pory"
# 374 "data/maps/LittlerootTown/scripts.pory"
# 745 "data/maps/LittlerootTown/scripts.pory"
	walk_down
# 746 "data/maps/LittlerootTown/scripts.pory"
# 375 "data/maps/LittlerootTown/scripts.pory"
# 747 "data/maps/LittlerootTown/scripts.pory"
	walk_left
# 748 "data/maps/LittlerootTown/scripts.pory"
# 376 "data/maps/LittlerootTown/scripts.pory"
# 749 "data/maps/LittlerootTown/scripts.pory"
	walk_left
# 750 "data/maps/LittlerootTown/scripts.pory"
# 377 "data/maps/LittlerootTown/scripts.pory"
# 751 "data/maps/LittlerootTown/scripts.pory"
	walk_left
# 752 "data/maps/LittlerootTown/scripts.pory"
# 378 "data/maps/LittlerootTown/scripts.pory"
# 753 "data/maps/LittlerootTown/scripts.pory"
	walk_in_place_faster_down
# 754 "data/maps/LittlerootTown/scripts.pory"
# 379 "data/maps/LittlerootTown/scripts.pory"
# 755 "data/maps/LittlerootTown/scripts.pory"
	step_end
# 756 "data/maps/LittlerootTown/scripts.pory"
# 380 "data/maps/LittlerootTown/scripts.pory"
# 757 "data/maps/LittlerootTown/scripts.pory"

# 758 "data/maps/LittlerootTown/scripts.pory"
# 381 "data/maps/LittlerootTown/scripts.pory"
# 759 "data/maps/LittlerootTown/scripts.pory"
LittlerootTown_EventScript_GoSaveBirchTrigger::
# 760 "data/maps/LittlerootTown/scripts.pory"
# 382 "data/maps/LittlerootTown/scripts.pory"
# 761 "data/maps/LittlerootTown/scripts.pory"
	lockall
# 762 "data/maps/LittlerootTown/scripts.pory"
# 383 "data/maps/LittlerootTown/scripts.pory"
# 763 "data/maps/LittlerootTown/scripts.pory"
	applymovement LOCALID_TWIN, Common_Movement_WalkInPlaceFasterRight
# 764 "data/maps/LittlerootTown/scripts.pory"
# 384 "data/maps/LittlerootTown/scripts.pory"
# 765 "data/maps/LittlerootTown/scripts.pory"
	waitmovement 0
# 766 "data/maps/LittlerootTown/scripts.pory"
# 385 "data/maps/LittlerootTown/scripts.pory"
# 767 "data/maps/LittlerootTown/scripts.pory"
	applymovement OBJ_EVENT_ID_PLAYER, Common_Movement_WalkInPlaceFasterLeft
# 768 "data/maps/LittlerootTown/scripts.pory"
# 386 "data/maps/LittlerootTown/scripts.pory"
# 769 "data/maps/LittlerootTown/scripts.pory"
	waitmovement 0
# 770 "data/maps/LittlerootTown/scripts.pory"
# 387 "data/maps/LittlerootTown/scripts.pory"
# 771 "data/maps/LittlerootTown/scripts.pory"
	special GetPlayerBigGuyGirlString
# 772 "data/maps/LittlerootTown/scripts.pory"
# 388 "data/maps/LittlerootTown/scripts.pory"
# 773 "data/maps/LittlerootTown/scripts.pory"
	msgbox LittlerootTown_Text_CanYouGoSeeWhatsHappening, MSGBOX_DEFAULT
# 774 "data/maps/LittlerootTown/scripts.pory"
# 389 "data/maps/LittlerootTown/scripts.pory"
# 775 "data/maps/LittlerootTown/scripts.pory"
	closemessage
# 776 "data/maps/LittlerootTown/scripts.pory"
# 390 "data/maps/LittlerootTown/scripts.pory"
# 777 "data/maps/LittlerootTown/scripts.pory"
	applymovement LOCALID_TWIN, Common_Movement_FaceOriginalDirection
# 778 "data/maps/LittlerootTown/scripts.pory"
# 391 "data/maps/LittlerootTown/scripts.pory"
# 779 "data/maps/LittlerootTown/scripts.pory"
	waitmovement 0
# 780 "data/maps/LittlerootTown/scripts.pory"
# 392 "data/maps/LittlerootTown/scripts.pory"
# 781 "data/maps/LittlerootTown/scripts.pory"
	setvar VAR_LITTLEROOT_TOWN_STATE, 2
# 782 "data/maps/LittlerootTown/scripts.pory"
# 393 "data/maps/LittlerootTown/scripts.pory"
# 783 "data/maps/LittlerootTown/scripts.pory"
	releaseall
# 784 "data/maps/LittlerootTown/scripts.pory"
# 394 "data/maps/LittlerootTown/scripts.pory"
# 785 "data/maps/LittlerootTown/scripts.pory"
	end
# 786 "data/maps/LittlerootTown/scripts.pory"
# 395 "data/maps/LittlerootTown/scripts.pory"
# 787 "data/maps/LittlerootTown/scripts.pory"

# 788 "data/maps/LittlerootTown/scripts.pory"
# 396 "data/maps/LittlerootTown/scripts.pory"
# 789 "data/maps/LittlerootTown/scripts.pory"
LittlerootTown_EventScript_TownSign::
# 790 "data/maps/LittlerootTown/scripts.pory"
# 397 "data/maps/LittlerootTown/scripts.pory"
# 791 "data/maps/LittlerootTown/scripts.pory"
	msgbox LittlerootTown_Text_TownSign, MSGBOX_SIGN
# 792 "data/maps/LittlerootTown/scripts.pory"
# 398 "data/maps/LittlerootTown/scripts.pory"
# 793 "data/maps/LittlerootTown/scripts.pory"
	end
# 794 "data/maps/LittlerootTown/scripts.pory"
# 399 "data/maps/LittlerootTown/scripts.pory"
# 795 "data/maps/LittlerootTown/scripts.pory"

# 796 "data/maps/LittlerootTown/scripts.pory"
# 400 "data/maps/LittlerootTown/scripts.pory"
# 797 "data/maps/LittlerootTown/scripts.pory"
LittlerootTown_EventScript_BirchsLabSign::
# 798 "data/maps/LittlerootTown/scripts.pory"
# 401 "data/maps/LittlerootTown/scripts.pory"
# 799 "data/maps/LittlerootTown/scripts.pory"
	msgbox LittlerootTown_Text_ProfBirchsLab, MSGBOX_SIGN
# 800 "data/maps/LittlerootTown/scripts.pory"
# 402 "data/maps/LittlerootTown/scripts.pory"
# 801 "data/maps/LittlerootTown/scripts.pory"
	end
# 802 "data/maps/LittlerootTown/scripts.pory"
# 403 "data/maps/LittlerootTown/scripts.pory"
# 803 "data/maps/LittlerootTown/scripts.pory"

# 804 "data/maps/LittlerootTown/scripts.pory"
# 404 "data/maps/LittlerootTown/scripts.pory"
# 805 "data/maps/LittlerootTown/scripts.pory"
LittlerootTown_EventScript_BrendansHouseSign::
# 806 "data/maps/LittlerootTown/scripts.pory"
# 405 "data/maps/LittlerootTown/scripts.pory"
# 807 "data/maps/LittlerootTown/scripts.pory"
	lockall
# 808 "data/maps/LittlerootTown/scripts.pory"
# 406 "data/maps/LittlerootTown/scripts.pory"
# 809 "data/maps/LittlerootTown/scripts.pory"
	checkplayergender
# 810 "data/maps/LittlerootTown/scripts.pory"
# 407 "data/maps/LittlerootTown/scripts.pory"
# 811 "data/maps/LittlerootTown/scripts.pory"
	call_if_eq VAR_RESULT, MALE, LittlerootTown_EventScript_PlayersHouseSignMale
# 812 "data/maps/LittlerootTown/scripts.pory"
# 408 "data/maps/LittlerootTown/scripts.pory"
# 813 "data/maps/LittlerootTown/scripts.pory"
	call_if_eq VAR_RESULT, FEMALE, LittlerootTown_EventScript_BirchsHouseSignFemale
# 814 "data/maps/LittlerootTown/scripts.pory"
# 409 "data/maps/LittlerootTown/scripts.pory"
# 815 "data/maps/LittlerootTown/scripts.pory"
	releaseall
# 816 "data/maps/LittlerootTown/scripts.pory"
# 410 "data/maps/LittlerootTown/scripts.pory"
# 817 "data/maps/LittlerootTown/scripts.pory"
	end
# 818 "data/maps/LittlerootTown/scripts.pory"
# 411 "data/maps/LittlerootTown/scripts.pory"
# 819 "data/maps/LittlerootTown/scripts.pory"

# 820 "data/maps/LittlerootTown/scripts.pory"
# 412 "data/maps/LittlerootTown/scripts.pory"
# 821 "data/maps/LittlerootTown/scripts.pory"
LittlerootTown_EventScript_PlayersHouseSignMale::
# 822 "data/maps/LittlerootTown/scripts.pory"
# 413 "data/maps/LittlerootTown/scripts.pory"
# 823 "data/maps/LittlerootTown/scripts.pory"
	msgbox LittlerootTown_Text_PlayersHouse, MSGBOX_DEFAULT
# 824 "data/maps/LittlerootTown/scripts.pory"
# 414 "data/maps/LittlerootTown/scripts.pory"
# 825 "data/maps/LittlerootTown/scripts.pory"
	return
# 826 "data/maps/LittlerootTown/scripts.pory"
# 415 "data/maps/LittlerootTown/scripts.pory"
# 827 "data/maps/LittlerootTown/scripts.pory"

# 828 "data/maps/LittlerootTown/scripts.pory"
# 416 "data/maps/LittlerootTown/scripts.pory"
# 829 "data/maps/LittlerootTown/scripts.pory"
LittlerootTown_EventScript_BirchsHouseSignFemale::
# 830 "data/maps/LittlerootTown/scripts.pory"
# 417 "data/maps/LittlerootTown/scripts.pory"
# 831 "data/maps/LittlerootTown/scripts.pory"
	msgbox LittlerootTown_Text_ProfBirchsHouse, MSGBOX_DEFAULT
# 832 "data/maps/LittlerootTown/scripts.pory"
# 418 "data/maps/LittlerootTown/scripts.pory"
# 833 "data/maps/LittlerootTown/scripts.pory"
	return
# 834 "data/maps/LittlerootTown/scripts.pory"
# 419 "data/maps/LittlerootTown/scripts.pory"
# 835 "data/maps/LittlerootTown/scripts.pory"

# 836 "data/maps/LittlerootTown/scripts.pory"
# 420 "data/maps/LittlerootTown/scripts.pory"
# 837 "data/maps/LittlerootTown/scripts.pory"
LittlerootTown_EventScript_MaysHouseSign::
# 838 "data/maps/LittlerootTown/scripts.pory"
# 421 "data/maps/LittlerootTown/scripts.pory"
# 839 "data/maps/LittlerootTown/scripts.pory"
	lockall
# 840 "data/maps/LittlerootTown/scripts.pory"
# 422 "data/maps/LittlerootTown/scripts.pory"
# 841 "data/maps/LittlerootTown/scripts.pory"
	checkplayergender
# 842 "data/maps/LittlerootTown/scripts.pory"
# 423 "data/maps/LittlerootTown/scripts.pory"
# 843 "data/maps/LittlerootTown/scripts.pory"
	call_if_eq VAR_RESULT, MALE, LittlerootTown_EventScript_BirchsHouseSignMale
# 844 "data/maps/LittlerootTown/scripts.pory"
# 424 "data/maps/LittlerootTown/scripts.pory"
# 845 "data/maps/LittlerootTown/scripts.pory"
	call_if_eq VAR_RESULT, FEMALE, LittlerootTown_EventScript_PlayersHouseSignFemale
# 846 "data/maps/LittlerootTown/scripts.pory"
# 425 "data/maps/LittlerootTown/scripts.pory"
# 847 "data/maps/LittlerootTown/scripts.pory"
	releaseall
# 848 "data/maps/LittlerootTown/scripts.pory"
# 426 "data/maps/LittlerootTown/scripts.pory"
# 849 "data/maps/LittlerootTown/scripts.pory"
	end
# 850 "data/maps/LittlerootTown/scripts.pory"
# 427 "data/maps/LittlerootTown/scripts.pory"
# 851 "data/maps/LittlerootTown/scripts.pory"

# 852 "data/maps/LittlerootTown/scripts.pory"
# 428 "data/maps/LittlerootTown/scripts.pory"
# 853 "data/maps/LittlerootTown/scripts.pory"
LittlerootTown_EventScript_BirchsHouseSignMale::
# 854 "data/maps/LittlerootTown/scripts.pory"
# 429 "data/maps/LittlerootTown/scripts.pory"
# 855 "data/maps/LittlerootTown/scripts.pory"
	msgbox LittlerootTown_Text_ProfBirchsHouse, MSGBOX_DEFAULT
# 856 "data/maps/LittlerootTown/scripts.pory"
# 430 "data/maps/LittlerootTown/scripts.pory"
# 857 "data/maps/LittlerootTown/scripts.pory"
	return
# 858 "data/maps/LittlerootTown/scripts.pory"
# 431 "data/maps/LittlerootTown/scripts.pory"
# 859 "data/maps/LittlerootTown/scripts.pory"

# 860 "data/maps/LittlerootTown/scripts.pory"
# 432 "data/maps/LittlerootTown/scripts.pory"
# 861 "data/maps/LittlerootTown/scripts.pory"
LittlerootTown_EventScript_PlayersHouseSignFemale::
# 862 "data/maps/LittlerootTown/scripts.pory"
# 433 "data/maps/LittlerootTown/scripts.pory"
# 863 "data/maps/LittlerootTown/scripts.pory"
	msgbox LittlerootTown_Text_PlayersHouse, MSGBOX_DEFAULT
# 864 "data/maps/LittlerootTown/scripts.pory"
# 434 "data/maps/LittlerootTown/scripts.pory"
# 865 "data/maps/LittlerootTown/scripts.pory"
	return
# 866 "data/maps/LittlerootTown/scripts.pory"
# 435 "data/maps/LittlerootTown/scripts.pory"
# 867 "data/maps/LittlerootTown/scripts.pory"

# 868 "data/maps/LittlerootTown/scripts.pory"
# 436 "data/maps/LittlerootTown/scripts.pory"
# 869 "data/maps/LittlerootTown/scripts.pory"
LittlerootTown_EventScript_GiveRunningShoesTrigger0::
# 870 "data/maps/LittlerootTown/scripts.pory"
# 437 "data/maps/LittlerootTown/scripts.pory"
# 871 "data/maps/LittlerootTown/scripts.pory"
	lockall
# 872 "data/maps/LittlerootTown/scripts.pory"
# 438 "data/maps/LittlerootTown/scripts.pory"
# 873 "data/maps/LittlerootTown/scripts.pory"
	setvar VAR_0x8008, 0
# 874 "data/maps/LittlerootTown/scripts.pory"
# 439 "data/maps/LittlerootTown/scripts.pory"
# 875 "data/maps/LittlerootTown/scripts.pory"
	setobjectxy LOCALID_MOM, 10, 9
# 876 "data/maps/LittlerootTown/scripts.pory"
# 440 "data/maps/LittlerootTown/scripts.pory"
# 877 "data/maps/LittlerootTown/scripts.pory"
	goto LittlerootTown_EventScript_GiveRunningShoesTrigger
# 878 "data/maps/LittlerootTown/scripts.pory"
# 441 "data/maps/LittlerootTown/scripts.pory"
# 879 "data/maps/LittlerootTown/scripts.pory"
	end
# 880 "data/maps/LittlerootTown/scripts.pory"
# 442 "data/maps/LittlerootTown/scripts.pory"
# 881 "data/maps/LittlerootTown/scripts.pory"

# 882 "data/maps/LittlerootTown/scripts.pory"
# 443 "data/maps/LittlerootTown/scripts.pory"
# 883 "data/maps/LittlerootTown/scripts.pory"
LittlerootTown_EventScript_GiveRunningShoesTrigger1::
# 884 "data/maps/LittlerootTown/scripts.pory"
# 444 "data/maps/LittlerootTown/scripts.pory"
# 885 "data/maps/LittlerootTown/scripts.pory"
	lockall
# 886 "data/maps/LittlerootTown/scripts.pory"
# 445 "data/maps/LittlerootTown/scripts.pory"
# 887 "data/maps/LittlerootTown/scripts.pory"
	setvar VAR_0x8008, 1
# 888 "data/maps/LittlerootTown/scripts.pory"
# 446 "data/maps/LittlerootTown/scripts.pory"
# 889 "data/maps/LittlerootTown/scripts.pory"
	setobjectxy LOCALID_MOM, 11, 9
# 890 "data/maps/LittlerootTown/scripts.pory"
# 447 "data/maps/LittlerootTown/scripts.pory"
# 891 "data/maps/LittlerootTown/scripts.pory"
	goto LittlerootTown_EventScript_GiveRunningShoesTrigger
# 892 "data/maps/LittlerootTown/scripts.pory"
# 448 "data/maps/LittlerootTown/scripts.pory"
# 893 "data/maps/LittlerootTown/scripts.pory"
	end
# 894 "data/maps/LittlerootTown/scripts.pory"
# 449 "data/maps/LittlerootTown/scripts.pory"
# 895 "data/maps/LittlerootTown/scripts.pory"

# 896 "data/maps/LittlerootTown/scripts.pory"
# 450 "data/maps/LittlerootTown/scripts.pory"
# 897 "data/maps/LittlerootTown/scripts.pory"
LittlerootTown_EventScript_GiveRunningShoesTrigger2::
# 898 "data/maps/LittlerootTown/scripts.pory"
# 451 "data/maps/LittlerootTown/scripts.pory"
# 899 "data/maps/LittlerootTown/scripts.pory"
	lockall
# 900 "data/maps/LittlerootTown/scripts.pory"
# 452 "data/maps/LittlerootTown/scripts.pory"
# 901 "data/maps/LittlerootTown/scripts.pory"
	setvar VAR_0x8008, 2
# 902 "data/maps/LittlerootTown/scripts.pory"
# 453 "data/maps/LittlerootTown/scripts.pory"
# 903 "data/maps/LittlerootTown/scripts.pory"
	goto LittlerootTown_EventScript_GiveRunningShoesTrigger
# 904 "data/maps/LittlerootTown/scripts.pory"
# 454 "data/maps/LittlerootTown/scripts.pory"
# 905 "data/maps/LittlerootTown/scripts.pory"
	end
# 906 "data/maps/LittlerootTown/scripts.pory"
# 455 "data/maps/LittlerootTown/scripts.pory"
# 907 "data/maps/LittlerootTown/scripts.pory"

# 908 "data/maps/LittlerootTown/scripts.pory"
# 456 "data/maps/LittlerootTown/scripts.pory"
# 909 "data/maps/LittlerootTown/scripts.pory"
LittlerootTown_EventScript_GiveRunningShoesTrigger3::
# 910 "data/maps/LittlerootTown/scripts.pory"
# 457 "data/maps/LittlerootTown/scripts.pory"
# 911 "data/maps/LittlerootTown/scripts.pory"
	lockall
# 912 "data/maps/LittlerootTown/scripts.pory"
# 458 "data/maps/LittlerootTown/scripts.pory"
# 913 "data/maps/LittlerootTown/scripts.pory"
	setvar VAR_0x8008, 3
# 914 "data/maps/LittlerootTown/scripts.pory"
# 459 "data/maps/LittlerootTown/scripts.pory"
# 915 "data/maps/LittlerootTown/scripts.pory"
	goto LittlerootTown_EventScript_GiveRunningShoesTrigger
# 916 "data/maps/LittlerootTown/scripts.pory"
# 460 "data/maps/LittlerootTown/scripts.pory"
# 917 "data/maps/LittlerootTown/scripts.pory"
	end
# 918 "data/maps/LittlerootTown/scripts.pory"
# 461 "data/maps/LittlerootTown/scripts.pory"
# 919 "data/maps/LittlerootTown/scripts.pory"

# 920 "data/maps/LittlerootTown/scripts.pory"
# 462 "data/maps/LittlerootTown/scripts.pory"
# 921 "data/maps/LittlerootTown/scripts.pory"
LittlerootTown_EventScript_GiveRunningShoesTrigger4::
# 922 "data/maps/LittlerootTown/scripts.pory"
# 463 "data/maps/LittlerootTown/scripts.pory"
# 923 "data/maps/LittlerootTown/scripts.pory"
	lockall
# 924 "data/maps/LittlerootTown/scripts.pory"
# 464 "data/maps/LittlerootTown/scripts.pory"
# 925 "data/maps/LittlerootTown/scripts.pory"
	setvar VAR_0x8008, 4
# 926 "data/maps/LittlerootTown/scripts.pory"
# 465 "data/maps/LittlerootTown/scripts.pory"
# 927 "data/maps/LittlerootTown/scripts.pory"
	goto LittlerootTown_EventScript_GiveRunningShoesTrigger
# 928 "data/maps/LittlerootTown/scripts.pory"
# 466 "data/maps/LittlerootTown/scripts.pory"
# 929 "data/maps/LittlerootTown/scripts.pory"
	end
# 930 "data/maps/LittlerootTown/scripts.pory"
# 467 "data/maps/LittlerootTown/scripts.pory"
# 931 "data/maps/LittlerootTown/scripts.pory"

# 932 "data/maps/LittlerootTown/scripts.pory"
# 468 "data/maps/LittlerootTown/scripts.pory"
# 933 "data/maps/LittlerootTown/scripts.pory"
LittlerootTown_EventScript_GiveRunningShoesTrigger5::
# 934 "data/maps/LittlerootTown/scripts.pory"
# 469 "data/maps/LittlerootTown/scripts.pory"
# 935 "data/maps/LittlerootTown/scripts.pory"
	lockall
# 936 "data/maps/LittlerootTown/scripts.pory"
# 470 "data/maps/LittlerootTown/scripts.pory"
# 937 "data/maps/LittlerootTown/scripts.pory"
	setvar VAR_0x8008, 5
# 938 "data/maps/LittlerootTown/scripts.pory"
# 471 "data/maps/LittlerootTown/scripts.pory"
# 939 "data/maps/LittlerootTown/scripts.pory"
	goto LittlerootTown_EventScript_GiveRunningShoesTrigger
# 940 "data/maps/LittlerootTown/scripts.pory"
# 472 "data/maps/LittlerootTown/scripts.pory"
# 941 "data/maps/LittlerootTown/scripts.pory"
	end
# 942 "data/maps/LittlerootTown/scripts.pory"
# 473 "data/maps/LittlerootTown/scripts.pory"
# 943 "data/maps/LittlerootTown/scripts.pory"

# 944 "data/maps/LittlerootTown/scripts.pory"
# 474 "data/maps/LittlerootTown/scripts.pory"
# 945 "data/maps/LittlerootTown/scripts.pory"
LittlerootTown_EventScript_GiveRunningShoesTrigger::
# 946 "data/maps/LittlerootTown/scripts.pory"
# 475 "data/maps/LittlerootTown/scripts.pory"
# 947 "data/maps/LittlerootTown/scripts.pory"
	checkplayergender
# 948 "data/maps/LittlerootTown/scripts.pory"
# 476 "data/maps/LittlerootTown/scripts.pory"
# 949 "data/maps/LittlerootTown/scripts.pory"
	call_if_eq VAR_RESULT, MALE, LittlerootTown_EventScript_MomNoticePlayerMale
# 950 "data/maps/LittlerootTown/scripts.pory"
# 477 "data/maps/LittlerootTown/scripts.pory"
# 951 "data/maps/LittlerootTown/scripts.pory"
	call_if_eq VAR_RESULT, FEMALE, LittlerootTown_EventScript_MomNoticePlayerFemale
# 952 "data/maps/LittlerootTown/scripts.pory"
# 478 "data/maps/LittlerootTown/scripts.pory"
# 953 "data/maps/LittlerootTown/scripts.pory"
	checkplayergender
# 954 "data/maps/LittlerootTown/scripts.pory"
# 479 "data/maps/LittlerootTown/scripts.pory"
# 955 "data/maps/LittlerootTown/scripts.pory"
	call_if_eq VAR_RESULT, MALE, LittlerootTown_EventScript_SetHomeDoorCoordsMale
# 956 "data/maps/LittlerootTown/scripts.pory"
# 480 "data/maps/LittlerootTown/scripts.pory"
# 957 "data/maps/LittlerootTown/scripts.pory"
	call_if_eq VAR_RESULT, FEMALE, LittlerootTown_EventScript_SetHomeDoorCoordsFemale
# 958 "data/maps/LittlerootTown/scripts.pory"
# 481 "data/maps/LittlerootTown/scripts.pory"
# 959 "data/maps/LittlerootTown/scripts.pory"
	msgbox LittlerootTown_Text_WaitPlayer, MSGBOX_DEFAULT
# 960 "data/maps/LittlerootTown/scripts.pory"
# 482 "data/maps/LittlerootTown/scripts.pory"
# 961 "data/maps/LittlerootTown/scripts.pory"
	closemessage
# 962 "data/maps/LittlerootTown/scripts.pory"
# 483 "data/maps/LittlerootTown/scripts.pory"
# 963 "data/maps/LittlerootTown/scripts.pory"
	checkplayergender
# 964 "data/maps/LittlerootTown/scripts.pory"
# 484 "data/maps/LittlerootTown/scripts.pory"
# 965 "data/maps/LittlerootTown/scripts.pory"
	call_if_eq VAR_RESULT, MALE, LittlerootTown_EventScript_MomApproachPlayerMale
# 966 "data/maps/LittlerootTown/scripts.pory"
# 485 "data/maps/LittlerootTown/scripts.pory"
# 967 "data/maps/LittlerootTown/scripts.pory"
	call_if_eq VAR_RESULT, FEMALE, LittlerootTown_EventScript_MomApproachPlayerFemale
# 968 "data/maps/LittlerootTown/scripts.pory"
# 486 "data/maps/LittlerootTown/scripts.pory"
# 969 "data/maps/LittlerootTown/scripts.pory"
	call LittlerootTown_EventScript_GiveRunningShoes
# 970 "data/maps/LittlerootTown/scripts.pory"
# 487 "data/maps/LittlerootTown/scripts.pory"
# 971 "data/maps/LittlerootTown/scripts.pory"
	checkplayergender
# 972 "data/maps/LittlerootTown/scripts.pory"
# 488 "data/maps/LittlerootTown/scripts.pory"
# 973 "data/maps/LittlerootTown/scripts.pory"
	call_if_eq VAR_RESULT, MALE, LittlerootTown_EventScript_MomReturnHomeMale
# 974 "data/maps/LittlerootTown/scripts.pory"
# 489 "data/maps/LittlerootTown/scripts.pory"
# 975 "data/maps/LittlerootTown/scripts.pory"
	call_if_eq VAR_RESULT, FEMALE, LittlerootTown_EventScript_MomReturnHomeFemale
# 976 "data/maps/LittlerootTown/scripts.pory"
# 490 "data/maps/LittlerootTown/scripts.pory"
# 977 "data/maps/LittlerootTown/scripts.pory"
	goto LittlerootTown_EventScript_SetReceivedRunningShoes
# 978 "data/maps/LittlerootTown/scripts.pory"
# 491 "data/maps/LittlerootTown/scripts.pory"
# 979 "data/maps/LittlerootTown/scripts.pory"
	end
# 980 "data/maps/LittlerootTown/scripts.pory"
# 492 "data/maps/LittlerootTown/scripts.pory"
# 981 "data/maps/LittlerootTown/scripts.pory"

# 982 "data/maps/LittlerootTown/scripts.pory"
# 493 "data/maps/LittlerootTown/scripts.pory"
# 983 "data/maps/LittlerootTown/scripts.pory"
LittlerootTown_EventScript_SetHomeDoorCoordsMale::
# 984 "data/maps/LittlerootTown/scripts.pory"
# 494 "data/maps/LittlerootTown/scripts.pory"
# 985 "data/maps/LittlerootTown/scripts.pory"
	setvar VAR_0x8009, 5
# 986 "data/maps/LittlerootTown/scripts.pory"
# 495 "data/maps/LittlerootTown/scripts.pory"
# 987 "data/maps/LittlerootTown/scripts.pory"
	setvar VAR_0x800A, 8
# 988 "data/maps/LittlerootTown/scripts.pory"
# 496 "data/maps/LittlerootTown/scripts.pory"
# 989 "data/maps/LittlerootTown/scripts.pory"
	return
# 990 "data/maps/LittlerootTown/scripts.pory"
# 497 "data/maps/LittlerootTown/scripts.pory"
# 991 "data/maps/LittlerootTown/scripts.pory"

# 992 "data/maps/LittlerootTown/scripts.pory"
# 498 "data/maps/LittlerootTown/scripts.pory"
# 993 "data/maps/LittlerootTown/scripts.pory"
LittlerootTown_EventScript_SetHomeDoorCoordsFemale::
# 994 "data/maps/LittlerootTown/scripts.pory"
# 499 "data/maps/LittlerootTown/scripts.pory"
# 995 "data/maps/LittlerootTown/scripts.pory"
	setvar VAR_0x8009, 14
# 996 "data/maps/LittlerootTown/scripts.pory"
# 500 "data/maps/LittlerootTown/scripts.pory"
# 997 "data/maps/LittlerootTown/scripts.pory"
	setvar VAR_0x800A, 8
# 998 "data/maps/LittlerootTown/scripts.pory"
# 501 "data/maps/LittlerootTown/scripts.pory"
# 999 "data/maps/LittlerootTown/scripts.pory"
	return
# 1000 "data/maps/LittlerootTown/scripts.pory"
# 502 "data/maps/LittlerootTown/scripts.pory"
# 1001 "data/maps/LittlerootTown/scripts.pory"

# 1002 "data/maps/LittlerootTown/scripts.pory"
# 503 "data/maps/LittlerootTown/scripts.pory"
# 1003 "data/maps/LittlerootTown/scripts.pory"
LittlerootTown_EventScript_MomNoticePlayerMale::
# 1004 "data/maps/LittlerootTown/scripts.pory"
# 504 "data/maps/LittlerootTown/scripts.pory"
# 1005 "data/maps/LittlerootTown/scripts.pory"
	applymovement LOCALID_MOM, Common_Movement_WalkInPlaceFasterRight
# 1006 "data/maps/LittlerootTown/scripts.pory"
# 505 "data/maps/LittlerootTown/scripts.pory"
# 1007 "data/maps/LittlerootTown/scripts.pory"
	waitmovement 0
# 1008 "data/maps/LittlerootTown/scripts.pory"
# 506 "data/maps/LittlerootTown/scripts.pory"
# 1009 "data/maps/LittlerootTown/scripts.pory"
	return
# 1010 "data/maps/LittlerootTown/scripts.pory"
# 507 "data/maps/LittlerootTown/scripts.pory"
# 1011 "data/maps/LittlerootTown/scripts.pory"

# 1012 "data/maps/LittlerootTown/scripts.pory"
# 508 "data/maps/LittlerootTown/scripts.pory"
# 1013 "data/maps/LittlerootTown/scripts.pory"
LittlerootTown_EventScript_MomNoticePlayerFemale::
# 1014 "data/maps/LittlerootTown/scripts.pory"
# 509 "data/maps/LittlerootTown/scripts.pory"
# 1015 "data/maps/LittlerootTown/scripts.pory"
	applymovement LOCALID_MOM, Common_Movement_WalkInPlaceFasterLeft
# 1016 "data/maps/LittlerootTown/scripts.pory"
# 510 "data/maps/LittlerootTown/scripts.pory"
# 1017 "data/maps/LittlerootTown/scripts.pory"
	waitmovement 0
# 1018 "data/maps/LittlerootTown/scripts.pory"
# 511 "data/maps/LittlerootTown/scripts.pory"
# 1019 "data/maps/LittlerootTown/scripts.pory"
	return
# 1020 "data/maps/LittlerootTown/scripts.pory"
# 512 "data/maps/LittlerootTown/scripts.pory"
# 1021 "data/maps/LittlerootTown/scripts.pory"

# 1022 "data/maps/LittlerootTown/scripts.pory"
# 513 "data/maps/LittlerootTown/scripts.pory"
# 1023 "data/maps/LittlerootTown/scripts.pory"
LittlerootTown_EventScript_MomApproachPlayerMale::
# 1024 "data/maps/LittlerootTown/scripts.pory"
# 514 "data/maps/LittlerootTown/scripts.pory"
# 1025 "data/maps/LittlerootTown/scripts.pory"
	call_if_eq VAR_0x8008, 0, LittlerootTown_EventScript_MomApproachPlayer0
# 1026 "data/maps/LittlerootTown/scripts.pory"
# 515 "data/maps/LittlerootTown/scripts.pory"
# 1027 "data/maps/LittlerootTown/scripts.pory"
	call_if_eq VAR_0x8008, 1, LittlerootTown_EventScript_MomApproachPlayer1
# 1028 "data/maps/LittlerootTown/scripts.pory"
# 516 "data/maps/LittlerootTown/scripts.pory"
# 1029 "data/maps/LittlerootTown/scripts.pory"
	call_if_eq VAR_0x8008, 2, LittlerootTown_EventScript_MomApproachPlayerMale2
# 1030 "data/maps/LittlerootTown/scripts.pory"
# 517 "data/maps/LittlerootTown/scripts.pory"
# 1031 "data/maps/LittlerootTown/scripts.pory"
	call_if_eq VAR_0x8008, 3, LittlerootTown_EventScript_MomApproachPlayerMale3
# 1032 "data/maps/LittlerootTown/scripts.pory"
# 518 "data/maps/LittlerootTown/scripts.pory"
# 1033 "data/maps/LittlerootTown/scripts.pory"
	call_if_eq VAR_0x8008, 4, LittlerootTown_EventScript_MomApproachPlayerMale4
# 1034 "data/maps/LittlerootTown/scripts.pory"
# 519 "data/maps/LittlerootTown/scripts.pory"
# 1035 "data/maps/LittlerootTown/scripts.pory"
	call_if_eq VAR_0x8008, 5, LittlerootTown_EventScript_MomApproachPlayerMale5
# 1036 "data/maps/LittlerootTown/scripts.pory"
# 520 "data/maps/LittlerootTown/scripts.pory"
# 1037 "data/maps/LittlerootTown/scripts.pory"
	return
# 1038 "data/maps/LittlerootTown/scripts.pory"
# 521 "data/maps/LittlerootTown/scripts.pory"
# 1039 "data/maps/LittlerootTown/scripts.pory"

# 1040 "data/maps/LittlerootTown/scripts.pory"
# 522 "data/maps/LittlerootTown/scripts.pory"
# 1041 "data/maps/LittlerootTown/scripts.pory"
LittlerootTown_EventScript_MomApproachPlayerFemale::
# 1042 "data/maps/LittlerootTown/scripts.pory"
# 523 "data/maps/LittlerootTown/scripts.pory"
# 1043 "data/maps/LittlerootTown/scripts.pory"
	call_if_eq VAR_0x8008, 0, LittlerootTown_EventScript_MomApproachPlayer0
# 1044 "data/maps/LittlerootTown/scripts.pory"
# 524 "data/maps/LittlerootTown/scripts.pory"
# 1045 "data/maps/LittlerootTown/scripts.pory"
	call_if_eq VAR_0x8008, 1, LittlerootTown_EventScript_MomApproachPlayer1
# 1046 "data/maps/LittlerootTown/scripts.pory"
# 525 "data/maps/LittlerootTown/scripts.pory"
# 1047 "data/maps/LittlerootTown/scripts.pory"
	call_if_eq VAR_0x8008, 2, LittlerootTown_EventScript_MomApproachPlayerFemale2
# 1048 "data/maps/LittlerootTown/scripts.pory"
# 526 "data/maps/LittlerootTown/scripts.pory"
# 1049 "data/maps/LittlerootTown/scripts.pory"
	call_if_eq VAR_0x8008, 3, LittlerootTown_EventScript_MomApproachPlayerFemale3
# 1050 "data/maps/LittlerootTown/scripts.pory"
# 527 "data/maps/LittlerootTown/scripts.pory"
# 1051 "data/maps/LittlerootTown/scripts.pory"
	call_if_eq VAR_0x8008, 4, LittlerootTown_EventScript_MomApproachPlayerFemale4
# 1052 "data/maps/LittlerootTown/scripts.pory"
# 528 "data/maps/LittlerootTown/scripts.pory"
# 1053 "data/maps/LittlerootTown/scripts.pory"
	call_if_eq VAR_0x8008, 5, LittlerootTown_EventScript_MomApproachPlayerFemale5
# 1054 "data/maps/LittlerootTown/scripts.pory"
# 529 "data/maps/LittlerootTown/scripts.pory"
# 1055 "data/maps/LittlerootTown/scripts.pory"
	return
# 1056 "data/maps/LittlerootTown/scripts.pory"
# 530 "data/maps/LittlerootTown/scripts.pory"
# 1057 "data/maps/LittlerootTown/scripts.pory"

# 1058 "data/maps/LittlerootTown/scripts.pory"
# 531 "data/maps/LittlerootTown/scripts.pory"
# 1059 "data/maps/LittlerootTown/scripts.pory"
LittlerootTown_EventScript_MomApproachPlayer0::
# 1060 "data/maps/LittlerootTown/scripts.pory"
# 532 "data/maps/LittlerootTown/scripts.pory"
# 1061 "data/maps/LittlerootTown/scripts.pory"
	applymovement OBJ_EVENT_ID_PLAYER, Common_Movement_WalkInPlaceFasterDown
# 1062 "data/maps/LittlerootTown/scripts.pory"
# 533 "data/maps/LittlerootTown/scripts.pory"
# 1063 "data/maps/LittlerootTown/scripts.pory"
	waitmovement 0
# 1064 "data/maps/LittlerootTown/scripts.pory"
# 534 "data/maps/LittlerootTown/scripts.pory"
# 1065 "data/maps/LittlerootTown/scripts.pory"
	applymovement LOCALID_MOM, LittlerootTown_Movement_MomApproachPlayer0
# 1066 "data/maps/LittlerootTown/scripts.pory"
# 535 "data/maps/LittlerootTown/scripts.pory"
# 1067 "data/maps/LittlerootTown/scripts.pory"
	waitmovement 0
# 1068 "data/maps/LittlerootTown/scripts.pory"
# 536 "data/maps/LittlerootTown/scripts.pory"
# 1069 "data/maps/LittlerootTown/scripts.pory"
	return
# 1070 "data/maps/LittlerootTown/scripts.pory"
# 537 "data/maps/LittlerootTown/scripts.pory"
# 1071 "data/maps/LittlerootTown/scripts.pory"

# 1072 "data/maps/LittlerootTown/scripts.pory"
# 538 "data/maps/LittlerootTown/scripts.pory"
# 1073 "data/maps/LittlerootTown/scripts.pory"
LittlerootTown_EventScript_MomApproachPlayer1::
# 1074 "data/maps/LittlerootTown/scripts.pory"
# 539 "data/maps/LittlerootTown/scripts.pory"
# 1075 "data/maps/LittlerootTown/scripts.pory"
	applymovement OBJ_EVENT_ID_PLAYER, Common_Movement_WalkInPlaceFasterDown
# 1076 "data/maps/LittlerootTown/scripts.pory"
# 540 "data/maps/LittlerootTown/scripts.pory"
# 1077 "data/maps/LittlerootTown/scripts.pory"
	waitmovement 0
# 1078 "data/maps/LittlerootTown/scripts.pory"
# 541 "data/maps/LittlerootTown/scripts.pory"
# 1079 "data/maps/LittlerootTown/scripts.pory"
	applymovement LOCALID_MOM, LittlerootTown_Movement_MomApproachPlayer1
# 1080 "data/maps/LittlerootTown/scripts.pory"
# 542 "data/maps/LittlerootTown/scripts.pory"
# 1081 "data/maps/LittlerootTown/scripts.pory"
	waitmovement 0
# 1082 "data/maps/LittlerootTown/scripts.pory"
# 543 "data/maps/LittlerootTown/scripts.pory"
# 1083 "data/maps/LittlerootTown/scripts.pory"
	return
# 1084 "data/maps/LittlerootTown/scripts.pory"
# 544 "data/maps/LittlerootTown/scripts.pory"
# 1085 "data/maps/LittlerootTown/scripts.pory"

# 1086 "data/maps/LittlerootTown/scripts.pory"
# 545 "data/maps/LittlerootTown/scripts.pory"
# 1087 "data/maps/LittlerootTown/scripts.pory"
LittlerootTown_EventScript_MomApproachPlayerMale2::
# 1088 "data/maps/LittlerootTown/scripts.pory"
# 546 "data/maps/LittlerootTown/scripts.pory"
# 1089 "data/maps/LittlerootTown/scripts.pory"
	applymovement OBJ_EVENT_ID_PLAYER, Common_Movement_WalkInPlaceFasterLeft
# 1090 "data/maps/LittlerootTown/scripts.pory"
# 547 "data/maps/LittlerootTown/scripts.pory"
# 1091 "data/maps/LittlerootTown/scripts.pory"
	waitmovement 0
# 1092 "data/maps/LittlerootTown/scripts.pory"
# 548 "data/maps/LittlerootTown/scripts.pory"
# 1093 "data/maps/LittlerootTown/scripts.pory"
	applymovement LOCALID_MOM, LittlerootTown_Movement_MomApproachPlayerMale2
# 1094 "data/maps/LittlerootTown/scripts.pory"
# 549 "data/maps/LittlerootTown/scripts.pory"
# 1095 "data/maps/LittlerootTown/scripts.pory"
	waitmovement 0
# 1096 "data/maps/LittlerootTown/scripts.pory"
# 550 "data/maps/LittlerootTown/scripts.pory"
# 1097 "data/maps/LittlerootTown/scripts.pory"
	return
# 1098 "data/maps/LittlerootTown/scripts.pory"
# 551 "data/maps/LittlerootTown/scripts.pory"
# 1099 "data/maps/LittlerootTown/scripts.pory"

# 1100 "data/maps/LittlerootTown/scripts.pory"
# 552 "data/maps/LittlerootTown/scripts.pory"
# 1101 "data/maps/LittlerootTown/scripts.pory"
LittlerootTown_EventScript_MomApproachPlayerMale3::
# 1102 "data/maps/LittlerootTown/scripts.pory"
# 553 "data/maps/LittlerootTown/scripts.pory"
# 1103 "data/maps/LittlerootTown/scripts.pory"
	applymovement OBJ_EVENT_ID_PLAYER, Common_Movement_WalkInPlaceFasterLeft
# 1104 "data/maps/LittlerootTown/scripts.pory"
# 554 "data/maps/LittlerootTown/scripts.pory"
# 1105 "data/maps/LittlerootTown/scripts.pory"
	waitmovement 0
# 1106 "data/maps/LittlerootTown/scripts.pory"
# 555 "data/maps/LittlerootTown/scripts.pory"
# 1107 "data/maps/LittlerootTown/scripts.pory"
	applymovement LOCALID_MOM, LittlerootTown_Movement_MomApproachPlayerMale3
# 1108 "data/maps/LittlerootTown/scripts.pory"
# 556 "data/maps/LittlerootTown/scripts.pory"
# 1109 "data/maps/LittlerootTown/scripts.pory"
	waitmovement 0
# 1110 "data/maps/LittlerootTown/scripts.pory"
# 557 "data/maps/LittlerootTown/scripts.pory"
# 1111 "data/maps/LittlerootTown/scripts.pory"
	return
# 1112 "data/maps/LittlerootTown/scripts.pory"
# 558 "data/maps/LittlerootTown/scripts.pory"
# 1113 "data/maps/LittlerootTown/scripts.pory"

# 1114 "data/maps/LittlerootTown/scripts.pory"
# 559 "data/maps/LittlerootTown/scripts.pory"
# 1115 "data/maps/LittlerootTown/scripts.pory"
LittlerootTown_EventScript_MomApproachPlayerMale4::
# 1116 "data/maps/LittlerootTown/scripts.pory"
# 560 "data/maps/LittlerootTown/scripts.pory"
# 1117 "data/maps/LittlerootTown/scripts.pory"
	applymovement OBJ_EVENT_ID_PLAYER, Common_Movement_WalkInPlaceFasterLeft
# 1118 "data/maps/LittlerootTown/scripts.pory"
# 561 "data/maps/LittlerootTown/scripts.pory"
# 1119 "data/maps/LittlerootTown/scripts.pory"
	waitmovement 0
# 1120 "data/maps/LittlerootTown/scripts.pory"
# 562 "data/maps/LittlerootTown/scripts.pory"
# 1121 "data/maps/LittlerootTown/scripts.pory"
	applymovement LOCALID_MOM, LittlerootTown_Movement_MomApproachPlayerMale4
# 1122 "data/maps/LittlerootTown/scripts.pory"
# 563 "data/maps/LittlerootTown/scripts.pory"
# 1123 "data/maps/LittlerootTown/scripts.pory"
	waitmovement 0
# 1124 "data/maps/LittlerootTown/scripts.pory"
# 564 "data/maps/LittlerootTown/scripts.pory"
# 1125 "data/maps/LittlerootTown/scripts.pory"
	return
# 1126 "data/maps/LittlerootTown/scripts.pory"
# 565 "data/maps/LittlerootTown/scripts.pory"
# 1127 "data/maps/LittlerootTown/scripts.pory"

# 1128 "data/maps/LittlerootTown/scripts.pory"
# 566 "data/maps/LittlerootTown/scripts.pory"
# 1129 "data/maps/LittlerootTown/scripts.pory"
LittlerootTown_EventScript_MomApproachPlayerMale5::
# 1130 "data/maps/LittlerootTown/scripts.pory"
# 567 "data/maps/LittlerootTown/scripts.pory"
# 1131 "data/maps/LittlerootTown/scripts.pory"
	applymovement OBJ_EVENT_ID_PLAYER, Common_Movement_WalkInPlaceFasterLeft
# 1132 "data/maps/LittlerootTown/scripts.pory"
# 568 "data/maps/LittlerootTown/scripts.pory"
# 1133 "data/maps/LittlerootTown/scripts.pory"
	waitmovement 0
# 1134 "data/maps/LittlerootTown/scripts.pory"
# 569 "data/maps/LittlerootTown/scripts.pory"
# 1135 "data/maps/LittlerootTown/scripts.pory"
	applymovement LOCALID_MOM, LittlerootTown_Movement_MomApproachPlayerMale5
# 1136 "data/maps/LittlerootTown/scripts.pory"
# 570 "data/maps/LittlerootTown/scripts.pory"
# 1137 "data/maps/LittlerootTown/scripts.pory"
	waitmovement 0
# 1138 "data/maps/LittlerootTown/scripts.pory"
# 571 "data/maps/LittlerootTown/scripts.pory"
# 1139 "data/maps/LittlerootTown/scripts.pory"
	return
# 1140 "data/maps/LittlerootTown/scripts.pory"
# 572 "data/maps/LittlerootTown/scripts.pory"
# 1141 "data/maps/LittlerootTown/scripts.pory"

# 1142 "data/maps/LittlerootTown/scripts.pory"
# 573 "data/maps/LittlerootTown/scripts.pory"
# 1143 "data/maps/LittlerootTown/scripts.pory"
LittlerootTown_EventScript_MomApproachPlayerFemale2::
# 1144 "data/maps/LittlerootTown/scripts.pory"
# 574 "data/maps/LittlerootTown/scripts.pory"
# 1145 "data/maps/LittlerootTown/scripts.pory"
	applymovement OBJ_EVENT_ID_PLAYER, Common_Movement_WalkInPlaceFasterRight
# 1146 "data/maps/LittlerootTown/scripts.pory"
# 575 "data/maps/LittlerootTown/scripts.pory"
# 1147 "data/maps/LittlerootTown/scripts.pory"
	waitmovement 0
# 1148 "data/maps/LittlerootTown/scripts.pory"
# 576 "data/maps/LittlerootTown/scripts.pory"
# 1149 "data/maps/LittlerootTown/scripts.pory"
	applymovement LOCALID_MOM, LittlerootTown_Movement_MomApproachPlayerFemale2
# 1150 "data/maps/LittlerootTown/scripts.pory"
# 577 "data/maps/LittlerootTown/scripts.pory"
# 1151 "data/maps/LittlerootTown/scripts.pory"
	waitmovement 0
# 1152 "data/maps/LittlerootTown/scripts.pory"
# 578 "data/maps/LittlerootTown/scripts.pory"
# 1153 "data/maps/LittlerootTown/scripts.pory"
	return
# 1154 "data/maps/LittlerootTown/scripts.pory"
# 579 "data/maps/LittlerootTown/scripts.pory"
# 1155 "data/maps/LittlerootTown/scripts.pory"

# 1156 "data/maps/LittlerootTown/scripts.pory"
# 580 "data/maps/LittlerootTown/scripts.pory"
# 1157 "data/maps/LittlerootTown/scripts.pory"
LittlerootTown_EventScript_MomApproachPlayerFemale3::
# 1158 "data/maps/LittlerootTown/scripts.pory"
# 581 "data/maps/LittlerootTown/scripts.pory"
# 1159 "data/maps/LittlerootTown/scripts.pory"
	applymovement OBJ_EVENT_ID_PLAYER, Common_Movement_WalkInPlaceFasterRight
# 1160 "data/maps/LittlerootTown/scripts.pory"
# 582 "data/maps/LittlerootTown/scripts.pory"
# 1161 "data/maps/LittlerootTown/scripts.pory"
	waitmovement 0
# 1162 "data/maps/LittlerootTown/scripts.pory"
# 583 "data/maps/LittlerootTown/scripts.pory"
# 1163 "data/maps/LittlerootTown/scripts.pory"
	applymovement LOCALID_MOM, LittlerootTown_Movement_MomApproachPlayerFemale3
# 1164 "data/maps/LittlerootTown/scripts.pory"
# 584 "data/maps/LittlerootTown/scripts.pory"
# 1165 "data/maps/LittlerootTown/scripts.pory"
	waitmovement 0
# 1166 "data/maps/LittlerootTown/scripts.pory"
# 585 "data/maps/LittlerootTown/scripts.pory"
# 1167 "data/maps/LittlerootTown/scripts.pory"
	return
# 1168 "data/maps/LittlerootTown/scripts.pory"
# 586 "data/maps/LittlerootTown/scripts.pory"
# 1169 "data/maps/LittlerootTown/scripts.pory"

# 1170 "data/maps/LittlerootTown/scripts.pory"
# 587 "data/maps/LittlerootTown/scripts.pory"
# 1171 "data/maps/LittlerootTown/scripts.pory"
LittlerootTown_EventScript_MomApproachPlayerFemale4::
# 1172 "data/maps/LittlerootTown/scripts.pory"
# 588 "data/maps/LittlerootTown/scripts.pory"
# 1173 "data/maps/LittlerootTown/scripts.pory"
	applymovement OBJ_EVENT_ID_PLAYER, Common_Movement_WalkInPlaceFasterRight
# 1174 "data/maps/LittlerootTown/scripts.pory"
# 589 "data/maps/LittlerootTown/scripts.pory"
# 1175 "data/maps/LittlerootTown/scripts.pory"
	waitmovement 0
# 1176 "data/maps/LittlerootTown/scripts.pory"
# 590 "data/maps/LittlerootTown/scripts.pory"
# 1177 "data/maps/LittlerootTown/scripts.pory"
	applymovement LOCALID_MOM, LittlerootTown_Movement_MomApproachPlayerFemale4
# 1178 "data/maps/LittlerootTown/scripts.pory"
# 591 "data/maps/LittlerootTown/scripts.pory"
# 1179 "data/maps/LittlerootTown/scripts.pory"
	waitmovement 0
# 1180 "data/maps/LittlerootTown/scripts.pory"
# 592 "data/maps/LittlerootTown/scripts.pory"
# 1181 "data/maps/LittlerootTown/scripts.pory"
	return
# 1182 "data/maps/LittlerootTown/scripts.pory"
# 593 "data/maps/LittlerootTown/scripts.pory"
# 1183 "data/maps/LittlerootTown/scripts.pory"

# 1184 "data/maps/LittlerootTown/scripts.pory"
# 594 "data/maps/LittlerootTown/scripts.pory"
# 1185 "data/maps/LittlerootTown/scripts.pory"
LittlerootTown_EventScript_MomApproachPlayerFemale5::
# 1186 "data/maps/LittlerootTown/scripts.pory"
# 595 "data/maps/LittlerootTown/scripts.pory"
# 1187 "data/maps/LittlerootTown/scripts.pory"
	applymovement OBJ_EVENT_ID_PLAYER, Common_Movement_WalkInPlaceFasterRight
# 1188 "data/maps/LittlerootTown/scripts.pory"
# 596 "data/maps/LittlerootTown/scripts.pory"
# 1189 "data/maps/LittlerootTown/scripts.pory"
	waitmovement 0
# 1190 "data/maps/LittlerootTown/scripts.pory"
# 597 "data/maps/LittlerootTown/scripts.pory"
# 1191 "data/maps/LittlerootTown/scripts.pory"
	applymovement LOCALID_MOM, LittlerootTown_Movement_MomApproachPlayerFemale5
# 1192 "data/maps/LittlerootTown/scripts.pory"
# 598 "data/maps/LittlerootTown/scripts.pory"
# 1193 "data/maps/LittlerootTown/scripts.pory"
	waitmovement 0
# 1194 "data/maps/LittlerootTown/scripts.pory"
# 599 "data/maps/LittlerootTown/scripts.pory"
# 1195 "data/maps/LittlerootTown/scripts.pory"
	return
# 1196 "data/maps/LittlerootTown/scripts.pory"
# 600 "data/maps/LittlerootTown/scripts.pory"
# 1197 "data/maps/LittlerootTown/scripts.pory"

# 1198 "data/maps/LittlerootTown/scripts.pory"
# 601 "data/maps/LittlerootTown/scripts.pory"
# 1199 "data/maps/LittlerootTown/scripts.pory"
LittlerootTown_EventScript_MomReturnHomeMale::
# 1200 "data/maps/LittlerootTown/scripts.pory"
# 602 "data/maps/LittlerootTown/scripts.pory"
# 1201 "data/maps/LittlerootTown/scripts.pory"
	call_if_eq VAR_0x8008, 0, LittlerootTown_EventScript_MomReturnHome0
# 1202 "data/maps/LittlerootTown/scripts.pory"
# 603 "data/maps/LittlerootTown/scripts.pory"
# 1203 "data/maps/LittlerootTown/scripts.pory"
	call_if_eq VAR_0x8008, 1, LittlerootTown_EventScript_MomReturnHome1
# 1204 "data/maps/LittlerootTown/scripts.pory"
# 604 "data/maps/LittlerootTown/scripts.pory"
# 1205 "data/maps/LittlerootTown/scripts.pory"
	call_if_eq VAR_0x8008, 2, LittlerootTown_EventScript_MomReturnHomeMale2
# 1206 "data/maps/LittlerootTown/scripts.pory"
# 605 "data/maps/LittlerootTown/scripts.pory"
# 1207 "data/maps/LittlerootTown/scripts.pory"
	call_if_eq VAR_0x8008, 3, LittlerootTown_EventScript_MomReturnHomeMale3
# 1208 "data/maps/LittlerootTown/scripts.pory"
# 606 "data/maps/LittlerootTown/scripts.pory"
# 1209 "data/maps/LittlerootTown/scripts.pory"
	call_if_eq VAR_0x8008, 4, LittlerootTown_EventScript_MomReturnHomeMale4
# 1210 "data/maps/LittlerootTown/scripts.pory"
# 607 "data/maps/LittlerootTown/scripts.pory"
# 1211 "data/maps/LittlerootTown/scripts.pory"
	call_if_eq VAR_0x8008, 5, LittlerootTown_EventScript_MomReturnHomeMale5
# 1212 "data/maps/LittlerootTown/scripts.pory"
# 608 "data/maps/LittlerootTown/scripts.pory"
# 1213 "data/maps/LittlerootTown/scripts.pory"
	return
# 1214 "data/maps/LittlerootTown/scripts.pory"
# 609 "data/maps/LittlerootTown/scripts.pory"
# 1215 "data/maps/LittlerootTown/scripts.pory"

# 1216 "data/maps/LittlerootTown/scripts.pory"
# 610 "data/maps/LittlerootTown/scripts.pory"
# 1217 "data/maps/LittlerootTown/scripts.pory"
LittlerootTown_EventScript_MomReturnHomeFemale::
# 1218 "data/maps/LittlerootTown/scripts.pory"
# 611 "data/maps/LittlerootTown/scripts.pory"
# 1219 "data/maps/LittlerootTown/scripts.pory"
	call_if_eq VAR_0x8008, 0, LittlerootTown_EventScript_MomReturnHome0
# 1220 "data/maps/LittlerootTown/scripts.pory"
# 612 "data/maps/LittlerootTown/scripts.pory"
# 1221 "data/maps/LittlerootTown/scripts.pory"
	call_if_eq VAR_0x8008, 1, LittlerootTown_EventScript_MomReturnHome1
# 1222 "data/maps/LittlerootTown/scripts.pory"
# 613 "data/maps/LittlerootTown/scripts.pory"
# 1223 "data/maps/LittlerootTown/scripts.pory"
	call_if_eq VAR_0x8008, 2, LittlerootTown_EventScript_MomReturnHomeFemale2
# 1224 "data/maps/LittlerootTown/scripts.pory"
# 614 "data/maps/LittlerootTown/scripts.pory"
# 1225 "data/maps/LittlerootTown/scripts.pory"
	call_if_eq VAR_0x8008, 3, LittlerootTown_EventScript_MomReturnHomeFemale3
# 1226 "data/maps/LittlerootTown/scripts.pory"
# 615 "data/maps/LittlerootTown/scripts.pory"
# 1227 "data/maps/LittlerootTown/scripts.pory"
	call_if_eq VAR_0x8008, 4, LittlerootTown_EventScript_MomReturnHomeFemale4
# 1228 "data/maps/LittlerootTown/scripts.pory"
# 616 "data/maps/LittlerootTown/scripts.pory"
# 1229 "data/maps/LittlerootTown/scripts.pory"
	call_if_eq VAR_0x8008, 5, LittlerootTown_EventScript_MomReturnHomeFemale5
# 1230 "data/maps/LittlerootTown/scripts.pory"
# 617 "data/maps/LittlerootTown/scripts.pory"
# 1231 "data/maps/LittlerootTown/scripts.pory"
	return
# 1232 "data/maps/LittlerootTown/scripts.pory"
# 618 "data/maps/LittlerootTown/scripts.pory"
# 1233 "data/maps/LittlerootTown/scripts.pory"

# 1234 "data/maps/LittlerootTown/scripts.pory"
# 619 "data/maps/LittlerootTown/scripts.pory"
# 1235 "data/maps/LittlerootTown/scripts.pory"
LittlerootTown_EventScript_MomReturnHome0::
# 1236 "data/maps/LittlerootTown/scripts.pory"
# 620 "data/maps/LittlerootTown/scripts.pory"
# 1237 "data/maps/LittlerootTown/scripts.pory"
	applymovement LOCALID_MOM, LittlerootTown_Movement_MomReturnHome0
# 1238 "data/maps/LittlerootTown/scripts.pory"
# 621 "data/maps/LittlerootTown/scripts.pory"
# 1239 "data/maps/LittlerootTown/scripts.pory"
	waitmovement 0
# 1240 "data/maps/LittlerootTown/scripts.pory"
# 622 "data/maps/LittlerootTown/scripts.pory"
# 1241 "data/maps/LittlerootTown/scripts.pory"
	return
# 1242 "data/maps/LittlerootTown/scripts.pory"
# 623 "data/maps/LittlerootTown/scripts.pory"
# 1243 "data/maps/LittlerootTown/scripts.pory"

# 1244 "data/maps/LittlerootTown/scripts.pory"
# 624 "data/maps/LittlerootTown/scripts.pory"
# 1245 "data/maps/LittlerootTown/scripts.pory"
LittlerootTown_EventScript_MomReturnHome1::
# 1246 "data/maps/LittlerootTown/scripts.pory"
# 625 "data/maps/LittlerootTown/scripts.pory"
# 1247 "data/maps/LittlerootTown/scripts.pory"
	applymovement LOCALID_MOM, LittlerootTown_Movement_MomReturnHome1
# 1248 "data/maps/LittlerootTown/scripts.pory"
# 626 "data/maps/LittlerootTown/scripts.pory"
# 1249 "data/maps/LittlerootTown/scripts.pory"
	waitmovement 0
# 1250 "data/maps/LittlerootTown/scripts.pory"
# 627 "data/maps/LittlerootTown/scripts.pory"
# 1251 "data/maps/LittlerootTown/scripts.pory"
	return
# 1252 "data/maps/LittlerootTown/scripts.pory"
# 628 "data/maps/LittlerootTown/scripts.pory"
# 1253 "data/maps/LittlerootTown/scripts.pory"

# 1254 "data/maps/LittlerootTown/scripts.pory"
# 629 "data/maps/LittlerootTown/scripts.pory"
# 1255 "data/maps/LittlerootTown/scripts.pory"
LittlerootTown_EventScript_MomReturnHomeMale2::
# 1256 "data/maps/LittlerootTown/scripts.pory"
# 630 "data/maps/LittlerootTown/scripts.pory"
# 1257 "data/maps/LittlerootTown/scripts.pory"
	applymovement LOCALID_MOM, LittlerootTown_Movement_MomReturnHomeMale2
# 1258 "data/maps/LittlerootTown/scripts.pory"
# 631 "data/maps/LittlerootTown/scripts.pory"
# 1259 "data/maps/LittlerootTown/scripts.pory"
	waitmovement 0
# 1260 "data/maps/LittlerootTown/scripts.pory"
# 632 "data/maps/LittlerootTown/scripts.pory"
# 1261 "data/maps/LittlerootTown/scripts.pory"
	opendoor VAR_0x8009, VAR_0x800A
# 1262 "data/maps/LittlerootTown/scripts.pory"
# 633 "data/maps/LittlerootTown/scripts.pory"
# 1263 "data/maps/LittlerootTown/scripts.pory"
	waitdooranim
# 1264 "data/maps/LittlerootTown/scripts.pory"
# 634 "data/maps/LittlerootTown/scripts.pory"
# 1265 "data/maps/LittlerootTown/scripts.pory"
	applymovement LOCALID_MOM, LittlerootTown_Movement_MomExitThroughDoor
# 1266 "data/maps/LittlerootTown/scripts.pory"
# 635 "data/maps/LittlerootTown/scripts.pory"
# 1267 "data/maps/LittlerootTown/scripts.pory"
	waitmovement 0
# 1268 "data/maps/LittlerootTown/scripts.pory"
# 636 "data/maps/LittlerootTown/scripts.pory"
# 1269 "data/maps/LittlerootTown/scripts.pory"
	hideobjectat LOCALID_MOM, MAP_LITTLEROOT_TOWN
# 1270 "data/maps/LittlerootTown/scripts.pory"
# 637 "data/maps/LittlerootTown/scripts.pory"
# 1271 "data/maps/LittlerootTown/scripts.pory"
	closedoor VAR_0x8009, VAR_0x800A
# 1272 "data/maps/LittlerootTown/scripts.pory"
# 638 "data/maps/LittlerootTown/scripts.pory"
# 1273 "data/maps/LittlerootTown/scripts.pory"
	waitdooranim
# 1274 "data/maps/LittlerootTown/scripts.pory"
# 639 "data/maps/LittlerootTown/scripts.pory"
# 1275 "data/maps/LittlerootTown/scripts.pory"
	return
# 1276 "data/maps/LittlerootTown/scripts.pory"
# 640 "data/maps/LittlerootTown/scripts.pory"
# 1277 "data/maps/LittlerootTown/scripts.pory"

# 1278 "data/maps/LittlerootTown/scripts.pory"
# 641 "data/maps/LittlerootTown/scripts.pory"
# 1279 "data/maps/LittlerootTown/scripts.pory"
LittlerootTown_EventScript_MomReturnHomeMale3::
# 1280 "data/maps/LittlerootTown/scripts.pory"
# 642 "data/maps/LittlerootTown/scripts.pory"
# 1281 "data/maps/LittlerootTown/scripts.pory"
	applymovement LOCALID_MOM, LittlerootTown_Movement_MomReturnHomeMale3
# 1282 "data/maps/LittlerootTown/scripts.pory"
# 643 "data/maps/LittlerootTown/scripts.pory"
# 1283 "data/maps/LittlerootTown/scripts.pory"
	waitmovement 0
# 1284 "data/maps/LittlerootTown/scripts.pory"
# 644 "data/maps/LittlerootTown/scripts.pory"
# 1285 "data/maps/LittlerootTown/scripts.pory"
	opendoor VAR_0x8009, VAR_0x800A
# 1286 "data/maps/LittlerootTown/scripts.pory"
# 645 "data/maps/LittlerootTown/scripts.pory"
# 1287 "data/maps/LittlerootTown/scripts.pory"
	waitdooranim
# 1288 "data/maps/LittlerootTown/scripts.pory"
# 646 "data/maps/LittlerootTown/scripts.pory"
# 1289 "data/maps/LittlerootTown/scripts.pory"
	applymovement LOCALID_MOM, LittlerootTown_Movement_MomExitThroughDoor
# 1290 "data/maps/LittlerootTown/scripts.pory"
# 647 "data/maps/LittlerootTown/scripts.pory"
# 1291 "data/maps/LittlerootTown/scripts.pory"
	waitmovement 0
# 1292 "data/maps/LittlerootTown/scripts.pory"
# 648 "data/maps/LittlerootTown/scripts.pory"
# 1293 "data/maps/LittlerootTown/scripts.pory"
	hideobjectat LOCALID_MOM, MAP_LITTLEROOT_TOWN
# 1294 "data/maps/LittlerootTown/scripts.pory"
# 649 "data/maps/LittlerootTown/scripts.pory"
# 1295 "data/maps/LittlerootTown/scripts.pory"
	closedoor VAR_0x8009, VAR_0x800A
# 1296 "data/maps/LittlerootTown/scripts.pory"
# 650 "data/maps/LittlerootTown/scripts.pory"
# 1297 "data/maps/LittlerootTown/scripts.pory"
	waitdooranim
# 1298 "data/maps/LittlerootTown/scripts.pory"
# 651 "data/maps/LittlerootTown/scripts.pory"
# 1299 "data/maps/LittlerootTown/scripts.pory"
	return
# 1300 "data/maps/LittlerootTown/scripts.pory"
# 652 "data/maps/LittlerootTown/scripts.pory"
# 1301 "data/maps/LittlerootTown/scripts.pory"

# 1302 "data/maps/LittlerootTown/scripts.pory"
# 653 "data/maps/LittlerootTown/scripts.pory"
# 1303 "data/maps/LittlerootTown/scripts.pory"
LittlerootTown_EventScript_MomReturnHomeMale4::
# 1304 "data/maps/LittlerootTown/scripts.pory"
# 654 "data/maps/LittlerootTown/scripts.pory"
# 1305 "data/maps/LittlerootTown/scripts.pory"
	applymovement LOCALID_MOM, LittlerootTown_Movement_MomReturnHomeMale4
# 1306 "data/maps/LittlerootTown/scripts.pory"
# 655 "data/maps/LittlerootTown/scripts.pory"
# 1307 "data/maps/LittlerootTown/scripts.pory"
	waitmovement 0
# 1308 "data/maps/LittlerootTown/scripts.pory"
# 656 "data/maps/LittlerootTown/scripts.pory"
# 1309 "data/maps/LittlerootTown/scripts.pory"
	opendoor VAR_0x8009, VAR_0x800A
# 1310 "data/maps/LittlerootTown/scripts.pory"
# 657 "data/maps/LittlerootTown/scripts.pory"
# 1311 "data/maps/LittlerootTown/scripts.pory"
	waitdooranim
# 1312 "data/maps/LittlerootTown/scripts.pory"
# 658 "data/maps/LittlerootTown/scripts.pory"
# 1313 "data/maps/LittlerootTown/scripts.pory"
	applymovement LOCALID_MOM, LittlerootTown_Movement_MomExitThroughDoor
# 1314 "data/maps/LittlerootTown/scripts.pory"
# 659 "data/maps/LittlerootTown/scripts.pory"
# 1315 "data/maps/LittlerootTown/scripts.pory"
	waitmovement 0
# 1316 "data/maps/LittlerootTown/scripts.pory"
# 660 "data/maps/LittlerootTown/scripts.pory"
# 1317 "data/maps/LittlerootTown/scripts.pory"
	hideobjectat LOCALID_MOM, MAP_LITTLEROOT_TOWN
# 1318 "data/maps/LittlerootTown/scripts.pory"
# 661 "data/maps/LittlerootTown/scripts.pory"
# 1319 "data/maps/LittlerootTown/scripts.pory"
	closedoor VAR_0x8009, VAR_0x800A
# 1320 "data/maps/LittlerootTown/scripts.pory"
# 662 "data/maps/LittlerootTown/scripts.pory"
# 1321 "data/maps/LittlerootTown/scripts.pory"
	waitdooranim
# 1322 "data/maps/LittlerootTown/scripts.pory"
# 663 "data/maps/LittlerootTown/scripts.pory"
# 1323 "data/maps/LittlerootTown/scripts.pory"
	return
# 1324 "data/maps/LittlerootTown/scripts.pory"
# 664 "data/maps/LittlerootTown/scripts.pory"
# 1325 "data/maps/LittlerootTown/scripts.pory"

# 1326 "data/maps/LittlerootTown/scripts.pory"
# 665 "data/maps/LittlerootTown/scripts.pory"
# 1327 "data/maps/LittlerootTown/scripts.pory"
LittlerootTown_EventScript_MomReturnHomeMale5::
# 1328 "data/maps/LittlerootTown/scripts.pory"
# 666 "data/maps/LittlerootTown/scripts.pory"
# 1329 "data/maps/LittlerootTown/scripts.pory"
	applymovement LOCALID_MOM, LittlerootTown_Movement_MomReturnHomeMale5
# 1330 "data/maps/LittlerootTown/scripts.pory"
# 667 "data/maps/LittlerootTown/scripts.pory"
# 1331 "data/maps/LittlerootTown/scripts.pory"
	waitmovement 0
# 1332 "data/maps/LittlerootTown/scripts.pory"
# 668 "data/maps/LittlerootTown/scripts.pory"
# 1333 "data/maps/LittlerootTown/scripts.pory"
	opendoor VAR_0x8009, VAR_0x800A
# 1334 "data/maps/LittlerootTown/scripts.pory"
# 669 "data/maps/LittlerootTown/scripts.pory"
# 1335 "data/maps/LittlerootTown/scripts.pory"
	waitdooranim
# 1336 "data/maps/LittlerootTown/scripts.pory"
# 670 "data/maps/LittlerootTown/scripts.pory"
# 1337 "data/maps/LittlerootTown/scripts.pory"
	applymovement LOCALID_MOM, LittlerootTown_Movement_MomExitThroughDoor
# 1338 "data/maps/LittlerootTown/scripts.pory"
# 671 "data/maps/LittlerootTown/scripts.pory"
# 1339 "data/maps/LittlerootTown/scripts.pory"
	waitmovement 0
# 1340 "data/maps/LittlerootTown/scripts.pory"
# 672 "data/maps/LittlerootTown/scripts.pory"
# 1341 "data/maps/LittlerootTown/scripts.pory"
	hideobjectat LOCALID_MOM, MAP_LITTLEROOT_TOWN
# 1342 "data/maps/LittlerootTown/scripts.pory"
# 673 "data/maps/LittlerootTown/scripts.pory"
# 1343 "data/maps/LittlerootTown/scripts.pory"
	closedoor VAR_0x8009, VAR_0x800A
# 1344 "data/maps/LittlerootTown/scripts.pory"
# 674 "data/maps/LittlerootTown/scripts.pory"
# 1345 "data/maps/LittlerootTown/scripts.pory"
	waitdooranim
# 1346 "data/maps/LittlerootTown/scripts.pory"
# 675 "data/maps/LittlerootTown/scripts.pory"
# 1347 "data/maps/LittlerootTown/scripts.pory"
	return
# 1348 "data/maps/LittlerootTown/scripts.pory"
# 676 "data/maps/LittlerootTown/scripts.pory"
# 1349 "data/maps/LittlerootTown/scripts.pory"

# 1350 "data/maps/LittlerootTown/scripts.pory"
# 677 "data/maps/LittlerootTown/scripts.pory"
# 1351 "data/maps/LittlerootTown/scripts.pory"
LittlerootTown_EventScript_MomReturnHomeFemale2::
# 1352 "data/maps/LittlerootTown/scripts.pory"
# 678 "data/maps/LittlerootTown/scripts.pory"
# 1353 "data/maps/LittlerootTown/scripts.pory"
	applymovement LOCALID_MOM, LittlerootTown_Movement_MomReturnHomeFemale2
# 1354 "data/maps/LittlerootTown/scripts.pory"
# 679 "data/maps/LittlerootTown/scripts.pory"
# 1355 "data/maps/LittlerootTown/scripts.pory"
	waitmovement 0
# 1356 "data/maps/LittlerootTown/scripts.pory"
# 680 "data/maps/LittlerootTown/scripts.pory"
# 1357 "data/maps/LittlerootTown/scripts.pory"
	opendoor VAR_0x8009, VAR_0x800A
# 1358 "data/maps/LittlerootTown/scripts.pory"
# 681 "data/maps/LittlerootTown/scripts.pory"
# 1359 "data/maps/LittlerootTown/scripts.pory"
	waitdooranim
# 1360 "data/maps/LittlerootTown/scripts.pory"
# 682 "data/maps/LittlerootTown/scripts.pory"
# 1361 "data/maps/LittlerootTown/scripts.pory"
	applymovement LOCALID_MOM, LittlerootTown_Movement_MomExitThroughDoor
# 1362 "data/maps/LittlerootTown/scripts.pory"
# 683 "data/maps/LittlerootTown/scripts.pory"
# 1363 "data/maps/LittlerootTown/scripts.pory"
	waitmovement 0
# 1364 "data/maps/LittlerootTown/scripts.pory"
# 684 "data/maps/LittlerootTown/scripts.pory"
# 1365 "data/maps/LittlerootTown/scripts.pory"
	hideobjectat LOCALID_MOM, MAP_LITTLEROOT_TOWN
# 1366 "data/maps/LittlerootTown/scripts.pory"
# 685 "data/maps/LittlerootTown/scripts.pory"
# 1367 "data/maps/LittlerootTown/scripts.pory"
	closedoor VAR_0x8009, VAR_0x800A
# 1368 "data/maps/LittlerootTown/scripts.pory"
# 686 "data/maps/LittlerootTown/scripts.pory"
# 1369 "data/maps/LittlerootTown/scripts.pory"
	waitdooranim
# 1370 "data/maps/LittlerootTown/scripts.pory"
# 687 "data/maps/LittlerootTown/scripts.pory"
# 1371 "data/maps/LittlerootTown/scripts.pory"
	return
# 1372 "data/maps/LittlerootTown/scripts.pory"
# 688 "data/maps/LittlerootTown/scripts.pory"
# 1373 "data/maps/LittlerootTown/scripts.pory"

# 1374 "data/maps/LittlerootTown/scripts.pory"
# 689 "data/maps/LittlerootTown/scripts.pory"
# 1375 "data/maps/LittlerootTown/scripts.pory"
LittlerootTown_EventScript_MomReturnHomeFemale3::
# 1376 "data/maps/LittlerootTown/scripts.pory"
# 690 "data/maps/LittlerootTown/scripts.pory"
# 1377 "data/maps/LittlerootTown/scripts.pory"
	applymovement LOCALID_MOM, LittlerootTown_Movement_MomReturnHomeFemale3
# 1378 "data/maps/LittlerootTown/scripts.pory"
# 691 "data/maps/LittlerootTown/scripts.pory"
# 1379 "data/maps/LittlerootTown/scripts.pory"
	waitmovement 0
# 1380 "data/maps/LittlerootTown/scripts.pory"
# 692 "data/maps/LittlerootTown/scripts.pory"
# 1381 "data/maps/LittlerootTown/scripts.pory"
	opendoor VAR_0x8009, VAR_0x800A
# 1382 "data/maps/LittlerootTown/scripts.pory"
# 693 "data/maps/LittlerootTown/scripts.pory"
# 1383 "data/maps/LittlerootTown/scripts.pory"
	waitdooranim
# 1384 "data/maps/LittlerootTown/scripts.pory"
# 694 "data/maps/LittlerootTown/scripts.pory"
# 1385 "data/maps/LittlerootTown/scripts.pory"
	applymovement LOCALID_MOM, LittlerootTown_Movement_MomExitThroughDoor
# 1386 "data/maps/LittlerootTown/scripts.pory"
# 695 "data/maps/LittlerootTown/scripts.pory"
# 1387 "data/maps/LittlerootTown/scripts.pory"
	waitmovement 0
# 1388 "data/maps/LittlerootTown/scripts.pory"
# 696 "data/maps/LittlerootTown/scripts.pory"
# 1389 "data/maps/LittlerootTown/scripts.pory"
	hideobjectat LOCALID_MOM, MAP_LITTLEROOT_TOWN
# 1390 "data/maps/LittlerootTown/scripts.pory"
# 697 "data/maps/LittlerootTown/scripts.pory"
# 1391 "data/maps/LittlerootTown/scripts.pory"
	closedoor VAR_0x8009, VAR_0x800A
# 1392 "data/maps/LittlerootTown/scripts.pory"
# 698 "data/maps/LittlerootTown/scripts.pory"
# 1393 "data/maps/LittlerootTown/scripts.pory"
	waitdooranim
# 1394 "data/maps/LittlerootTown/scripts.pory"
# 699 "data/maps/LittlerootTown/scripts.pory"
# 1395 "data/maps/LittlerootTown/scripts.pory"
	return
# 1396 "data/maps/LittlerootTown/scripts.pory"
# 700 "data/maps/LittlerootTown/scripts.pory"
# 1397 "data/maps/LittlerootTown/scripts.pory"

# 1398 "data/maps/LittlerootTown/scripts.pory"
# 701 "data/maps/LittlerootTown/scripts.pory"
# 1399 "data/maps/LittlerootTown/scripts.pory"
LittlerootTown_EventScript_MomReturnHomeFemale4::
# 1400 "data/maps/LittlerootTown/scripts.pory"
# 702 "data/maps/LittlerootTown/scripts.pory"
# 1401 "data/maps/LittlerootTown/scripts.pory"
	applymovement LOCALID_MOM, LittlerootTown_Movement_MomReturnHomeFemale4
# 1402 "data/maps/LittlerootTown/scripts.pory"
# 703 "data/maps/LittlerootTown/scripts.pory"
# 1403 "data/maps/LittlerootTown/scripts.pory"
	waitmovement 0
# 1404 "data/maps/LittlerootTown/scripts.pory"
# 704 "data/maps/LittlerootTown/scripts.pory"
# 1405 "data/maps/LittlerootTown/scripts.pory"
	opendoor VAR_0x8009, VAR_0x800A
# 1406 "data/maps/LittlerootTown/scripts.pory"
# 705 "data/maps/LittlerootTown/scripts.pory"
# 1407 "data/maps/LittlerootTown/scripts.pory"
	waitdooranim
# 1408 "data/maps/LittlerootTown/scripts.pory"
# 706 "data/maps/LittlerootTown/scripts.pory"
# 1409 "data/maps/LittlerootTown/scripts.pory"
	applymovement LOCALID_MOM, LittlerootTown_Movement_MomExitThroughDoor
# 1410 "data/maps/LittlerootTown/scripts.pory"
# 707 "data/maps/LittlerootTown/scripts.pory"
# 1411 "data/maps/LittlerootTown/scripts.pory"
	waitmovement 0
# 1412 "data/maps/LittlerootTown/scripts.pory"
# 708 "data/maps/LittlerootTown/scripts.pory"
# 1413 "data/maps/LittlerootTown/scripts.pory"
	hideobjectat LOCALID_MOM, MAP_LITTLEROOT_TOWN
# 1414 "data/maps/LittlerootTown/scripts.pory"
# 709 "data/maps/LittlerootTown/scripts.pory"
# 1415 "data/maps/LittlerootTown/scripts.pory"
	closedoor VAR_0x8009, VAR_0x800A
# 1416 "data/maps/LittlerootTown/scripts.pory"
# 710 "data/maps/LittlerootTown/scripts.pory"
# 1417 "data/maps/LittlerootTown/scripts.pory"
	waitdooranim
# 1418 "data/maps/LittlerootTown/scripts.pory"
# 711 "data/maps/LittlerootTown/scripts.pory"
# 1419 "data/maps/LittlerootTown/scripts.pory"
	return
# 1420 "data/maps/LittlerootTown/scripts.pory"
# 712 "data/maps/LittlerootTown/scripts.pory"
# 1421 "data/maps/LittlerootTown/scripts.pory"

# 1422 "data/maps/LittlerootTown/scripts.pory"
# 713 "data/maps/LittlerootTown/scripts.pory"
# 1423 "data/maps/LittlerootTown/scripts.pory"
LittlerootTown_EventScript_MomReturnHomeFemale5::
# 1424 "data/maps/LittlerootTown/scripts.pory"
# 714 "data/maps/LittlerootTown/scripts.pory"
# 1425 "data/maps/LittlerootTown/scripts.pory"
	applymovement LOCALID_MOM, LittlerootTown_Movement_MomReturnHomeFemale5
# 1426 "data/maps/LittlerootTown/scripts.pory"
# 715 "data/maps/LittlerootTown/scripts.pory"
# 1427 "data/maps/LittlerootTown/scripts.pory"
	waitmovement 0
# 1428 "data/maps/LittlerootTown/scripts.pory"
# 716 "data/maps/LittlerootTown/scripts.pory"
# 1429 "data/maps/LittlerootTown/scripts.pory"
	opendoor VAR_0x8009, VAR_0x800A
# 1430 "data/maps/LittlerootTown/scripts.pory"
# 717 "data/maps/LittlerootTown/scripts.pory"
# 1431 "data/maps/LittlerootTown/scripts.pory"
	waitdooranim
# 1432 "data/maps/LittlerootTown/scripts.pory"
# 718 "data/maps/LittlerootTown/scripts.pory"
# 1433 "data/maps/LittlerootTown/scripts.pory"
	applymovement LOCALID_MOM, LittlerootTown_Movement_MomExitThroughDoor
# 1434 "data/maps/LittlerootTown/scripts.pory"
# 719 "data/maps/LittlerootTown/scripts.pory"
# 1435 "data/maps/LittlerootTown/scripts.pory"
	waitmovement 0
# 1436 "data/maps/LittlerootTown/scripts.pory"
# 720 "data/maps/LittlerootTown/scripts.pory"
# 1437 "data/maps/LittlerootTown/scripts.pory"
	hideobjectat LOCALID_MOM, MAP_LITTLEROOT_TOWN
# 1438 "data/maps/LittlerootTown/scripts.pory"
# 721 "data/maps/LittlerootTown/scripts.pory"
# 1439 "data/maps/LittlerootTown/scripts.pory"
	closedoor VAR_0x8009, VAR_0x800A
# 1440 "data/maps/LittlerootTown/scripts.pory"
# 722 "data/maps/LittlerootTown/scripts.pory"
# 1441 "data/maps/LittlerootTown/scripts.pory"
	waitdooranim
# 1442 "data/maps/LittlerootTown/scripts.pory"
# 723 "data/maps/LittlerootTown/scripts.pory"
# 1443 "data/maps/LittlerootTown/scripts.pory"
	return
# 1444 "data/maps/LittlerootTown/scripts.pory"
# 724 "data/maps/LittlerootTown/scripts.pory"
# 1445 "data/maps/LittlerootTown/scripts.pory"

# 1446 "data/maps/LittlerootTown/scripts.pory"
# 725 "data/maps/LittlerootTown/scripts.pory"
# 1447 "data/maps/LittlerootTown/scripts.pory"
LittlerootTown_Movement_MomApproachPlayer0:
# 1448 "data/maps/LittlerootTown/scripts.pory"
# 726 "data/maps/LittlerootTown/scripts.pory"
# 1449 "data/maps/LittlerootTown/scripts.pory"
	walk_up
# 1450 "data/maps/LittlerootTown/scripts.pory"
# 727 "data/maps/LittlerootTown/scripts.pory"
# 1451 "data/maps/LittlerootTown/scripts.pory"
	walk_up
# 1452 "data/maps/LittlerootTown/scripts.pory"
# 728 "data/maps/LittlerootTown/scripts.pory"
# 1453 "data/maps/LittlerootTown/scripts.pory"
	walk_up
# 1454 "data/maps/LittlerootTown/scripts.pory"
# 729 "data/maps/LittlerootTown/scripts.pory"
# 1455 "data/maps/LittlerootTown/scripts.pory"
	walk_up
# 1456 "data/maps/LittlerootTown/scripts.pory"
# 730 "data/maps/LittlerootTown/scripts.pory"
# 1457 "data/maps/LittlerootTown/scripts.pory"
	walk_up
# 1458 "data/maps/LittlerootTown/scripts.pory"
# 731 "data/maps/LittlerootTown/scripts.pory"
# 1459 "data/maps/LittlerootTown/scripts.pory"
	walk_up
# 1460 "data/maps/LittlerootTown/scripts.pory"
# 732 "data/maps/LittlerootTown/scripts.pory"
# 1461 "data/maps/LittlerootTown/scripts.pory"
	step_end
# 1462 "data/maps/LittlerootTown/scripts.pory"
# 733 "data/maps/LittlerootTown/scripts.pory"
# 1463 "data/maps/LittlerootTown/scripts.pory"

# 1464 "data/maps/LittlerootTown/scripts.pory"
# 734 "data/maps/LittlerootTown/scripts.pory"
# 1465 "data/maps/LittlerootTown/scripts.pory"
LittlerootTown_Movement_MomApproachPlayer1:
# 1466 "data/maps/LittlerootTown/scripts.pory"
# 735 "data/maps/LittlerootTown/scripts.pory"
# 1467 "data/maps/LittlerootTown/scripts.pory"
	walk_up
# 1468 "data/maps/LittlerootTown/scripts.pory"
# 736 "data/maps/LittlerootTown/scripts.pory"
# 1469 "data/maps/LittlerootTown/scripts.pory"
	walk_up
# 1470 "data/maps/LittlerootTown/scripts.pory"
# 737 "data/maps/LittlerootTown/scripts.pory"
# 1471 "data/maps/LittlerootTown/scripts.pory"
	walk_up
# 1472 "data/maps/LittlerootTown/scripts.pory"
# 738 "data/maps/LittlerootTown/scripts.pory"
# 1473 "data/maps/LittlerootTown/scripts.pory"
	walk_up
# 1474 "data/maps/LittlerootTown/scripts.pory"
# 739 "data/maps/LittlerootTown/scripts.pory"
# 1475 "data/maps/LittlerootTown/scripts.pory"
	walk_up
# 1476 "data/maps/LittlerootTown/scripts.pory"
# 740 "data/maps/LittlerootTown/scripts.pory"
# 1477 "data/maps/LittlerootTown/scripts.pory"
	walk_up
# 1478 "data/maps/LittlerootTown/scripts.pory"
# 741 "data/maps/LittlerootTown/scripts.pory"
# 1479 "data/maps/LittlerootTown/scripts.pory"
	step_end
# 1480 "data/maps/LittlerootTown/scripts.pory"
# 742 "data/maps/LittlerootTown/scripts.pory"
# 1481 "data/maps/LittlerootTown/scripts.pory"

# 1482 "data/maps/LittlerootTown/scripts.pory"
# 743 "data/maps/LittlerootTown/scripts.pory"
# 1483 "data/maps/LittlerootTown/scripts.pory"
LittlerootTown_Movement_MomApproachPlayerMale2:
# 1484 "data/maps/LittlerootTown/scripts.pory"
# 744 "data/maps/LittlerootTown/scripts.pory"
# 1485 "data/maps/LittlerootTown/scripts.pory"
	walk_right
# 1486 "data/maps/LittlerootTown/scripts.pory"
# 745 "data/maps/LittlerootTown/scripts.pory"
# 1487 "data/maps/LittlerootTown/scripts.pory"
	walk_right
# 1488 "data/maps/LittlerootTown/scripts.pory"
# 746 "data/maps/LittlerootTown/scripts.pory"
# 1489 "data/maps/LittlerootTown/scripts.pory"
	walk_right
# 1490 "data/maps/LittlerootTown/scripts.pory"
# 747 "data/maps/LittlerootTown/scripts.pory"
# 1491 "data/maps/LittlerootTown/scripts.pory"
	walk_right
# 1492 "data/maps/LittlerootTown/scripts.pory"
# 748 "data/maps/LittlerootTown/scripts.pory"
# 1493 "data/maps/LittlerootTown/scripts.pory"
	step_end
# 1494 "data/maps/LittlerootTown/scripts.pory"
# 749 "data/maps/LittlerootTown/scripts.pory"
# 1495 "data/maps/LittlerootTown/scripts.pory"

# 1496 "data/maps/LittlerootTown/scripts.pory"
# 750 "data/maps/LittlerootTown/scripts.pory"
# 1497 "data/maps/LittlerootTown/scripts.pory"
LittlerootTown_Movement_MomApproachPlayerMale3:
# 1498 "data/maps/LittlerootTown/scripts.pory"
# 751 "data/maps/LittlerootTown/scripts.pory"
# 1499 "data/maps/LittlerootTown/scripts.pory"
	walk_right
# 1500 "data/maps/LittlerootTown/scripts.pory"
# 752 "data/maps/LittlerootTown/scripts.pory"
# 1501 "data/maps/LittlerootTown/scripts.pory"
	walk_right
# 1502 "data/maps/LittlerootTown/scripts.pory"
# 753 "data/maps/LittlerootTown/scripts.pory"
# 1503 "data/maps/LittlerootTown/scripts.pory"
	walk_right
# 1504 "data/maps/LittlerootTown/scripts.pory"
# 754 "data/maps/LittlerootTown/scripts.pory"
# 1505 "data/maps/LittlerootTown/scripts.pory"
	walk_right
# 1506 "data/maps/LittlerootTown/scripts.pory"
# 755 "data/maps/LittlerootTown/scripts.pory"
# 1507 "data/maps/LittlerootTown/scripts.pory"
	walk_right
# 1508 "data/maps/LittlerootTown/scripts.pory"
# 756 "data/maps/LittlerootTown/scripts.pory"
# 1509 "data/maps/LittlerootTown/scripts.pory"
	step_end
# 1510 "data/maps/LittlerootTown/scripts.pory"
# 757 "data/maps/LittlerootTown/scripts.pory"
# 1511 "data/maps/LittlerootTown/scripts.pory"

# 1512 "data/maps/LittlerootTown/scripts.pory"
# 758 "data/maps/LittlerootTown/scripts.pory"
# 1513 "data/maps/LittlerootTown/scripts.pory"
LittlerootTown_Movement_MomApproachPlayerMale4:
# 1514 "data/maps/LittlerootTown/scripts.pory"
# 759 "data/maps/LittlerootTown/scripts.pory"
# 1515 "data/maps/LittlerootTown/scripts.pory"
	walk_right
# 1516 "data/maps/LittlerootTown/scripts.pory"
# 760 "data/maps/LittlerootTown/scripts.pory"
# 1517 "data/maps/LittlerootTown/scripts.pory"
	walk_right
# 1518 "data/maps/LittlerootTown/scripts.pory"
# 761 "data/maps/LittlerootTown/scripts.pory"
# 1519 "data/maps/LittlerootTown/scripts.pory"
	step_end
# 1520 "data/maps/LittlerootTown/scripts.pory"
# 762 "data/maps/LittlerootTown/scripts.pory"
# 1521 "data/maps/LittlerootTown/scripts.pory"

# 1522 "data/maps/LittlerootTown/scripts.pory"
# 763 "data/maps/LittlerootTown/scripts.pory"
# 1523 "data/maps/LittlerootTown/scripts.pory"
LittlerootTown_Movement_MomApproachPlayerMale5:
# 1524 "data/maps/LittlerootTown/scripts.pory"
# 764 "data/maps/LittlerootTown/scripts.pory"
# 1525 "data/maps/LittlerootTown/scripts.pory"
	walk_right
# 1526 "data/maps/LittlerootTown/scripts.pory"
# 765 "data/maps/LittlerootTown/scripts.pory"
# 1527 "data/maps/LittlerootTown/scripts.pory"
	walk_right
# 1528 "data/maps/LittlerootTown/scripts.pory"
# 766 "data/maps/LittlerootTown/scripts.pory"
# 1529 "data/maps/LittlerootTown/scripts.pory"
	walk_right
# 1530 "data/maps/LittlerootTown/scripts.pory"
# 767 "data/maps/LittlerootTown/scripts.pory"
# 1531 "data/maps/LittlerootTown/scripts.pory"
	step_end
# 1532 "data/maps/LittlerootTown/scripts.pory"
# 768 "data/maps/LittlerootTown/scripts.pory"
# 1533 "data/maps/LittlerootTown/scripts.pory"

# 1534 "data/maps/LittlerootTown/scripts.pory"
# 769 "data/maps/LittlerootTown/scripts.pory"
# 1535 "data/maps/LittlerootTown/scripts.pory"
LittlerootTown_Movement_MomApproachPlayerFemale2:
# 1536 "data/maps/LittlerootTown/scripts.pory"
# 770 "data/maps/LittlerootTown/scripts.pory"
# 1537 "data/maps/LittlerootTown/scripts.pory"
	walk_left
# 1538 "data/maps/LittlerootTown/scripts.pory"
# 771 "data/maps/LittlerootTown/scripts.pory"
# 1539 "data/maps/LittlerootTown/scripts.pory"
	walk_left
# 1540 "data/maps/LittlerootTown/scripts.pory"
# 772 "data/maps/LittlerootTown/scripts.pory"
# 1541 "data/maps/LittlerootTown/scripts.pory"
	walk_left
# 1542 "data/maps/LittlerootTown/scripts.pory"
# 773 "data/maps/LittlerootTown/scripts.pory"
# 1543 "data/maps/LittlerootTown/scripts.pory"
	step_end
# 1544 "data/maps/LittlerootTown/scripts.pory"
# 774 "data/maps/LittlerootTown/scripts.pory"
# 1545 "data/maps/LittlerootTown/scripts.pory"

# 1546 "data/maps/LittlerootTown/scripts.pory"
# 775 "data/maps/LittlerootTown/scripts.pory"
# 1547 "data/maps/LittlerootTown/scripts.pory"
LittlerootTown_Movement_MomApproachPlayerFemale3:
# 1548 "data/maps/LittlerootTown/scripts.pory"
# 776 "data/maps/LittlerootTown/scripts.pory"
# 1549 "data/maps/LittlerootTown/scripts.pory"
	walk_left
# 1550 "data/maps/LittlerootTown/scripts.pory"
# 777 "data/maps/LittlerootTown/scripts.pory"
# 1551 "data/maps/LittlerootTown/scripts.pory"
	walk_left
# 1552 "data/maps/LittlerootTown/scripts.pory"
# 778 "data/maps/LittlerootTown/scripts.pory"
# 1553 "data/maps/LittlerootTown/scripts.pory"
	step_end
# 1554 "data/maps/LittlerootTown/scripts.pory"
# 779 "data/maps/LittlerootTown/scripts.pory"
# 1555 "data/maps/LittlerootTown/scripts.pory"

# 1556 "data/maps/LittlerootTown/scripts.pory"
# 780 "data/maps/LittlerootTown/scripts.pory"
# 1557 "data/maps/LittlerootTown/scripts.pory"
LittlerootTown_Movement_MomApproachPlayerFemale4:
# 1558 "data/maps/LittlerootTown/scripts.pory"
# 781 "data/maps/LittlerootTown/scripts.pory"
# 1559 "data/maps/LittlerootTown/scripts.pory"
	walk_left
# 1560 "data/maps/LittlerootTown/scripts.pory"
# 782 "data/maps/LittlerootTown/scripts.pory"
# 1561 "data/maps/LittlerootTown/scripts.pory"
	walk_left
# 1562 "data/maps/LittlerootTown/scripts.pory"
# 783 "data/maps/LittlerootTown/scripts.pory"
# 1563 "data/maps/LittlerootTown/scripts.pory"
	walk_left
# 1564 "data/maps/LittlerootTown/scripts.pory"
# 784 "data/maps/LittlerootTown/scripts.pory"
# 1565 "data/maps/LittlerootTown/scripts.pory"
	walk_left
# 1566 "data/maps/LittlerootTown/scripts.pory"
# 785 "data/maps/LittlerootTown/scripts.pory"
# 1567 "data/maps/LittlerootTown/scripts.pory"
	walk_left
# 1568 "data/maps/LittlerootTown/scripts.pory"
# 786 "data/maps/LittlerootTown/scripts.pory"
# 1569 "data/maps/LittlerootTown/scripts.pory"
	step_end
# 1570 "data/maps/LittlerootTown/scripts.pory"
# 787 "data/maps/LittlerootTown/scripts.pory"
# 1571 "data/maps/LittlerootTown/scripts.pory"

# 1572 "data/maps/LittlerootTown/scripts.pory"
# 788 "data/maps/LittlerootTown/scripts.pory"
# 1573 "data/maps/LittlerootTown/scripts.pory"
LittlerootTown_Movement_MomApproachPlayerFemale5:
# 1574 "data/maps/LittlerootTown/scripts.pory"
# 789 "data/maps/LittlerootTown/scripts.pory"
# 1575 "data/maps/LittlerootTown/scripts.pory"
	walk_left
# 1576 "data/maps/LittlerootTown/scripts.pory"
# 790 "data/maps/LittlerootTown/scripts.pory"
# 1577 "data/maps/LittlerootTown/scripts.pory"
	walk_left
# 1578 "data/maps/LittlerootTown/scripts.pory"
# 791 "data/maps/LittlerootTown/scripts.pory"
# 1579 "data/maps/LittlerootTown/scripts.pory"
	walk_left
# 1580 "data/maps/LittlerootTown/scripts.pory"
# 792 "data/maps/LittlerootTown/scripts.pory"
# 1581 "data/maps/LittlerootTown/scripts.pory"
	walk_left
# 1582 "data/maps/LittlerootTown/scripts.pory"
# 793 "data/maps/LittlerootTown/scripts.pory"
# 1583 "data/maps/LittlerootTown/scripts.pory"
	step_end
# 1584 "data/maps/LittlerootTown/scripts.pory"
# 794 "data/maps/LittlerootTown/scripts.pory"
# 1585 "data/maps/LittlerootTown/scripts.pory"

# 1586 "data/maps/LittlerootTown/scripts.pory"
# 795 "data/maps/LittlerootTown/scripts.pory"
# 1587 "data/maps/LittlerootTown/scripts.pory"
LittlerootTown_Movement_MomReturnHome0:
# 1588 "data/maps/LittlerootTown/scripts.pory"
# 796 "data/maps/LittlerootTown/scripts.pory"
# 1589 "data/maps/LittlerootTown/scripts.pory"
	walk_down
# 1590 "data/maps/LittlerootTown/scripts.pory"
# 797 "data/maps/LittlerootTown/scripts.pory"
# 1591 "data/maps/LittlerootTown/scripts.pory"
	walk_down
# 1592 "data/maps/LittlerootTown/scripts.pory"
# 798 "data/maps/LittlerootTown/scripts.pory"
# 1593 "data/maps/LittlerootTown/scripts.pory"
	walk_down
# 1594 "data/maps/LittlerootTown/scripts.pory"
# 799 "data/maps/LittlerootTown/scripts.pory"
# 1595 "data/maps/LittlerootTown/scripts.pory"
	walk_down
# 1596 "data/maps/LittlerootTown/scripts.pory"
# 800 "data/maps/LittlerootTown/scripts.pory"
# 1597 "data/maps/LittlerootTown/scripts.pory"
	walk_down
# 1598 "data/maps/LittlerootTown/scripts.pory"
# 801 "data/maps/LittlerootTown/scripts.pory"
# 1599 "data/maps/LittlerootTown/scripts.pory"
	step_end
# 1600 "data/maps/LittlerootTown/scripts.pory"
# 802 "data/maps/LittlerootTown/scripts.pory"
# 1601 "data/maps/LittlerootTown/scripts.pory"

# 1602 "data/maps/LittlerootTown/scripts.pory"
# 803 "data/maps/LittlerootTown/scripts.pory"
# 1603 "data/maps/LittlerootTown/scripts.pory"
LittlerootTown_Movement_MomReturnHome1:
# 1604 "data/maps/LittlerootTown/scripts.pory"
# 804 "data/maps/LittlerootTown/scripts.pory"
# 1605 "data/maps/LittlerootTown/scripts.pory"
	walk_down
# 1606 "data/maps/LittlerootTown/scripts.pory"
# 805 "data/maps/LittlerootTown/scripts.pory"
# 1607 "data/maps/LittlerootTown/scripts.pory"
	walk_down
# 1608 "data/maps/LittlerootTown/scripts.pory"
# 806 "data/maps/LittlerootTown/scripts.pory"
# 1609 "data/maps/LittlerootTown/scripts.pory"
	walk_down
# 1610 "data/maps/LittlerootTown/scripts.pory"
# 807 "data/maps/LittlerootTown/scripts.pory"
# 1611 "data/maps/LittlerootTown/scripts.pory"
	walk_down
# 1612 "data/maps/LittlerootTown/scripts.pory"
# 808 "data/maps/LittlerootTown/scripts.pory"
# 1613 "data/maps/LittlerootTown/scripts.pory"
	walk_down
# 1614 "data/maps/LittlerootTown/scripts.pory"
# 809 "data/maps/LittlerootTown/scripts.pory"
# 1615 "data/maps/LittlerootTown/scripts.pory"
	step_end
# 1616 "data/maps/LittlerootTown/scripts.pory"
# 810 "data/maps/LittlerootTown/scripts.pory"
# 1617 "data/maps/LittlerootTown/scripts.pory"

# 1618 "data/maps/LittlerootTown/scripts.pory"
# 811 "data/maps/LittlerootTown/scripts.pory"
# 1619 "data/maps/LittlerootTown/scripts.pory"
LittlerootTown_Movement_MomReturnHomeMale2:
# 1620 "data/maps/LittlerootTown/scripts.pory"
# 812 "data/maps/LittlerootTown/scripts.pory"
# 1621 "data/maps/LittlerootTown/scripts.pory"
	walk_left
# 1622 "data/maps/LittlerootTown/scripts.pory"
# 813 "data/maps/LittlerootTown/scripts.pory"
# 1623 "data/maps/LittlerootTown/scripts.pory"
	walk_left
# 1624 "data/maps/LittlerootTown/scripts.pory"
# 814 "data/maps/LittlerootTown/scripts.pory"
# 1625 "data/maps/LittlerootTown/scripts.pory"
	walk_left
# 1626 "data/maps/LittlerootTown/scripts.pory"
# 815 "data/maps/LittlerootTown/scripts.pory"
# 1627 "data/maps/LittlerootTown/scripts.pory"
	walk_left
# 1628 "data/maps/LittlerootTown/scripts.pory"
# 816 "data/maps/LittlerootTown/scripts.pory"
# 1629 "data/maps/LittlerootTown/scripts.pory"
	walk_in_place_faster_up
# 1630 "data/maps/LittlerootTown/scripts.pory"
# 817 "data/maps/LittlerootTown/scripts.pory"
# 1631 "data/maps/LittlerootTown/scripts.pory"
	step_end
# 1632 "data/maps/LittlerootTown/scripts.pory"
# 818 "data/maps/LittlerootTown/scripts.pory"
# 1633 "data/maps/LittlerootTown/scripts.pory"

# 1634 "data/maps/LittlerootTown/scripts.pory"
# 819 "data/maps/LittlerootTown/scripts.pory"
# 1635 "data/maps/LittlerootTown/scripts.pory"
LittlerootTown_Movement_MomReturnHomeMale3:
# 1636 "data/maps/LittlerootTown/scripts.pory"
# 820 "data/maps/LittlerootTown/scripts.pory"
# 1637 "data/maps/LittlerootTown/scripts.pory"
	walk_left
# 1638 "data/maps/LittlerootTown/scripts.pory"
# 821 "data/maps/LittlerootTown/scripts.pory"
# 1639 "data/maps/LittlerootTown/scripts.pory"
	walk_left
# 1640 "data/maps/LittlerootTown/scripts.pory"
# 822 "data/maps/LittlerootTown/scripts.pory"
# 1641 "data/maps/LittlerootTown/scripts.pory"
	walk_left
# 1642 "data/maps/LittlerootTown/scripts.pory"
# 823 "data/maps/LittlerootTown/scripts.pory"
# 1643 "data/maps/LittlerootTown/scripts.pory"
	walk_left
# 1644 "data/maps/LittlerootTown/scripts.pory"
# 824 "data/maps/LittlerootTown/scripts.pory"
# 1645 "data/maps/LittlerootTown/scripts.pory"
	walk_left
# 1646 "data/maps/LittlerootTown/scripts.pory"
# 825 "data/maps/LittlerootTown/scripts.pory"
# 1647 "data/maps/LittlerootTown/scripts.pory"
	walk_in_place_faster_up
# 1648 "data/maps/LittlerootTown/scripts.pory"
# 826 "data/maps/LittlerootTown/scripts.pory"
# 1649 "data/maps/LittlerootTown/scripts.pory"
	step_end
# 1650 "data/maps/LittlerootTown/scripts.pory"
# 827 "data/maps/LittlerootTown/scripts.pory"
# 1651 "data/maps/LittlerootTown/scripts.pory"

# 1652 "data/maps/LittlerootTown/scripts.pory"
# 828 "data/maps/LittlerootTown/scripts.pory"
# 1653 "data/maps/LittlerootTown/scripts.pory"
LittlerootTown_Movement_MomReturnHomeMale4:
# 1654 "data/maps/LittlerootTown/scripts.pory"
# 829 "data/maps/LittlerootTown/scripts.pory"
# 1655 "data/maps/LittlerootTown/scripts.pory"
	walk_left
# 1656 "data/maps/LittlerootTown/scripts.pory"
# 830 "data/maps/LittlerootTown/scripts.pory"
# 1657 "data/maps/LittlerootTown/scripts.pory"
	walk_left
# 1658 "data/maps/LittlerootTown/scripts.pory"
# 831 "data/maps/LittlerootTown/scripts.pory"
# 1659 "data/maps/LittlerootTown/scripts.pory"
	walk_in_place_faster_up
# 1660 "data/maps/LittlerootTown/scripts.pory"
# 832 "data/maps/LittlerootTown/scripts.pory"
# 1661 "data/maps/LittlerootTown/scripts.pory"
	step_end
# 1662 "data/maps/LittlerootTown/scripts.pory"
# 833 "data/maps/LittlerootTown/scripts.pory"
# 1663 "data/maps/LittlerootTown/scripts.pory"

# 1664 "data/maps/LittlerootTown/scripts.pory"
# 834 "data/maps/LittlerootTown/scripts.pory"
# 1665 "data/maps/LittlerootTown/scripts.pory"
LittlerootTown_Movement_MomReturnHomeMale5:
# 1666 "data/maps/LittlerootTown/scripts.pory"
# 835 "data/maps/LittlerootTown/scripts.pory"
# 1667 "data/maps/LittlerootTown/scripts.pory"
	walk_left
# 1668 "data/maps/LittlerootTown/scripts.pory"
# 836 "data/maps/LittlerootTown/scripts.pory"
# 1669 "data/maps/LittlerootTown/scripts.pory"
	walk_left
# 1670 "data/maps/LittlerootTown/scripts.pory"
# 837 "data/maps/LittlerootTown/scripts.pory"
# 1671 "data/maps/LittlerootTown/scripts.pory"
	walk_left
# 1672 "data/maps/LittlerootTown/scripts.pory"
# 838 "data/maps/LittlerootTown/scripts.pory"
# 1673 "data/maps/LittlerootTown/scripts.pory"
	walk_in_place_faster_up
# 1674 "data/maps/LittlerootTown/scripts.pory"
# 839 "data/maps/LittlerootTown/scripts.pory"
# 1675 "data/maps/LittlerootTown/scripts.pory"
	step_end
# 1676 "data/maps/LittlerootTown/scripts.pory"
# 840 "data/maps/LittlerootTown/scripts.pory"
# 1677 "data/maps/LittlerootTown/scripts.pory"

# 1678 "data/maps/LittlerootTown/scripts.pory"
# 841 "data/maps/LittlerootTown/scripts.pory"
# 1679 "data/maps/LittlerootTown/scripts.pory"
LittlerootTown_Movement_MomReturnHomeFemale2:
# 1680 "data/maps/LittlerootTown/scripts.pory"
# 842 "data/maps/LittlerootTown/scripts.pory"
# 1681 "data/maps/LittlerootTown/scripts.pory"
	walk_right
# 1682 "data/maps/LittlerootTown/scripts.pory"
# 843 "data/maps/LittlerootTown/scripts.pory"
# 1683 "data/maps/LittlerootTown/scripts.pory"
	walk_right
# 1684 "data/maps/LittlerootTown/scripts.pory"
# 844 "data/maps/LittlerootTown/scripts.pory"
# 1685 "data/maps/LittlerootTown/scripts.pory"
	walk_right
# 1686 "data/maps/LittlerootTown/scripts.pory"
# 845 "data/maps/LittlerootTown/scripts.pory"
# 1687 "data/maps/LittlerootTown/scripts.pory"
	walk_in_place_faster_up
# 1688 "data/maps/LittlerootTown/scripts.pory"
# 846 "data/maps/LittlerootTown/scripts.pory"
# 1689 "data/maps/LittlerootTown/scripts.pory"
	step_end
# 1690 "data/maps/LittlerootTown/scripts.pory"
# 847 "data/maps/LittlerootTown/scripts.pory"
# 1691 "data/maps/LittlerootTown/scripts.pory"

# 1692 "data/maps/LittlerootTown/scripts.pory"
# 848 "data/maps/LittlerootTown/scripts.pory"
# 1693 "data/maps/LittlerootTown/scripts.pory"
LittlerootTown_Movement_MomReturnHomeFemale3:
# 1694 "data/maps/LittlerootTown/scripts.pory"
# 849 "data/maps/LittlerootTown/scripts.pory"
# 1695 "data/maps/LittlerootTown/scripts.pory"
	walk_right
# 1696 "data/maps/LittlerootTown/scripts.pory"
# 850 "data/maps/LittlerootTown/scripts.pory"
# 1697 "data/maps/LittlerootTown/scripts.pory"
	walk_right
# 1698 "data/maps/LittlerootTown/scripts.pory"
# 851 "data/maps/LittlerootTown/scripts.pory"
# 1699 "data/maps/LittlerootTown/scripts.pory"
	walk_in_place_faster_up
# 1700 "data/maps/LittlerootTown/scripts.pory"
# 852 "data/maps/LittlerootTown/scripts.pory"
# 1701 "data/maps/LittlerootTown/scripts.pory"
	step_end
# 1702 "data/maps/LittlerootTown/scripts.pory"
# 853 "data/maps/LittlerootTown/scripts.pory"
# 1703 "data/maps/LittlerootTown/scripts.pory"

# 1704 "data/maps/LittlerootTown/scripts.pory"
# 854 "data/maps/LittlerootTown/scripts.pory"
# 1705 "data/maps/LittlerootTown/scripts.pory"
LittlerootTown_Movement_MomReturnHomeFemale4:
# 1706 "data/maps/LittlerootTown/scripts.pory"
# 855 "data/maps/LittlerootTown/scripts.pory"
# 1707 "data/maps/LittlerootTown/scripts.pory"
	walk_right
# 1708 "data/maps/LittlerootTown/scripts.pory"
# 856 "data/maps/LittlerootTown/scripts.pory"
# 1709 "data/maps/LittlerootTown/scripts.pory"
	walk_right
# 1710 "data/maps/LittlerootTown/scripts.pory"
# 857 "data/maps/LittlerootTown/scripts.pory"
# 1711 "data/maps/LittlerootTown/scripts.pory"
	walk_right
# 1712 "data/maps/LittlerootTown/scripts.pory"
# 858 "data/maps/LittlerootTown/scripts.pory"
# 1713 "data/maps/LittlerootTown/scripts.pory"
	walk_right
# 1714 "data/maps/LittlerootTown/scripts.pory"
# 859 "data/maps/LittlerootTown/scripts.pory"
# 1715 "data/maps/LittlerootTown/scripts.pory"
	walk_right
# 1716 "data/maps/LittlerootTown/scripts.pory"
# 860 "data/maps/LittlerootTown/scripts.pory"
# 1717 "data/maps/LittlerootTown/scripts.pory"
	walk_in_place_faster_up
# 1718 "data/maps/LittlerootTown/scripts.pory"
# 861 "data/maps/LittlerootTown/scripts.pory"
# 1719 "data/maps/LittlerootTown/scripts.pory"
	step_end
# 1720 "data/maps/LittlerootTown/scripts.pory"
# 862 "data/maps/LittlerootTown/scripts.pory"
# 1721 "data/maps/LittlerootTown/scripts.pory"

# 1722 "data/maps/LittlerootTown/scripts.pory"
# 863 "data/maps/LittlerootTown/scripts.pory"
# 1723 "data/maps/LittlerootTown/scripts.pory"
LittlerootTown_Movement_MomReturnHomeFemale5:
# 1724 "data/maps/LittlerootTown/scripts.pory"
# 864 "data/maps/LittlerootTown/scripts.pory"
# 1725 "data/maps/LittlerootTown/scripts.pory"
	walk_right
# 1726 "data/maps/LittlerootTown/scripts.pory"
# 865 "data/maps/LittlerootTown/scripts.pory"
# 1727 "data/maps/LittlerootTown/scripts.pory"
	walk_right
# 1728 "data/maps/LittlerootTown/scripts.pory"
# 866 "data/maps/LittlerootTown/scripts.pory"
# 1729 "data/maps/LittlerootTown/scripts.pory"
	walk_right
# 1730 "data/maps/LittlerootTown/scripts.pory"
# 867 "data/maps/LittlerootTown/scripts.pory"
# 1731 "data/maps/LittlerootTown/scripts.pory"
	walk_right
# 1732 "data/maps/LittlerootTown/scripts.pory"
# 868 "data/maps/LittlerootTown/scripts.pory"
# 1733 "data/maps/LittlerootTown/scripts.pory"
	walk_in_place_faster_up
# 1734 "data/maps/LittlerootTown/scripts.pory"
# 869 "data/maps/LittlerootTown/scripts.pory"
# 1735 "data/maps/LittlerootTown/scripts.pory"
	step_end
# 1736 "data/maps/LittlerootTown/scripts.pory"
# 870 "data/maps/LittlerootTown/scripts.pory"
# 1737 "data/maps/LittlerootTown/scripts.pory"

# 1738 "data/maps/LittlerootTown/scripts.pory"
# 871 "data/maps/LittlerootTown/scripts.pory"
# 1739 "data/maps/LittlerootTown/scripts.pory"
LittlerootTown_Movement_MomExitThroughDoor:
# 1740 "data/maps/LittlerootTown/scripts.pory"
# 872 "data/maps/LittlerootTown/scripts.pory"
# 1741 "data/maps/LittlerootTown/scripts.pory"
	walk_up
# 1742 "data/maps/LittlerootTown/scripts.pory"
# 873 "data/maps/LittlerootTown/scripts.pory"
# 1743 "data/maps/LittlerootTown/scripts.pory"
	step_end
# 1744 "data/maps/LittlerootTown/scripts.pory"
# 874 "data/maps/LittlerootTown/scripts.pory"
# 1745 "data/maps/LittlerootTown/scripts.pory"

# 1746 "data/maps/LittlerootTown/scripts.pory"
# 875 "data/maps/LittlerootTown/scripts.pory"
# 1747 "data/maps/LittlerootTown/scripts.pory"
LittlerootTown_EventScript_Mom::
# 1748 "data/maps/LittlerootTown/scripts.pory"
# 876 "data/maps/LittlerootTown/scripts.pory"
# 1749 "data/maps/LittlerootTown/scripts.pory"
	lock
# 1750 "data/maps/LittlerootTown/scripts.pory"
# 877 "data/maps/LittlerootTown/scripts.pory"
# 1751 "data/maps/LittlerootTown/scripts.pory"
	faceplayer
# 1752 "data/maps/LittlerootTown/scripts.pory"
# 878 "data/maps/LittlerootTown/scripts.pory"
# 1753 "data/maps/LittlerootTown/scripts.pory"
	checkplayergender
# 1754 "data/maps/LittlerootTown/scripts.pory"
# 879 "data/maps/LittlerootTown/scripts.pory"
# 1755 "data/maps/LittlerootTown/scripts.pory"
	call_if_eq VAR_RESULT, MALE, LittlerootTown_EventScript_SetHomeDoorCoordsMale
# 1756 "data/maps/LittlerootTown/scripts.pory"
# 880 "data/maps/LittlerootTown/scripts.pory"
# 1757 "data/maps/LittlerootTown/scripts.pory"
	call_if_eq VAR_RESULT, FEMALE, LittlerootTown_EventScript_SetHomeDoorCoordsFemale
# 1758 "data/maps/LittlerootTown/scripts.pory"
# 881 "data/maps/LittlerootTown/scripts.pory"
# 1759 "data/maps/LittlerootTown/scripts.pory"
	call LittlerootTown_EventScript_GiveRunningShoes
# 1760 "data/maps/LittlerootTown/scripts.pory"
# 882 "data/maps/LittlerootTown/scripts.pory"
# 1761 "data/maps/LittlerootTown/scripts.pory"
	applymovement LOCALID_MOM, Common_Movement_WalkInPlaceFasterUp
# 1762 "data/maps/LittlerootTown/scripts.pory"
# 883 "data/maps/LittlerootTown/scripts.pory"
# 1763 "data/maps/LittlerootTown/scripts.pory"
	waitmovement 0
# 1764 "data/maps/LittlerootTown/scripts.pory"
# 884 "data/maps/LittlerootTown/scripts.pory"
# 1765 "data/maps/LittlerootTown/scripts.pory"
	opendoor VAR_0x8009, VAR_0x800A
# 1766 "data/maps/LittlerootTown/scripts.pory"
# 885 "data/maps/LittlerootTown/scripts.pory"
# 1767 "data/maps/LittlerootTown/scripts.pory"
	waitdooranim
# 1768 "data/maps/LittlerootTown/scripts.pory"
# 886 "data/maps/LittlerootTown/scripts.pory"
# 1769 "data/maps/LittlerootTown/scripts.pory"
	applymovement LOCALID_MOM, LittlerootTown_Movement_MomExitThroughDoor
# 1770 "data/maps/LittlerootTown/scripts.pory"
# 887 "data/maps/LittlerootTown/scripts.pory"
# 1771 "data/maps/LittlerootTown/scripts.pory"
	waitmovement 0
# 1772 "data/maps/LittlerootTown/scripts.pory"
# 888 "data/maps/LittlerootTown/scripts.pory"
# 1773 "data/maps/LittlerootTown/scripts.pory"
	hideobjectat LOCALID_MOM, MAP_LITTLEROOT_TOWN
# 1774 "data/maps/LittlerootTown/scripts.pory"
# 889 "data/maps/LittlerootTown/scripts.pory"
# 1775 "data/maps/LittlerootTown/scripts.pory"
	closedoor VAR_0x8009, VAR_0x800A
# 1776 "data/maps/LittlerootTown/scripts.pory"
# 890 "data/maps/LittlerootTown/scripts.pory"
# 1777 "data/maps/LittlerootTown/scripts.pory"
	waitdooranim
# 1778 "data/maps/LittlerootTown/scripts.pory"
# 891 "data/maps/LittlerootTown/scripts.pory"
# 1779 "data/maps/LittlerootTown/scripts.pory"
	goto LittlerootTown_EventScript_SetReceivedRunningShoes
# 1780 "data/maps/LittlerootTown/scripts.pory"
# 892 "data/maps/LittlerootTown/scripts.pory"
# 1781 "data/maps/LittlerootTown/scripts.pory"
	end
# 1782 "data/maps/LittlerootTown/scripts.pory"
# 893 "data/maps/LittlerootTown/scripts.pory"
# 1783 "data/maps/LittlerootTown/scripts.pory"

# 1784 "data/maps/LittlerootTown/scripts.pory"
# 894 "data/maps/LittlerootTown/scripts.pory"
# 1785 "data/maps/LittlerootTown/scripts.pory"
LittlerootTown_EventScript_SetReceivedRunningShoes::
# 1786 "data/maps/LittlerootTown/scripts.pory"
# 895 "data/maps/LittlerootTown/scripts.pory"
# 1787 "data/maps/LittlerootTown/scripts.pory"
	removeobject LOCALID_MOM
# 1788 "data/maps/LittlerootTown/scripts.pory"
# 896 "data/maps/LittlerootTown/scripts.pory"
# 1789 "data/maps/LittlerootTown/scripts.pory"
# 897 "data/maps/LittlerootTown/scripts.pory"
# 1790 "data/maps/LittlerootTown/scripts.pory"
	setvar VAR_LITTLEROOT_TOWN_STATE, 4
# 1791 "data/maps/LittlerootTown/scripts.pory"
# 898 "data/maps/LittlerootTown/scripts.pory"
# 1792 "data/maps/LittlerootTown/scripts.pory"
	release
# 1793 "data/maps/LittlerootTown/scripts.pory"
# 899 "data/maps/LittlerootTown/scripts.pory"
# 1794 "data/maps/LittlerootTown/scripts.pory"
	end
# 1795 "data/maps/LittlerootTown/scripts.pory"
# 900 "data/maps/LittlerootTown/scripts.pory"
# 1796 "data/maps/LittlerootTown/scripts.pory"

# 1797 "data/maps/LittlerootTown/scripts.pory"
# 901 "data/maps/LittlerootTown/scripts.pory"
# 1798 "data/maps/LittlerootTown/scripts.pory"
LittlerootTown_EventScript_GiveRunningShoes::
# 1799 "data/maps/LittlerootTown/scripts.pory"
# 902 "data/maps/LittlerootTown/scripts.pory"
# 1800 "data/maps/LittlerootTown/scripts.pory"
	msgbox LittlerootTown_Text_WearTheseRunningShoes, MSGBOX_DEFAULT
# 1801 "data/maps/LittlerootTown/scripts.pory"
# 903 "data/maps/LittlerootTown/scripts.pory"
# 1802 "data/maps/LittlerootTown/scripts.pory"
# 906 "data/maps/LittlerootTown/scripts.pory"
# 1803 "data/maps/LittlerootTown/scripts.pory"
	setflag FLAG_RECEIVED_RUNNING_SHOES
# 1804 "data/maps/LittlerootTown/scripts.pory"
	setflag FLAG_SYS_B_DASH
# 1805 "data/maps/LittlerootTown/scripts.pory"
# 907 "data/maps/LittlerootTown/scripts.pory"
# 1806 "data/maps/LittlerootTown/scripts.pory"
	giveitem ITEM_INFINITE_CANDY
# 1807 "data/maps/LittlerootTown/scripts.pory"
	setflag FLAG_SYS_DEXNAV_GET
# 1808 "data/maps/LittlerootTown/scripts.pory"
	playfanfare MUS_OBTAIN_ITEM
# 1809 "data/maps/LittlerootTown/scripts.pory"
	msgbox LittlerootTown_Text_ReceivedPokeVial, MSGBOX_DEFAULT
# 1810 "data/maps/LittlerootTown/scripts.pory"
	waitfanfare
# 1811 "data/maps/LittlerootTown/scripts.pory"
	playfanfare MUS_OBTAIN_ITEM
# 1812 "data/maps/LittlerootTown/scripts.pory"
	msgbox LittlerootTown_Text_ReceivedInfiniteRepel, MSGBOX_DEFAULT
# 1813 "data/maps/LittlerootTown/scripts.pory"
	waitfanfare
# 1814 "data/maps/LittlerootTown/scripts.pory"
	playfanfare MUS_OBTAIN_ITEM
# 1815 "data/maps/LittlerootTown/scripts.pory"
	msgbox LittlerootTown_Text_ReceivedDexNav, MSGBOX_DEFAULT
# 1816 "data/maps/LittlerootTown/scripts.pory"
	waitfanfare
# 1817 "data/maps/LittlerootTown/scripts.pory"
	msgbox LittlerootTown_Text_ExplainNewGear, MSGBOX_DEFAULT
# 1818 "data/maps/LittlerootTown/scripts.pory"
	msgbox LittlerootTown_Text_ComeHomeIfAnythingHappens, MSGBOX_DEFAULT
# 1819 "data/maps/LittlerootTown/scripts.pory"
# 909 "data/maps/LittlerootTown/scripts.pory"
# 1820 "data/maps/LittlerootTown/scripts.pory"
	closemessage
# 1821 "data/maps/LittlerootTown/scripts.pory"
# 910 "data/maps/LittlerootTown/scripts.pory"
# 1822 "data/maps/LittlerootTown/scripts.pory"
	delay 30
# 1823 "data/maps/LittlerootTown/scripts.pory"
# 911 "data/maps/LittlerootTown/scripts.pory"
# 1824 "data/maps/LittlerootTown/scripts.pory"
	return
# 1825 "data/maps/LittlerootTown/scripts.pory"
# 912 "data/maps/LittlerootTown/scripts.pory"
# 1826 "data/maps/LittlerootTown/scripts.pory"

# 1827 "data/maps/LittlerootTown/scripts.pory"
# 913 "data/maps/LittlerootTown/scripts.pory"
# 1828 "data/maps/LittlerootTown/scripts.pory"
LittlerootTown_Text_OurNewHomeLetsGoInside:
# 1829 "data/maps/LittlerootTown/scripts.pory"
# 914 "data/maps/LittlerootTown/scripts.pory"
# 1830 "data/maps/LittlerootTown/scripts.pory"
	.string "{PLAYER}, we're here, honey!\p"
# 1831 "data/maps/LittlerootTown/scripts.pory"
# 915 "data/maps/LittlerootTown/scripts.pory"
# 1832 "data/maps/LittlerootTown/scripts.pory"
	.string "It must be tiring riding with our things\n"
# 1833 "data/maps/LittlerootTown/scripts.pory"
# 916 "data/maps/LittlerootTown/scripts.pory"
# 1834 "data/maps/LittlerootTown/scripts.pory"
	.string "in the moving truck.\p"
# 1835 "data/maps/LittlerootTown/scripts.pory"
# 917 "data/maps/LittlerootTown/scripts.pory"
# 1836 "data/maps/LittlerootTown/scripts.pory"
	.string "Well, this is Littleroot Town.\p"
# 1837 "data/maps/LittlerootTown/scripts.pory"
# 918 "data/maps/LittlerootTown/scripts.pory"
# 1838 "data/maps/LittlerootTown/scripts.pory"
	.string "How do you like it?\n"
# 1839 "data/maps/LittlerootTown/scripts.pory"
# 919 "data/maps/LittlerootTown/scripts.pory"
# 1840 "data/maps/LittlerootTown/scripts.pory"
	.string "This is our new home!\p"
# 1841 "data/maps/LittlerootTown/scripts.pory"
# 920 "data/maps/LittlerootTown/scripts.pory"
# 1842 "data/maps/LittlerootTown/scripts.pory"
	.string "It has a quaint feel, but it seems to be\n"
# 1843 "data/maps/LittlerootTown/scripts.pory"
# 921 "data/maps/LittlerootTown/scripts.pory"
# 1844 "data/maps/LittlerootTown/scripts.pory"
	.string "an easy place to live, don't you think?\p"
# 1845 "data/maps/LittlerootTown/scripts.pory"
# 922 "data/maps/LittlerootTown/scripts.pory"
# 1846 "data/maps/LittlerootTown/scripts.pory"
	.string "And, you get your own room, {PLAYER}!\n"
# 1847 "data/maps/LittlerootTown/scripts.pory"
# 923 "data/maps/LittlerootTown/scripts.pory"
# 1848 "data/maps/LittlerootTown/scripts.pory"
	.string "Let's go inside.$"
# 1849 "data/maps/LittlerootTown/scripts.pory"
# 924 "data/maps/LittlerootTown/scripts.pory"
# 1850 "data/maps/LittlerootTown/scripts.pory"

# 1851 "data/maps/LittlerootTown/scripts.pory"
# 925 "data/maps/LittlerootTown/scripts.pory"
# 1852 "data/maps/LittlerootTown/scripts.pory"
LittlerootTown_Text_WaitPlayer:
# 1853 "data/maps/LittlerootTown/scripts.pory"
# 926 "data/maps/LittlerootTown/scripts.pory"
# 1854 "data/maps/LittlerootTown/scripts.pory"
	.string "Wait, {PLAYER}!$"
# 1855 "data/maps/LittlerootTown/scripts.pory"
# 927 "data/maps/LittlerootTown/scripts.pory"
# 1856 "data/maps/LittlerootTown/scripts.pory"

# 1857 "data/maps/LittlerootTown/scripts.pory"
# 928 "data/maps/LittlerootTown/scripts.pory"
# 1858 "data/maps/LittlerootTown/scripts.pory"
LittlerootTown_Text_WearTheseRunningShoes:
# 1859 "data/maps/LittlerootTown/scripts.pory"
# 929 "data/maps/LittlerootTown/scripts.pory"
# 1860 "data/maps/LittlerootTown/scripts.pory"
	.string "{PLAYER}! {PLAYER}! Did you\n"
# 1861 "data/maps/LittlerootTown/scripts.pory"
# 930 "data/maps/LittlerootTown/scripts.pory"
# 1862 "data/maps/LittlerootTown/scripts.pory"
	.string "introduce yourself to Prof. Birch?\p"
# 1863 "data/maps/LittlerootTown/scripts.pory"
# 931 "data/maps/LittlerootTown/scripts.pory"
# 1864 "data/maps/LittlerootTown/scripts.pory"
	.string "Oh! What an adorable Pokémon!\n"
# 1865 "data/maps/LittlerootTown/scripts.pory"
# 932 "data/maps/LittlerootTown/scripts.pory"
# 1866 "data/maps/LittlerootTown/scripts.pory"
	.string "You got it from Prof. Birch. How nice!\p"
# 1867 "data/maps/LittlerootTown/scripts.pory"
# 933 "data/maps/LittlerootTown/scripts.pory"
# 1868 "data/maps/LittlerootTown/scripts.pory"
	.string "You're your father's child, all right.\n"
# 1869 "data/maps/LittlerootTown/scripts.pory"
# 934 "data/maps/LittlerootTown/scripts.pory"
# 1870 "data/maps/LittlerootTown/scripts.pory"
	.string "You look good together with Pokémon!\p"
# 1871 "data/maps/LittlerootTown/scripts.pory"
# 935 "data/maps/LittlerootTown/scripts.pory"
# 1872 "data/maps/LittlerootTown/scripts.pory"
	.string "Here, honey! If you're going out on an\n"
# 1873 "data/maps/LittlerootTown/scripts.pory"
# 936 "data/maps/LittlerootTown/scripts.pory"
# 1874 "data/maps/LittlerootTown/scripts.pory"
	.string "adventure, take these!$"
# 1875 "data/maps/LittlerootTown/scripts.pory"

# 1876 "data/maps/LittlerootTown/scripts.pory"
# 950 "data/maps/LittlerootTown/scripts.pory"
# 1877 "data/maps/LittlerootTown/scripts.pory"
LittlerootTown_Text_ExplainNewGear:
# 1878 "data/maps/LittlerootTown/scripts.pory"
	.string "That Infinite Candy is basically a\n"
# 1879 "data/maps/LittlerootTown/scripts.pory"
	.string "Rare Candy that will never run out,\l"
# 1880 "data/maps/LittlerootTown/scripts.pory"
	.string "it's in your Key Items!\p"
# 1881 "data/maps/LittlerootTown/scripts.pory"
	.string "I also gave you a PokéVial that will\n"
# 1882 "data/maps/LittlerootTown/scripts.pory"
	.string "heal your party from anywhere, an\l"
# 1883 "data/maps/LittlerootTown/scripts.pory"
	.string "Infinite Repel, which is a Repel that\l"
# 1884 "data/maps/LittlerootTown/scripts.pory"
	.string "will never run out, and a brand new\l"
# 1885 "data/maps/LittlerootTown/scripts.pory"
	.string "DexNav to help you find Pokémon!\p"
# 1886 "data/maps/LittlerootTown/scripts.pory"
	.string "{COLOR GREEN}{SHADOW LIGHT_GREEN}If you press the “L” button, you can\n"
# 1887 "data/maps/LittlerootTown/scripts.pory"
	.string "see a second menu.\p"
# 1888 "data/maps/LittlerootTown/scripts.pory"
	.string "{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}This menu will have new options on it,\n"
# 1889 "data/maps/LittlerootTown/scripts.pory"
	.string "including the PokéVial, the Infinite\l"
# 1890 "data/maps/LittlerootTown/scripts.pory"
	.string "Repel, and the DexNav!$"
# 1891 "data/maps/LittlerootTown/scripts.pory"

# 1892 "data/maps/LittlerootTown/scripts.pory"
LittlerootTown_Text_ReceivedDexNav:
# 1893 "data/maps/LittlerootTown/scripts.pory"
	.string "Obtained the DexNav!$"
# 1894 "data/maps/LittlerootTown/scripts.pory"

# 1895 "data/maps/LittlerootTown/scripts.pory"
LittlerootTown_Text_ReceivedInfiniteRepel:
# 1896 "data/maps/LittlerootTown/scripts.pory"
	.string "Obtained the Infinite Repel!$"
# 1897 "data/maps/LittlerootTown/scripts.pory"

# 1898 "data/maps/LittlerootTown/scripts.pory"
LittlerootTown_Text_ReceivedPokeVial:
# 1899 "data/maps/LittlerootTown/scripts.pory"
	.string "Obtained the PokéVial!$"
# 1900 "data/maps/LittlerootTown/scripts.pory"

# 1901 "data/maps/LittlerootTown/scripts.pory"
# 951 "data/maps/LittlerootTown/scripts.pory"
# 1902 "data/maps/LittlerootTown/scripts.pory"
LittlerootTown_Text_ComeHomeIfAnythingHappens:
# 1903 "data/maps/LittlerootTown/scripts.pory"
# 952 "data/maps/LittlerootTown/scripts.pory"
# 1904 "data/maps/LittlerootTown/scripts.pory"
	.string "… … … … … … … …\n"
# 1905 "data/maps/LittlerootTown/scripts.pory"
# 953 "data/maps/LittlerootTown/scripts.pory"
# 1906 "data/maps/LittlerootTown/scripts.pory"
	.string "… … … … … … … …\p"
# 1907 "data/maps/LittlerootTown/scripts.pory"
# 954 "data/maps/LittlerootTown/scripts.pory"
# 1908 "data/maps/LittlerootTown/scripts.pory"
	.string "To think that you have your very own\n"
# 1909 "data/maps/LittlerootTown/scripts.pory"
# 955 "data/maps/LittlerootTown/scripts.pory"
# 1910 "data/maps/LittlerootTown/scripts.pory"
	.string "Pokémon now…\l"
# 1911 "data/maps/LittlerootTown/scripts.pory"
# 956 "data/maps/LittlerootTown/scripts.pory"
# 1912 "data/maps/LittlerootTown/scripts.pory"
	.string "Your father will be overjoyed.\p"
# 1913 "data/maps/LittlerootTown/scripts.pory"
# 957 "data/maps/LittlerootTown/scripts.pory"
# 1914 "data/maps/LittlerootTown/scripts.pory"
	.string "…But please be careful.\n"
# 1915 "data/maps/LittlerootTown/scripts.pory"
# 958 "data/maps/LittlerootTown/scripts.pory"
# 1916 "data/maps/LittlerootTown/scripts.pory"
	.string "If anything happens, you can come home.\p"
# 1917 "data/maps/LittlerootTown/scripts.pory"
# 959 "data/maps/LittlerootTown/scripts.pory"
# 1918 "data/maps/LittlerootTown/scripts.pory"
	.string "Go on, go get them, honey!$"
# 1919 "data/maps/LittlerootTown/scripts.pory"
# 960 "data/maps/LittlerootTown/scripts.pory"
# 1920 "data/maps/LittlerootTown/scripts.pory"

# 1921 "data/maps/LittlerootTown/scripts.pory"
# 961 "data/maps/LittlerootTown/scripts.pory"
# 1922 "data/maps/LittlerootTown/scripts.pory"
LittlerootTown_Text_CanUsePCToStoreItems:
# 1923 "data/maps/LittlerootTown/scripts.pory"
# 962 "data/maps/LittlerootTown/scripts.pory"
# 1924 "data/maps/LittlerootTown/scripts.pory"
	.string "Huh, I swear the lab used to be\n"
# 1925 "data/maps/LittlerootTown/scripts.pory"
# 963 "data/maps/LittlerootTown/scripts.pory"
# 1926 "data/maps/LittlerootTown/scripts.pory"
	.string "right here. Weird.$"
# 1927 "data/maps/LittlerootTown/scripts.pory"
# 964 "data/maps/LittlerootTown/scripts.pory"
# 1928 "data/maps/LittlerootTown/scripts.pory"
# 965 "data/maps/LittlerootTown/scripts.pory"
# 1929 "data/maps/LittlerootTown/scripts.pory"

# 1930 "data/maps/LittlerootTown/scripts.pory"
# 966 "data/maps/LittlerootTown/scripts.pory"
# 1931 "data/maps/LittlerootTown/scripts.pory"
LittlerootTown_Text_BirchSpendsDaysInLab:
# 1932 "data/maps/LittlerootTown/scripts.pory"
# 967 "data/maps/LittlerootTown/scripts.pory"
# 1933 "data/maps/LittlerootTown/scripts.pory"
	.string "Prof. Birch spends days in his lab\n"
# 1934 "data/maps/LittlerootTown/scripts.pory"
# 968 "data/maps/LittlerootTown/scripts.pory"
# 1935 "data/maps/LittlerootTown/scripts.pory"
	.string "studying, then he'll suddenly go out in\l"
# 1936 "data/maps/LittlerootTown/scripts.pory"
# 969 "data/maps/LittlerootTown/scripts.pory"
# 1937 "data/maps/LittlerootTown/scripts.pory"
	.string "the wild to do more research…\p"
# 1938 "data/maps/LittlerootTown/scripts.pory"
# 970 "data/maps/LittlerootTown/scripts.pory"
# 1939 "data/maps/LittlerootTown/scripts.pory"
	.string "When does Prof. Birch spend time\n"
# 1940 "data/maps/LittlerootTown/scripts.pory"
# 971 "data/maps/LittlerootTown/scripts.pory"
# 1941 "data/maps/LittlerootTown/scripts.pory"
	.string "at home?$"
# 1942 "data/maps/LittlerootTown/scripts.pory"
# 972 "data/maps/LittlerootTown/scripts.pory"
# 1943 "data/maps/LittlerootTown/scripts.pory"

# 1944 "data/maps/LittlerootTown/scripts.pory"
# 973 "data/maps/LittlerootTown/scripts.pory"
# 1945 "data/maps/LittlerootTown/scripts.pory"
LittlerootTown_Text_IfYouGoInGrassPokemonWillJumpOut:
# 1946 "data/maps/LittlerootTown/scripts.pory"
# 974 "data/maps/LittlerootTown/scripts.pory"
# 1947 "data/maps/LittlerootTown/scripts.pory"
	.string "Um, um, um!\p"
# 1948 "data/maps/LittlerootTown/scripts.pory"
# 975 "data/maps/LittlerootTown/scripts.pory"
# 1949 "data/maps/LittlerootTown/scripts.pory"
	.string "If you go outside and go in the grass,\n"
# 1950 "data/maps/LittlerootTown/scripts.pory"
# 976 "data/maps/LittlerootTown/scripts.pory"
# 1951 "data/maps/LittlerootTown/scripts.pory"
	.string "wild Pokémon will jump out!$"
# 1952 "data/maps/LittlerootTown/scripts.pory"
# 977 "data/maps/LittlerootTown/scripts.pory"
# 1953 "data/maps/LittlerootTown/scripts.pory"

# 1954 "data/maps/LittlerootTown/scripts.pory"
# 978 "data/maps/LittlerootTown/scripts.pory"
# 1955 "data/maps/LittlerootTown/scripts.pory"
LittlerootTown_Text_DangerousIfYouDontHavePokemon:
# 1956 "data/maps/LittlerootTown/scripts.pory"
# 979 "data/maps/LittlerootTown/scripts.pory"
# 1957 "data/maps/LittlerootTown/scripts.pory"
	.string "It's dangerous if you don't have\n"
# 1958 "data/maps/LittlerootTown/scripts.pory"
# 980 "data/maps/LittlerootTown/scripts.pory"
# 1959 "data/maps/LittlerootTown/scripts.pory"
	.string "your own Pokémon.$"
# 1960 "data/maps/LittlerootTown/scripts.pory"
# 981 "data/maps/LittlerootTown/scripts.pory"
# 1961 "data/maps/LittlerootTown/scripts.pory"

# 1962 "data/maps/LittlerootTown/scripts.pory"
# 982 "data/maps/LittlerootTown/scripts.pory"
# 1963 "data/maps/LittlerootTown/scripts.pory"
LittlerootTown_Text_CanYouGoSeeWhatsHappening:
# 1964 "data/maps/LittlerootTown/scripts.pory"
# 983 "data/maps/LittlerootTown/scripts.pory"
# 1965 "data/maps/LittlerootTown/scripts.pory"
	.string "Um, hi!\p"
# 1966 "data/maps/LittlerootTown/scripts.pory"
# 984 "data/maps/LittlerootTown/scripts.pory"
# 1967 "data/maps/LittlerootTown/scripts.pory"
	.string "There are scary Pokémon outside!\n"
# 1968 "data/maps/LittlerootTown/scripts.pory"
# 985 "data/maps/LittlerootTown/scripts.pory"
# 1969 "data/maps/LittlerootTown/scripts.pory"
	.string "I can hear their cries!\p"
# 1970 "data/maps/LittlerootTown/scripts.pory"
# 986 "data/maps/LittlerootTown/scripts.pory"
# 1971 "data/maps/LittlerootTown/scripts.pory"
	.string "I want to go see what's going on,\n"
# 1972 "data/maps/LittlerootTown/scripts.pory"
# 987 "data/maps/LittlerootTown/scripts.pory"
# 1973 "data/maps/LittlerootTown/scripts.pory"
	.string "but I don't have any Pokémon…\p"
# 1974 "data/maps/LittlerootTown/scripts.pory"
# 988 "data/maps/LittlerootTown/scripts.pory"
# 1975 "data/maps/LittlerootTown/scripts.pory"
	.string "Can you go see what's happening\n"
# 1976 "data/maps/LittlerootTown/scripts.pory"
# 989 "data/maps/LittlerootTown/scripts.pory"
# 1977 "data/maps/LittlerootTown/scripts.pory"
	.string "for me?$"
# 1978 "data/maps/LittlerootTown/scripts.pory"
# 990 "data/maps/LittlerootTown/scripts.pory"
# 1979 "data/maps/LittlerootTown/scripts.pory"

# 1980 "data/maps/LittlerootTown/scripts.pory"
# 991 "data/maps/LittlerootTown/scripts.pory"
# 1981 "data/maps/LittlerootTown/scripts.pory"
LittlerootTown_Text_YouSavedBirch:
# 1982 "data/maps/LittlerootTown/scripts.pory"
# 992 "data/maps/LittlerootTown/scripts.pory"
# 1983 "data/maps/LittlerootTown/scripts.pory"
	.string "You have your own Pokémon!\n"
# 1984 "data/maps/LittlerootTown/scripts.pory"
# 993 "data/maps/LittlerootTown/scripts.pory"
# 1985 "data/maps/LittlerootTown/scripts.pory"
	.string "Cool!$"
# 1986 "data/maps/LittlerootTown/scripts.pory"
# 994 "data/maps/LittlerootTown/scripts.pory"
# 1987 "data/maps/LittlerootTown/scripts.pory"

# 1988 "data/maps/LittlerootTown/scripts.pory"
# 995 "data/maps/LittlerootTown/scripts.pory"
# 1989 "data/maps/LittlerootTown/scripts.pory"
LittlerootTown_Text_GoodLuckCatchingPokemon:
# 1990 "data/maps/LittlerootTown/scripts.pory"
# 996 "data/maps/LittlerootTown/scripts.pory"
# 1991 "data/maps/LittlerootTown/scripts.pory"
	.string "Are you going to catch Pokémon?\n"
# 1992 "data/maps/LittlerootTown/scripts.pory"
# 997 "data/maps/LittlerootTown/scripts.pory"
# 1993 "data/maps/LittlerootTown/scripts.pory"
	.string "Good luck!$"
# 1994 "data/maps/LittlerootTown/scripts.pory"
# 998 "data/maps/LittlerootTown/scripts.pory"
# 1995 "data/maps/LittlerootTown/scripts.pory"

# 1996 "data/maps/LittlerootTown/scripts.pory"
# 999 "data/maps/LittlerootTown/scripts.pory"
# 1997 "data/maps/LittlerootTown/scripts.pory"
LittlerootTown_Text_TownSign:
# 1998 "data/maps/LittlerootTown/scripts.pory"
# 1000 "data/maps/LittlerootTown/scripts.pory"
# 1999 "data/maps/LittlerootTown/scripts.pory"
	.string "Littleroot Town\n"
# 2000 "data/maps/LittlerootTown/scripts.pory"
# 1001 "data/maps/LittlerootTown/scripts.pory"
# 2001 "data/maps/LittlerootTown/scripts.pory"
	.string "“A town that can't be shaded any hue.”$"
# 2002 "data/maps/LittlerootTown/scripts.pory"
# 1002 "data/maps/LittlerootTown/scripts.pory"
# 2003 "data/maps/LittlerootTown/scripts.pory"

# 2004 "data/maps/LittlerootTown/scripts.pory"
# 1003 "data/maps/LittlerootTown/scripts.pory"
# 2005 "data/maps/LittlerootTown/scripts.pory"
LittlerootTown_Text_ProfBirchsLab:
# 2006 "data/maps/LittlerootTown/scripts.pory"
# 1004 "data/maps/LittlerootTown/scripts.pory"
# 2007 "data/maps/LittlerootTown/scripts.pory"
	.string "Prof. Birch's Pokémon Lab$"
# 2008 "data/maps/LittlerootTown/scripts.pory"
# 1005 "data/maps/LittlerootTown/scripts.pory"
# 2009 "data/maps/LittlerootTown/scripts.pory"

# 2010 "data/maps/LittlerootTown/scripts.pory"
# 1006 "data/maps/LittlerootTown/scripts.pory"
# 2011 "data/maps/LittlerootTown/scripts.pory"
LittlerootTown_Text_PlayersHouse:
# 2012 "data/maps/LittlerootTown/scripts.pory"
# 1007 "data/maps/LittlerootTown/scripts.pory"
# 2013 "data/maps/LittlerootTown/scripts.pory"
	.string "{PLAYER}'s House$"
# 2014 "data/maps/LittlerootTown/scripts.pory"
# 1008 "data/maps/LittlerootTown/scripts.pory"
# 2015 "data/maps/LittlerootTown/scripts.pory"

# 2016 "data/maps/LittlerootTown/scripts.pory"
# 1009 "data/maps/LittlerootTown/scripts.pory"
# 2017 "data/maps/LittlerootTown/scripts.pory"
LittlerootTown_Text_ProfBirchsHouse:
# 2018 "data/maps/LittlerootTown/scripts.pory"
# 1010 "data/maps/LittlerootTown/scripts.pory"
# 2019 "data/maps/LittlerootTown/scripts.pory"
	.string "Prof. Birch's House$"
# 2020 "data/maps/LittlerootTown/scripts.pory"
# 1011 "data/maps/LittlerootTown/scripts.pory"
# 2021 "data/maps/LittlerootTown/scripts.pory"

# 2022 "data/maps/LittlerootTown/scripts.pory"
# 1012 "data/maps/LittlerootTown/scripts.pory"
# 2023 "data/maps/LittlerootTown/scripts.pory"
LittlerootTown_Text_BirchSomethingToShowYouAtLab:
# 2024 "data/maps/LittlerootTown/scripts.pory"
# 1013 "data/maps/LittlerootTown/scripts.pory"
# 2025 "data/maps/LittlerootTown/scripts.pory"
	.string "Prof. Birch: Well, well, {PLAYER}{KUN}!\n"
# 2026 "data/maps/LittlerootTown/scripts.pory"
# 1014 "data/maps/LittlerootTown/scripts.pory"
# 2027 "data/maps/LittlerootTown/scripts.pory"
	.string "That was good work out there!\p"
# 2028 "data/maps/LittlerootTown/scripts.pory"
# 1015 "data/maps/LittlerootTown/scripts.pory"
# 2029 "data/maps/LittlerootTown/scripts.pory"
	.string "I knew there was something special\n"
# 2030 "data/maps/LittlerootTown/scripts.pory"
# 1016 "data/maps/LittlerootTown/scripts.pory"
# 2031 "data/maps/LittlerootTown/scripts.pory"
	.string "about you when I first saw you,\l"
# 2032 "data/maps/LittlerootTown/scripts.pory"
# 1017 "data/maps/LittlerootTown/scripts.pory"
# 2033 "data/maps/LittlerootTown/scripts.pory"
	.string "but I never expected this.\p"
# 2034 "data/maps/LittlerootTown/scripts.pory"
# 1018 "data/maps/LittlerootTown/scripts.pory"
# 2035 "data/maps/LittlerootTown/scripts.pory"
	.string "Oh, by the way, I have something to give\n"
# 2036 "data/maps/LittlerootTown/scripts.pory"
# 1019 "data/maps/LittlerootTown/scripts.pory"
# 2037 "data/maps/LittlerootTown/scripts.pory"
	.string "to you.\p"
# 2038 "data/maps/LittlerootTown/scripts.pory"
	.string "I always planned on giving this to the\n"
# 2039 "data/maps/LittlerootTown/scripts.pory"
	.string "next Hoenn Champion.\l"
# 2040 "data/maps/LittlerootTown/scripts.pory"
# 1020 "data/maps/LittlerootTown/scripts.pory"
# 2041 "data/maps/LittlerootTown/scripts.pory"
# 1021 "data/maps/LittlerootTown/scripts.pory"
# 2042 "data/maps/LittlerootTown/scripts.pory"
	.string "Let's go to my lab.$"
